-- generated by mise.py; do not edit

--$Name:t$
require "fmt"
require "parser/mp-ru"

local function fn_helper(s, w)
  p([[helper]])
end

obj {
  nam = "none";
}

Door = Class({
  from = 'none';
  to = 'none';
  door_to = function(s)
    if here() == _(s.from) then
      return _(s.to)
    end
    if here() == _(s.to) then
      return _(s.from)
    end
    return false
  end;
}, door):attr 'open'

Path = Class {
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(std.ref(s.walk_to)) then return end
    walk(s.walk_to)
  end;
  before_Default = function(s, ev, w)
    if s.desc then p(s.desc) return end
    p([[Ты можешь пойти в ]], std.ref(s.walk_to):noun('вн'), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

obj {
  -"коробка";
  nam = "box";
  title = "Коробка";
  score_value = 0;
}

_'box'.before_Take = function(s, w, wh)
  if s.score_value + 1 > 0 then
    p([[взяли]])
  end
end;
_'box'.Take = function(s, w, wh)
  p([[метод]])
end;
_'box'.after_Drop = fn_helper;
_'box'.Wait = fn_helper;
_'box'.Open = fn_helper;
_'box'.Close = fn_helper;
_'box'.after_Any = fn_helper;
_'box'.Any = fn_helper;
_'box'.Default = fn_helper;
