-- generated by mise.py; do not edit

--$Name:t$
require "fmt"
require "parser/mp-ru"

local function fn_helper()
  p([[helper]])
end

obj {
  nam = "none";
}

Door = Class({
  from = 'none';
  to = 'none';
  door_to = function(s)
    if here() == _(s.from) then
      return _(s.to)
    end
    if here() == _(s.to) then
      return _(s.from)
    end
    return false
  end;
}, door):attr 'open'

Path = Class {
  walk_to = 'none';
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(_(s.walk_to)) then
      return
    end
    walk(_(s.walk_to))
  end;
  before_Default = function(s, ev, w, wh)
    local d = (s.desc)
    if d then
      p(d)
      return
    end
    p('Ты можешь пойти в ', _(s.walk_to):noun_hint("вн"), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

obj {
  -"коробка";
  nam = "box";
  title = "Коробка";
  score_value = 0;
}

_'box'.before_Take = function(s, w, wh)
  if s.score_value + 1 > 0 then
    p([[взяли]])
  end
end;
_'box'.Take = function(s, w, wh)
  p([[метод]])
end;
_'box'.after_Drop = fn_helper;
_'box'.Wait = fn_helper;
_'box'.Open = fn_helper;
_'box'.Close = fn_helper;
_'box'.after_Any = fn_helper;
_'box'.Any = fn_helper;
_'box'.Default = fn_helper;
