-- generated by mise.py; do not edit

--$Name:Вильгельм Телль$
require "fmt"
require "parser/mp-ru"

local function fn_score_up()
  mp.score = mp.score + 1
end

local function fn_BowOrArrow(o)
  if not o or o == _'bow' or o.arrow then
    return true
  end
  p("Это не похоже на оружие, не правда ли?^")
  return false
end

obj {
  nam = "none";
}

Door = Class({
  from = 'none';
  to = 'none';
  door_to = function(s)
    if here() == _(s.from) then
      return _(s.to)
    end
    if here() == _(s.to) then
      return _(s.from)
    end
    return false
  end;
}, door):attr 'open'

Path = Class {
  walk_to = 'none';
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(_(s.walk_to)) then
      return
    end
    walk(_(s.walk_to))
  end;
  before_Default = function(s, ev, w, wh)
    local d = (s.desc)
    if d then
      p(d)
      return
    end
    p('Ты можешь пойти в ', _(s.walk_to):noun_hint("вн"), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

mp.undo = 5
mp.score = 0
mp.detailed_inv = true
instead.notitle = false

const 'MAX_SCORE' (3)

_'game'.hint_verbs = { "#Exam", "#Walk", "#Take", "#Drop", "#FireAt", "#Salute", "#Talk" }

Prop = Class {
  before_Exam = function() return false end;
  before_Default = function(s, ev, w, wh)
    p('Вам нет нужды беспокоиться о ', s:noun_hint(({ "пр" })), '.')
  end;
}:attr 'scenery'

Furniture = Class {
  ["before_Take,Pull,Push,PushDir"] = "Слишком тяжело.";
}:attr 'static,supporter'

Arrow = Class {
  -"стрела,стрел*";
  arrow = true;
  description = "Все твои стрелы верны и остры.";
  ["before_Drop,Give,ThrowAt"] = "Ты не хочешь расставаться со своими острыми стрелами.";
}

NPC = Class {
  ["life_Answer,Ask,AskTo,AskFor,Tell"] = function(s)
    p('Введите просто "говорить с ', s:noun_hint(({ 'тв' })), '".')
  end;
}:attr 'animate'

game.dsc = [[^Пример простой игры на Inform
^Авторы: Роджер Фирт (Roger Firth) и Соня Кессерих (Sonja Kesserich).
^Перевод Александра Мосьпана a.k.a. Ugo^
^Перенос на МЕТАПАРСЕР 3 выполнил Пётр Косых^^
Место: Альтдорф, кантон Ури, Швейцария. Год 1307. Швейцария под командованием Императора Альбрехта Габсбурга.
Его наместник -- фогт -- жестокий Герман Гесслер, повесил свою шляпу на вершине столба, установленного посередине
городской площади. Каждый проходящий мимо должен был кланяться этому ненавистному символу Императорского могущества.
^^
Ты, вместе с сыном, спустился от своего домика, расположенного высоко в горах, чтобы купить провизии. Ты -- гордый и
независимый мужчина, охотник и проводник, известный мастерством владения луком, и неумением скрывать своё презрение
к фогту, что, конечно, неумно, учитывая, сколько вокруг его солдат.
^^
Сегодня базарный день -- город забит людьми с окрестных деревень и селений.^]]
pl.description = "Ты одет в традиционную одежду швейцарского горца."
function init()
  move(me(), _'street')
  move(_'bow', me())
  move(_'quiver', me())
  _'quiver':attr("worn")
end

room {
  -"улица";
  nam = "street";
  title = "Улица Альтдорфа";
  n_to = 'below_square';
  s_to = function(s)
    p("Поток народа, движущийся на север, к площади, не даёт тебе пройти.")
  end;
  obj = {
    Prop {
      -"ворота";
      nam = "ворота";
      description = "Огромные деревянные ворота в городской стене. Они широко распахнуты.";
    };
  };
}

Prop {
  -"прилавки|прилавок";
  nam = "прилавки";
  description = "Еда, инструменты, одежда -- обычное барахло.";
  found_in = { 'street', 'below_square' };
}

Prop {
  -"товары|товар|еда|одежда|инструмент|барахло";
  nam = "товары";
  description = "Ничто не приковывает твой взгляд.";
  found_in = { 'street', 'below_square' };
}

Prop {
  -"торговцы,купцы,продавцы,лавочники";
  nam = "торговцы";
  description = [[Несколько жуликоватых, но довольно прилично выглядящих торговцев, откровенно преувеличивая,
расхваливают свой товар.]];
  found_in = { 'street', 'below_square' };
}:attr 'animate'

Prop {
  -"жители|люди|народ|толпа";
  nam = "жители";
  description = "Горный народ, такой же, как и ты.";
  found_in = function(s)
    return true
  end;
}

room {
  -"улица";
  nam = "below_square";
  title = "Улица";
  dsc = [[Народ проталкивается от южных ворот к городской площади, располагающейся немного севернее.
Ты узнаёшь торговку за прилавком фруктово-овощной лавки.]];
  n_to = 'south_square';
  s_to = 'street';
}

Furniture {
  -"овощная лавка|лавка|прилавок,стол";
  nam = "stall";
  found_in = 'below_square';
  description = "Это всего лишь маленький стол с большой кучей картошки, кучкой морковки и репы, и парой яблок.";
  before_Search = function(s, w, wh)
    mp:xaction('Exam', s)
  end;
}:attr 'scenery'

Prop {
  -"картошка|картофель";
  nam = "картошка";
  found_in = 'below_square';
  description = "Должно быть, какой-то особенно ранний сорт... лет так на триста!";
}

Prop {
  -"фрукты/~од|овощи|морковь,морковка|репа,репка";
  nam = "фрукты";
  found_in = 'below_square';
  description = "Отличные местные овощи.";
}

NPC {
  -"Хельга|торговка,продавщица,женщина|платье|шарф";
  nam = "stallholder";
  found_in = 'below_square';
  description = "Хельга -- полноватая жизнерадостная женщина, одетая в бесформенное платье и пёстрый платок.";
  times_spoken_to = 0;
  life_Kiss = '"Ох, а ты дерзкий тип!"';
}

room {
  nam = "south_square";
  title = "Южный край площади";
  dsc = [[Узкая улица выходит на южный край городской площади, продолжаясь на дальней её стороне.
Чтобы продолжить путь к месту назначения -- сыромятне Йохансона -- ты должен пройти на север, через площадь,
в центре которой ты видишь отвратительный столб со шляпой Гесслера на верхушке. Если ты пойдёшь прямо,
придётся пройти мимо него. Солдаты императора грубо толкаются среди толпы, раздавая тумаки и громко ругаясь.]];
  n_to = 'mid_square';
  s_to = 'below_square';
}

Prop {
  -"шляпа,шапка|шест,столб";
  nam = "шляпа";
  ["before_Default,Exam"] = "Издали плохо видно.";
  found_in = { 'south_square', 'north_square' };
}

NPC {
  -"солдаты,стражники";
  nam = "guard";
  description = "Неотёсанные, жестокие люди не из этих мест.";
  ["before_FireAt,Attack"] = "Их намного больше.";
  before_Talk = "Разговаривать с этими мерзавцами -- ниже твоего достоинства.";
  found_in = { 'south_square', 'mid_square', 'north_square', 'marketplace' };
}:attr 'animate,scenery'

room {
  -"центр|площадь";
  nam = "mid_square";
  title = "Центр площади";
  dsc = [[В центре площади давка совсем не такая сильная. Большинство людей предпочитают держаться подальше от столба,
на который нахлобучена эта нелепая церемониальная шапка. Группа солдат стоит неподалёку, осматривая всех, кто проходит.]];
  n_to = 'north_square';
  s_to = 'south_square';
  warnings_count = 0;
}

Furniture {
  -"шляпа|столб|перо|шапка";
  nam = "pole";
  description = [[Столб из соснового ствола диаметром в несколько дюймов и высотой в девять или десять футов.
На самой верхушке надёжно закреплена нелепая шляпа Гесслера из черной и красной кожи, с широкими
изогнутыми полями и пучком перьев из мёртвого гуся.]];
  has_been_saluted = false;
  before_FireAt = { "Заманчиво", "но ты не хочешь неприятностей." };
  before_Salute = function(s, w, wh)
    s.has_been_saluted = true
    p([[Ты отдаёшь честь шляпе на столбе.^^
"Благодарю вас, сэр", -- ухмыляется солдат.]])
  end;
  found_in = 'mid_square';
}:attr 'scenery'

room {
  nam = "north_square";
  title = "Северный край площади";
  dsc = "Узкая улочка ведёт на север от мощёной площади, в центре которой едва виднеется столб и шапка.";
  n_to = function(s)
    p("Вместе с Уолтером ты уходишь с площади, направляясь к сыромятне Йохансона.")
    walk(_'theend')
  end;
  s_to = function(s)
    p("Ты не можешь себя заставить снова пройти через это.")
  end;
}

room {
  nam = "marketplace";
  title = "Рыночная площадь";
  dsc = [[Рыночная площадь Альтдорфа примыкает к центральной площади. Она была поспешно очищена от прилавков.
Группа солдат расталкивает людей, чтобы очистить место перед липой, которая растет тут с незапамятных
времён. Обычно в её тени собираются старики, чтобы посплетничать, поглазеть на девушек и поиграть в карты.
Но сегодня под ней никого нет, кроме Уолтера, которого привязали к стволу. Двое солдат удерживают тебя примерно
в сорока метрах от него.]];
  cant_go = "Что? Оставить своего сына связанным здесь?";
}

obj {
  -"липа|дерево";
  nam = "tree";
  found_in = 'marketplace';
  description = "Обычное большое дерево.";
}:attr 'scenery'

NPC {
  -"герцог|Гесслер,фогт,Герман";
  nam = "governor";
  found_in = 'marketplace';
  description = "Невысокий, коренастый, с противным лицом, Гесслер наслаждается властью, которую он имеет над этим городком.";
  before_Attack = "Как ты думаешь это сделать?";
  life_Talk = "Ты не можешь заставить себя заговорить с ним.";
}:dict { ["Гесслер/вн"] = "Геслера", ["Гесслер/рд"] = "Геслера", ["Гесслер/дт"] = "Гесслеру", ["Гесслер/тв"] = "Гесслером", ["Гесслер/пр"] = "Геслере" }

obj {
  -"лук";
  nam = "bow";
  description = "Твой верный лук из тиса, с натянутой льняной тетивой.";
  ["before_Drop,Give,ThrowAt"] = "Ты никогда не расстаёшься со своим верным луком.";
}:attr 'clothing'

obj {
  -"колчан";
  nam = "quiver";
  description = "Он сделан из козьей кожи и обычно висит за твоим левым плечом. В колчане есть стрелы.";
  ["before_Drop,Give,ThrowAt"] = "Но это ведь подарок твоей жены Хедвиг.";
}:attr 'container,open,clothing'

Arrow {
  found_in = 'quiver';
}

Arrow {
  found_in = 'quiver';
}

Arrow {
  found_in = 'quiver';
}

NPC {
  -"сын,мальчик,мальчишка,парень|Уолтер";
  nam = "son";
  ["before_Exam,Listen,Salute,Talk"] = function() return false end;
  found_in = function(s)
    return true
  end;
}:attr 'transparent,scenery'

obj {
  -"яблоко,яблочко";
  nam = "apple";
  before_Drop = { "Вполне съедобное яблоко", "не стоит его выбрасывать." };
  before_Eat = "Хельга дала его для Уолтера...";
}

mp.FireAt = function(s, w, wh)
  if not w then
    p("Ты не хочешь просто стрелять куда зря.")
    return
  end
  if fn_BowOrArrow(wh) then
    p("Немыслимо!")
  end
  return false
end

Verb { '#FireAt', "стреля/ть,стрельн/уть,целить/ся,застрели/ть,выстрел/ить", "в {noun}/вн,scene : FireAt", "~ {noun}/вн,scene : FireAt", "~ ?в {noun}/вн,scene из {noun}/рд,held : FireAt", "~ из {noun}/рд,held в {noun}/вн,scene : FireAt reverse", "~ {noun}/тв,held в {noun}/вн,scene : FireAt reverse" }

mp.Salute = function(s, w, wh)
  if w:has("animate") then
    if w:hint('мн') then
      p(w:Noun_hint(), ' приветствуют тебя.')
    else
      p(w:Noun_hint(), ' приветствует тебя.')
    end
  else
    if w:hint('мн') then
      p(w:Noun_hint(), ' не замечают этого.')
    else
      p(w:Noun_hint(), ' не замечает этого.')
    end
  end
end

Verb { '#Salute', "поклони/ться,честь", "{noun}/дт,scene : Salute" }

Verb { '#Salute2', "мах/ать,помах/ать,помаш/и,маш/и", "{noun}/дт,scene : Salute" }

mp.Untie = function(s, w, wh)
  p("Ты не можешь развязать это.")
end

Verb { '#Untie', "развяз/ать,отвяз/ать,освобод/ить", "{noun}/вн,scene : Untie" }

_'street'.dsc = function(s)
  pn([[Узкая улочка тянется на север, к городской площади. Местные жители стекаются в город через ворота на юге.
Они выкрикивают приветствия, предлагают товары, обмениваются новостями, с наигранным недоверием торгуются с
лавочниками, чьи прилавки сильно затрудняют движение.]])
  if s:once() then
    pn('^"Держись поближе ко мне, сынок, -- говоришь ты. -- Иначе потеряешься в этой толпе".')
  end
end

_'stallholder'.init_dsc = function(s)
  pn("Хельга отвлекается от сортировки картошки, чтобы уделить тебе внимание.")
  if s:once() then
    move(_'apple', me())
    pn([[^"Привет, Вильгельм! Отличный денёк для торговли! Это твой Уолтер? О, как он вырос! Держи яблоко для него --
тут один край немного подгнил, но всё остальное хорошее. Как там фрау Телль? Передавай ей привет".]])
  end
end
_'stallholder'.life_Talk = function(s)
  s.times_spoken_to = s.times_spoken_to + (1)
  if s.times_spoken_to == 1 then
    fn_score_up()
    p("Ты тепло благодаришь Хельгу за яблоко.")
  elseif s.times_spoken_to == 2 then
    p("Ещё увидимся!")
  else
    return false
  end
end

_'mid_square'.before_Walk = function(s, w, wh)
  if (mp:compass_dir(w) or nil) == "s_to" then
    s.warnings_count = 0
    _'pole'.has_been_saluted = false
  end
  if (mp:compass_dir(w) or nil) == "n_to" then
    if _'pole'.has_been_saluted then
      p([[^"Хорошего дня".^]])
      return false
    end
    s.warnings_count = s.warnings_count + (1)
    if s.warnings_count == 1 then
      p([[Солдат преграждает тебе дорогу.^^
"Эй ты, сноб, забыл хорошие манеры? Как насчёт того, чтобы поклониться шляпе фогта?"]])
    elseif s.warnings_count == 2 then
      p([["Я тебя знаю, ты Телль, мятежник, не правда ли?
Ладно, мы не хотим начинать тут драку, так что будь хорошим мальчиком,
отдай честь этой чёртовой шляпе, в третий раз я просить не буду".]])
    else
      p([["Ладно, {$fmt u|господин} Телль, у вас серьёзные неприятности.
Я вежливо попросил, но вы оказались слишком гордым
и слишком глупым. Думаю, фогт захочет с вами немного побеседовать".^^
С этими словами солдаты хватают тебя и Уолтера, и пока сержант бежит докладывать Гесслеру,
они грубо тащат вас к старому липовому дереву, растущему на рыночной площади.^]])
      move(_'apple', _'son')
      move(me(), _'marketplace')
    end
    return
  end
  return false
end;

_'tree'.before_FireAt = function(s, w, wh)
  if fn_BowOrArrow(w) then
    p("Твоя рука слегка дрожит, и стрела входит в ствол на несколько дюймов выше головы Уолтера.")
    walk(_'theend')
  end
end;

_'governor'.init_dsc = function(s)
  pn("Гесслер с глумливым лицом наблюдает за происходящим с безопасного расстояния.")
  if s:once() then
    pn([[^"Похоже, нужно преподать тебе урок, глупец. Никто не смеет проходить через площадь, не отдав дань
уважения Его Императорскому Высочеству Альберту. Никто, ты слышишь? Я мог бы лишить тебя головы за измену,
но проявлю снисхождение. Не жди моей милости, если снова проявишь подобную глупость, но в этот раз я отпущу
тебя... после того, как ты продемонстрируешь своё мастерство владения луком. Попади в это яблоко с того места,
где ты стоишь. Это не должно быть слишком сложным. Сержант, лови. Поставь его на голову этого мелкого ублюдка".]])
  end
end
_'governor'.before_FireAt = function(s, w, wh)
  if fn_BowOrArrow(w) then
    p([[Прежде, чем солдаты успевают среагировать, ты разворачиваешься, и выпускаешь стрелу в Гесслера.
Она пронзает его сердце, и герцог оседает на землю. На мгновение толпа замирает в недоумении, но тут же
разражается криками ликования.]])
    walk(_'theend')
  end
end;

_'son'.description = function(s)
  if here() == _'marketplace' then
    p([[Он смотрит на тебя, пытаясь выглядеть спокойным и смелым. Его руки связаны за спиной.
Яблоко лежит в его светлых волосах.]])
    return
  end
  p("Тихий светлый мальчик восьми лет, он быстро учится сельской работе.")
end
_'son'.life_Give = function(s, w, wh)
  fn_score_up()
  move(w, s)
  p('"Спасибо, пап".')
end;
_'son'.life_Talk = function(s)
  if here() == _'marketplace' then
    p('"Стой спокойно, сынок, Господь нам поможет".')
  else
    p("Ты показываешь сыну несколько интересных мест в городе.")
  end
end
_'son'.before_FireAt = function(s, w, wh)
  if here() == _'marketplace' then
    if fn_BowOrArrow(w) then
      p("Упс! Наверняка вы имели в виду не это?")
      walk(_'theend')
    end
    return
  end
  return false
end;
_'son'.before_Default = function(s, ev, w, wh)
  if here() == _'marketplace' then
    p("Солдаты не позволят тебе этого.")
    return
  end
  return false
end;

_'apple'.description = function(s)
  if here() == _'marketplace' then
    p("Отсюда ты едва видишь его.")
  else
    p("Яблоко зелёное, с коричневым пятном.")
  end
end
_'apple'.before_Default = function(s, ev, w, wh)
  if where(s) == _'son' then
    if here() == _'marketplace' then
      p("Отсюда ты едва видишь его.")
      return
    end
    p("Лучше оставить яблоко сыну.")
    return
  end
  return false
end;
_'apple'.before_FireAt = function(s, w, wh)
  if here() == _'marketplace' then
    if fn_BowOrArrow(w) then
      fn_score_up()
      p([[Мягко и спокойно ты кладёшь стрелу на тетиву, оттягивая её, и, предельно
сконцентрировавшись, берёшь прицел. Задержав дыхание, не мигая, ты в ужасе
отправляешь стрелу в цель. Она летит через площадь к твоему сыну, и, пронзая яблоко, впивается
в дерево. Толпа взрывается криками радости. Гесслер остаётся разочарованным.]])
      walk(_'happyend')
    end
    return
  end
  return false
end;

gameover {
  nam = "theend";
  title = "Конец";
  dsc = function(s)
    pn('Вы испортили любимую народную легенду.')
    p('Ваш счет: ', (mp.score), ' из ', MAX_SCORE)
  end;
}

gameover {
  nam = "happyend";
  title = "Конец";
  dsc = function(s)
    pn('Поздравляю, вы прошли игру!')
    p('Ваш счет: ', (mp.score), ' из ', MAX_SCORE)
  end;
}
