-- generated by mise.py; do not edit

--$Name:Серое Сердце$
--$Version:1.0$
--$Author:по мотивам новелл А. Грина и анимации П. Гримо$
--$Info:Романтическая фантасмагория о море, памяти и машине. Петроград, зима 1920 года.$
require "fmt"
fmt.dash = true
fmt.quotes = true
require "parser/mp-ru"

local function fn_event()
  return mp.event
end

local function fn_call_before(s, ev)
  s['before_' .. ev](s)
end

local function fn_arg_word(i)
  return mp.args[i] and mp.args[i].word or ''
end

local function fn_tiny()
  return instead.tiny
end

local function fn_type_name(s, w)
  if (w == _'имя' or w == _'машинка') and have(_'карточка') and not type_done then
    p("Вы отстучали: М-А-Р-И-Я. Литеры ударили по бумаге, и в тумбе стола отскочила крышка тайника.")
    type_done = true
  else
    return false
  end
end

Path = Class {
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(std.ref(s.walk_to)) then return end
    walk(s.walk_to)
  end;
  before_Default = function(s, ev, w)
    if s.desc then p(s.desc) return end
    p([[Ты можешь пойти в ]], std.ref(s.walk_to):noun('вн'), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

function start(load)
  move(me(), _'набережная')
end
function init()
end

global 'candle_lit' (false)
global 'matches_warm' (false)
global 'code_known' (false)
global 'clerk_saved' (false)
global 'guard_out' (false)
global 'lantern_lit' (false)
global 'corridor_shock' (false)
global 'phone_heard' (false)
global 'rats_cleared' (false)
global 'hall_unlocked' (false)
global 'arch_open' (false)
global 'poet_saved' (false)
global 'poet_lost' (false)
global 'bird_freed' (false)
global 'boss_banished' (false)
global 'doll_true' (false)
global 'corinna_awake' (false)
global 'type_done' (false)
global 'brand_spoken' (false)
global 'dep_open' (false)
global 'fake_tested' (false)
global 'medallion_shown' (false)
global 'tube_hit' (false)
global 'dnevnik' (false)

Verb { '#Type', "[|на]печат/ать,отстуч/ать", "{noun}/вн : Type" }

Verb { '#Rewrite', "[пере|на]писать,нанести,[вы|на]бить", "{noun}/вн : Rewrite" }

Verb { '#Play', "[|по]играть,сыгра/ть,исполни/ть", "на {noun}/пр,held : Play", "{noun}/вн,held : Play" }

room {
  -"набережная,мойка,улица";
  nam = "набережная";
  title = "Набережная Мойки";
  dsc = function(s)
    p("Петроград, глухая ночь января 1920 года. Мороз сорок градусов. Белый стылый сумрак над промёрзшей Мойкой. За чугунной оградой — гранитная громада бывшего Ссудного Банка, опутанная трубами. Над ней мерцает рубиновый глазок семафора. В ограде — приоткрытая калитка; за ней — высокое крыльцо с гранитным портиком. И странно: в мёртвом воздухе, в вое паропроводов, слышится глухой рокот прибоя. Здесь моря нет и быть не может. Но оно — есть. Три дня назад Сюзанна ушла сюда заложить материнский медальон и не вернулась.")
    if not have(_'спички') then
      p("На обледенелых ступенях подле пилона лежит фигура в рваном пальто. Пальцы мертвеца сжимают спичечный коробок.")
    end
  end;
  before_Listen = function(s, w, wh)
    p("Ветер воет в растяжках труб. Под мостовой глухо ухает поршень. А поверх — далёкий рокот, которого здесь не должно быть. Море.")
  end;
  before_Exam = function(s, w, wh)
    if w == _'труп' then
      p("Лицо — синяя маска. На искусанных губах — застывшая розовая пена. На шее — тёмный укус с медным отливом по краям.")
    else
      return false
    end
  end;
  obj = {
    obj {
      -"труп,мертвец|фигура|пальто";
      nam = "труп";
    }:attr 'scenery,scenery';

    obj {
      -"спички|коробок";
      nam = "спички";
      before_Take = function(s, w, wh)
        p("Вы разжали закоченевшие пальцы. Коробок заиндевел.")
        return false
      end;
    };

    Path {
      -"крыльцо|портик|ступени|калитка";
      nam = "путь_набережная_крыльцо";
      walk_to = 'крыльцо';
    };

    obj {
      -"прочь|уйти";
      nam = "прочь";
      before_Walk = function(s, w, wh)
        walk(_'badend')
      end;
      before_Enter = function(s, w, wh)
        walk(_'badend')
      end;
    }:attr 'scenery,scenery';
  };
}

room {
  -"крыльцо|портал,портик";
  nam = "крыльцо";
  title = "Портал Банка";
  dsc = function(s)
    p("Высокий гранитный портик. Массивные дубовые двери с бронзовыми львами приоткрыты. В пастях львов — латунные переговорные раструбы. Из щели тянет тёплым. В сорокаградусный мороз это странно. За спиной остаётся калитка на набережную.")
  end;
  before_Exam = function(s, w, wh)
    if w == _'двери' then
      p("Створка подпёрта изнутри картонной пластиной с просечками. Кто-то вошёл и не вернулся.")
    elseif w == _'раструб' then
      p("Из медных глоток — треск реле и сухое покашливание дежурного.")
    else
      return false
    end
  end;
  before_Talk = function(s, w, wh)
    if w == _'раструб' then
      p('"Вход по нарядам канцелярии утилизации. Ожидайте вызова." И — тише, будто из-под воды: "...помогите..."')
    else
      return false
    end
  end;
  obj = {
    obj {
      -"двери|дверь|львы";
      nam = "двери";
    }:attr 'scenery,scenery';

    obj {
      -"раструбы|раструб|глотки";
      nam = "раструб";
    }:attr 'scenery,scenery';

    obj {
      -"набережная,калитка";
      nam = "путь_крыльцо_набережная";
      ["before_Walk,Enter"] = function(s, w, wh)
        move(me(), _'набережная')
      end;
    }:attr 'scenery,scenery';

    Path {
      -"вестибюль|внутрь|вход";
      nam = "путь_крыльцо_вестибюль";
      walk_to = 'вестибюль';
    };
  };
}

room {
  -"вестибюль,зал,холл";
  nam = "вестибюль";
  title = "Парадный вестибюль";
  dsc = function(s)
    p("Зал-колодец из белого мрамора, тронутый сажей. Потолок теряется в темноте, где в латунных трубах с шипением пролетают гильзы пневмопочты. Вдоль стен поднимаются чугунные шахты лифтов со шкалами до минус сорокового горизонта. В центре — остывшая буржуйка. На стене — высокие часы с маятником-гильотиной. За конторкой — чиновник в суконном вицмундире. Слева — тёмный проём гардеробной. Справа — низкая дверь караулки. За барьером, у стены, — буфетная. А в глубине, за шахтами лифтов, наверх ведёт широкая лестница — в галерею второго яруса.")
    if not candle_lit and not have(_'свеча') then
      p("На краю полированного барьера — толстая стеариновая свеча.")
    end
    if not candle_lit and have(_'свеча') then
      p("Свеча у вас в руке. Белый толстый фитиль холоден.")
    end
    if candle_lit then
      p("Огонёк выхватывает из мрака круг пола в два шага. Дальше — свинцовый полумрак, где за шахтами лифтов шевелятся тени.")
    end
  end;
  before_Listen = function(s, w, wh)
    p("Ваш сапог скрипнул по крошке — и в вышине галереи щёлкнул соленоид. Распределитель пневмопочты перевёл стрелку, отмечая вас.")
  end;
  before_Exam = function(s, w, wh)
    if w == _'часы' then
      p("Стрелки замерли на 4:12. Внутри — лихорадочный бег храповика: пружина взведена до предела. Маятник-гильотина блестит, как лезвие.")
      code_known = true
    elseif w == _'пневмопочта' then
      p("Латунные трубы втягивают воздух и со стуком выплёвывают гильзы с сургучной печатью. Каждая — чей-то приговор.")
    else
      return false
    end
  end;
  before_Talk = function(s, w, wh)
    if w == _'клерк' then
      if not clerk_saved then
        p('Глаза чиновника отливают ртутной мутью. Он перфорирует ленту ручным компостером: "Приём прекращён. Души отписаны в амортизационный фонд Его Величества Механизма."')
      else
        p('Он утыкается лбом в конторку: "Смотрите под ноги в галереях. Там провальные люки для недовольных."')
      end
    else
      return false
    end
  end;
  before_Show = function(s, w, wh)
    if w == _'карточка' and have(_'карточка') then
      if not clerk_saved then
        p('Компостер падает. Глаза расширяются. "Маша Бранд... Ордер на разборку за моим личным номером! Я подписал его за осьмушку чая и облатку сахарина. Возьмите ключ. Он отпирает парадный зал на втором этаже. Спасите тех, кого ещё не пустили на шестерни!"')
        clerk_saved = true
        enable(_'ключ_клерка')
        take(_'ключ_клерка')
      else
        p("Клерк уже видел карточку. Он лишь беззвучно вздрагивает, глядя в стол.")
      end
    else
      return false
    end
  end;
  obj = {
    obj {
      -"свеча|стеарин";
      nam = "свеча";
      before_Burn = function(s, w, wh)
        if matches_warm and not candle_lit then
          p("Спичка чиркнула жарко и сухо. Жёлтый огонёк встал над фитилём, оттеснив холодную тьму.")
          candle_lit = true
        elseif have(_'спички') and not matches_warm and not candle_lit then
          p("Серная головка обледенела и крошится. Спички нужно отогреть у тепла.")
        end
      end;
      before_Take = function(s, w, wh)
        p("Вы взяли свечу. В городе, где жгут книги ради тепла, фунт стеарина — залог выживания.")
        return false
      end;
    };

    obj {
      -"часы|маятник|гильотина";
      nam = "часы";
    }:attr 'scenery,scenery';

    obj {
      -"пневмопочта|трубы,гильзы";
      nam = "пневмопочта";
    }:attr 'scenery,scenery';

    obj {
      -"клерк,чиновник,дежурный";
      nam = "клерк";
    }:attr 'animate';

    obj {
      -"крыльцо";
      nam = "путь_вестибюль_крыльцо";
      ["before_Walk,Enter"] = function(s, w, wh)
        move(me(), _'крыльцо')
      end;
    }:attr 'scenery,scenery';

    Path {
      -"гардероб,гардеробная,проём";
      nam = "путь_вестибюль_гардероб";
      walk_to = 'гардероб';
    };

    Path {
      -"охрана,караулка,дверь";
      nam = "путь_вестибюль_охрана";
      walk_to = 'охрана';
    };

    Path {
      -"буфет|буфетная|барьер";
      nam = "путь_вестибюль_буфет";
      walk_to = 'буфет';
    };

    obj {
      -"коридор|лестница,галерея|наверх";
      nam = "путь_вестибюль_коридор";
      ["before_Walk,Enter"] = function(s, w, wh)
        if not candle_lit then
          p("Лестница обрывается в темноту. Шагнуть без огня — сорваться в провал.")
          return
        end
        move(me(), _'коридор')
      end;
    }:attr 'scenery,scenery,enterable';
  };
}

room {
  -"гардероб,гардеробная";
  nam = "гардероб";
  title = "Парадный гардероб";
  dsc = function(s)
    p("Ряды чугунных крючьев уходят в ледяную полутьму. Механические вешалки со скрипом перебирают пустоту. С лепного карниза свисают иглы сосулек, под ногами хрустит чёрная наледь. Позади — дверь в вестибюль.")
    if not have(_'осколок') then
      p("В лёд под разбитым трюмо вмёрз крупный осколок зеркала в серебряном ободе.")
    end
  end;
  before_Exam = function(s, w, wh)
    if w == _'вешалки' then
      p("Механические плечики перебирают пустоту. Лишь на одной стойке в глубине сиротливо качается забытая офицерская шинель.")
    elseif w == _'пальто' then
      p("Шинель изъедена снизу мелкими зубами. В кармане — горсть сухих зёрен овса и обрывок морской карты: бухта, мыс, название города — Зурбаган.")
    else
      return false
    end
  end;
  before_Listen = function(s, w, wh)
    p("Сухой скрип промёрзшего камня. За панелями — тиканье десятков таймеров.")
  end;
  obj = {
    obj {
      -"осколок|зеркало,стекло";
      nam = "осколок";
      before_Take = function(s, w, wh)
        p("Вы откололи тяжёлое стекло. В его амальгаме свет кажется обнажающим, сдирая с вещей искусственный лоск.")
        return false
      end;
    };

    obj {
      -"вешалки|плечики|крючья";
      nam = "вешалки";
    }:attr 'scenery,scenery';

    obj {
      -"пальто|шинель|карман";
      nam = "пальто";
    }:attr 'scenery,scenery';

    obj {
      -"вестибюль";
      nam = "путь_гардероб_вестибюль";
      before_Walk = function(s, w, wh)
        move(me(), _'вестибюль')
      end;
      before_Enter = function(s, w, wh)
        move(me(), _'вестибюль')
      end;
    }:attr 'scenery,scenery';
  };
}

room {
  -"буфет|буфетная";
  nam = "буфет";
  title = "Офицерский буфет";
  dsc = function(s)
    p("Разграбленные буфеты орехового дерева. На цинковой стойке — пустые коробки монпансье «Жорж Борман». У дальней стены гудит стальной калорифер с манометром. Под перевёрнутой чашкой прижат обрывок перфокарты. Позади — дверь в вестибюль.")
  end;
  before_Exam = function(s, w, wh)
    if w == _'записка' then
      p("Торопливый почерк Сюзанны: «Они заперли меня на третьем подземном горизонте. Их предводитель носит золотую заводную корону. Я спрятала мамин медальон в прачечной. Если найдёшь — помни обо мне. Не верь их соловьям...»")
    elseif w == _'калорифер' then
      p("Манометр подрагивает. Стальные рёбра вибрируют от пара из нижних котлов.")
    elseif w == _'стойка' then
      p("Среди черепков — жестянка с сушёными морковными очистками. Суррогат чая голодного года.")
    else
      return false
    end
  end;
  before_PutOn = function(s, w, wh)
    if w == _'спички' and wh == _'калорифер' and not matches_warm then
      p("Вы разложили коробок на горячих трубах калорифера. Лёд сошёл, серные головки оттаяли.")
      remove(_'спички')
      matches_warm = true
    else
      return false
    end
  end;
  obj = {
    obj {
      -"записка,перфокарта,чашка";
      nam = "записка";
    }:attr 'scenery,scenery';

    obj {
      -"калорифер,манометр|трубы";
      nam = "калорифер";
    }:attr 'scenery,scenery';

    obj {
      -"стойка|буфеты|коробки";
      nam = "стойка";
    }:attr 'scenery,scenery';

    obj {
      -"вестибюль";
      nam = "путь_буфет_вестибюль";
      before_Walk = function(s, w, wh)
        move(me(), _'вестибюль')
      end;
      before_Enter = function(s, w, wh)
        move(me(), _'вестибюль')
      end;
    }:attr 'scenery,scenery';
  };
}

room {
  -"охрана,караулка|пост";
  nam = "охрана";
  title = "Дежурный пост";
  dsc = function(s)
    p("Караулка с низким сводом. На стене вздрагивают латунные клапаны коммутатора. В полу — люк с решёткой, откуда тянет маслом, гарью и зерновой пылью. В железном шкафу, за спиной караульного, видна ветрозащитная лампа «Летучая мышь» в проволочном каркасе. За спиной — дверь в вестибюль.")
    if not guard_out then
      p("На табурете — караульный в форменной шинели. На голове — медный шлем с решётчатым забралом. Челюсти непрерывно жуют табак.")
    end
    if guard_out and not have(_'лампа') then
      p("Железный шкаф распахнут. Лампа исчезла.")
    end
    if guard_out and have(_'лампа') and not lantern_lit then
      p("Лампа в руке. За толстым стеклом плещется керосин.")
    end
    if guard_out and lantern_lit then
      p("Лампа горит ровным, устойчивым жёлтым пламенем, защищённым от сквозняков.")
    end
  end;
  before_Talk = function(s, w, wh)
    if w == _'сторож' and not guard_out then
      p('Из-под шлема — глухой хрип: "Наряд аннулирован. Вы приписаны к механическому переплаву. Ждите сигнала."')
    else
      return false
    end
  end;
  before_Exam = function(s, w, wh)
    if w == _'сторож' and not guard_out then
      p("Из-под суконного рукава виднеются серые суставчатые пальцы с плоскими когтями.")
    else
      return false
    end
  end;
  before_Show = function(s, w, wh)
    if w == _'осколок' and have(_'осколок') and not guard_out then
      p("В зеркале отразилась крысиная морда, впаянная в шестерни шлема. Тварь зашлась визгом, бросила винтовку и скользнула в люк пневмосброса.")
      guard_out = true
    else
      return false
    end
  end;
  obj = {
    obj {
      -"сторож,караульный,охранник";
      nam = "сторож";
    }:attr 'animate';

    obj {
      -"лампа|фонарь,летучая мышь";
      nam = "лампа";
      before_Burn = function(s, w, wh)
        if candle_lit and not lantern_lit then
          p("Вы поднесли свечу к фитилю. Керосин занялся ровным ярким пламенем.")
          lantern_lit = true
        elseif not candle_lit and not lantern_lit then
          p("Не от чего зажечь фитиль. Сначала нужен открытый огонь.")
        end
      end;
      before_Take = function(s, w, wh)
        if not guard_out then
          p('Сторож заслоняет шкаф, скаля резцы: "Руки прочь от казённого добра!"')
          return
        end
        p("Вы сняли с крюка фонарь. Проволочная корзина защитит стекло, а пламя — от тяги.")
        return false
      end;
    };

    obj {
      -"вестибюль";
      nam = "путь_охрана_вестибюль";
      ["before_Walk,Enter"] = function(s, w, wh)
        move(me(), _'вестибюль')
      end;
    }:attr 'scenery,scenery';

    obj {
      -"подвал,люк|решётка";
      nam = "путь_охрана_подвал";
      ["before_Walk,Enter"] = function(s, w, wh)
        if not lantern_lit then
          p("Ледяная тяга из шахты собьёт пламя свечи. Без закрытого фонаря — гибель.")
          return
        end
        move(me(), _'подвал')
      end;
    }:attr 'scenery,scenery,enterable';
  };
}

room {
  -"коридор|галерея,анфилада";
  nam = "коридор";
  title = "Анфилада присутствий";
  dsc = function(s)
    p("Парадная галерея второго яруса. Ковёр глушит шаги. Вдоль стен — ниши со статуями слепых богинь, держащих раструбы акустической проводки. На стене — чёрный аппарат «Эриксон» с двумя медными чашами звонков. Анфилада тянется мимо дверей: библиотека, архив, кабинет, будуар, бухгалтерия. В самом конце — высокие створки парадного зала. Позади, за поворотом, — лестница вниз, в вестибюль.")
    if not corridor_shock then
      p("Зловещая, гулкая тишина. Слышно лишь, как в висках молотом бьёт кровь.")
    end
    if corridor_shock and not phone_heard and not rats_cleared then
      p("Оглушительный звон! Медные чаши взрываются набатом над головой.")
    end
    if phone_heard and not rats_cleared then
      p("Трубка сорвана с медного рычага и качается на бронированном шнуре.")
    end
    if rats_cleared then
      p("Телефон разворочен: обезумевшая стая вырвала его из стены.")
    end
  end;
  before_Look = function(s, w, wh)
    if not corridor_shock then
      p("Вы вглядываетесь в своды — и тишину разрывает телефонный набат!")
      corridor_shock = true
      return
    end
    p("Холодный мрамор, позолота, тишина.")
  end;
  before_Listen = function(s, w, wh)
    if not corridor_shock then
      p("Вы замерли у раструба — и прямо в ухо ударил яростный звонок!")
      corridor_shock = true
      return
    end
    p("Только шорох ковра да далёкий гул в шахтах.")
  end;
  before_Exam = function(s, w, wh)
    if w == _'статуи' then
      if not corridor_shock then
        p("Вы шагнули к нише, но телефон взорвался трезвоном над головой!")
        corridor_shock = true
        return
      end
      p("Слепые богини с пустыми глазницами держат раструбы, вслушиваясь в каждый шорох.")
    else
      return false
    end
  end;
  before_Open = function(s, w, wh)
    if w == _'путь_коридор_зал' then
      if not corridor_shock then
        p("Вы потянулись к замку, но медный звон оборвал сердце!")
        corridor_shock = true
        return
      end
      if have(_'ключ_клерка') and not hall_unlocked then
        p("Ключ провернулся. Створки зала ушли в пазы.")
        hall_unlocked = true
      elseif not have(_'ключ_клерка') and not hall_unlocked then
        p("Замок с фигурным пазом. Нужен специальный ключ.")
      end
    else
      return false
    end
  end;
  before_Play = function(s, w, wh)
    if w == _'флейта' then
      if not corridor_shock then
        p("Вы подняли инструмент, но треск звонков сорвал дыхание!")
        corridor_shock = true
        return
      end
      if have(_'флейта') and not hall_unlocked then
        p("Створки заперты броневыми жалюзи. Звук разобьётся о сталь.")
      elseif have(_'флейта') and hall_unlocked and not rats_cleared then
        p("Вы поднесли флейту к губам и извлекли пронзительную ноту. В зале — вой. Механические люки распахнулись, и сотни серых теней с визгом посыпались через пробитые витражи наружу, в метель.")
        rats_cleared = true
      end
    else
      return false
    end
  end;
  obj = {
    obj {
      -"трубка|телефон,аппарат,рычаг";
      nam = "трубка";
      before_Take = function(s, w, wh)
        if not corridor_shock then
          p('Вы сорвали трубку, заглушая звон. В мембране — механический голос: "Канцелярия брака. Код списания партии кукол — 709. Повторяю: семьсот девять. Сбросить в изолятор." И — тише, будто из-под воды: "...помогите..."')
          corridor_shock = true
          phone_heard = true
          code_known = true
          return
        end
        if not phone_heard and not rats_cleared then
          p('Вы прижали трубку. Механический голос: "Канцелярия брака. Код списания партии кукол — 709." И тише: "...помогите..."')
          phone_heard = true
          code_known = true
        end
      end;
    }:attr 'scenery,scenery';

    obj {
      -"статуи,богини,ниши";
      nam = "статуи";
    }:attr 'scenery,scenery';

    obj {
      -"вестибюль|лестница";
      nam = "путь_коридор_вестибюль";
      ["before_Walk,Enter"] = function(s, w, wh)
        if not corridor_shock then
          p("Вы попятились, но телефон взорвался звоном!")
          corridor_shock = true
          return
        end
        move(me(), _'вестибюль')
      end;
    }:attr 'scenery,scenery,enterable';

    obj {
      -"библиотека";
      nam = "путь_коридор_библиотека";
      ["before_Walk,Enter"] = function(s, w, wh)
        if not corridor_shock then
          p("Вы шагнули к дверям, но раскатистый трезвон отшатнул вас!")
          corridor_shock = true
          return
        end
        move(me(), _'библиотека')
      end;
    }:attr 'scenery,scenery,enterable';

    obj {
      -"архив";
      nam = "путь_коридор_архив";
      ["before_Walk,Enter"] = function(s, w, wh)
        if not corridor_shock then
          p("В тишине разорвался набат, эхом ударив по камню!")
          corridor_shock = true
          return
        end
        move(me(), _'архив')
      end;
    }:attr 'scenery,scenery,enterable';

    obj {
      -"кабинет";
      nam = "путь_коридор_кабинет";
      ["before_Walk,Enter"] = function(s, w, wh)
        if not corridor_shock then
          p("Вы взялись за ручку, но визг аппарата за спиной замер!")
          corridor_shock = true
          return
        end
        move(me(), _'кабинет')
      end;
    }:attr 'scenery,scenery,enterable';

    obj {
      -"будуар";
      nam = "путь_коридор_будуар";
      ["before_Walk,Enter"] = function(s, w, wh)
        if not corridor_shock then
          p("Звон хлестнул по ушам, сбив шаг!")
          corridor_shock = true
          return
        end
        move(me(), _'будуар')
      end;
    }:attr 'scenery,scenery,enterable';

    obj {
      -"бухгалтерия|расчётная";
      nam = "путь_коридор_бухгалтерия";
      ["before_Walk,Enter"] = function(s, w, wh)
        if not corridor_shock then
          p("Треск медных чаш сотряс галерею!")
          corridor_shock = true
          return
        end
        move(me(), _'бухгалтерия')
      end;
    }:attr 'scenery,scenery,enterable';

    obj {
      -"зал|створки|заседания";
      nam = "путь_коридор_зал";
      ["before_Walk,Enter"] = function(s, w, wh)
        if not corridor_shock then
          p("Звон сорвал тишину в клочья!")
          corridor_shock = true
          return
        end
        if not rats_cleared then
          p("За дверями — чавкающий пир. Войти — гибель.")
          return
        end
        move(me(), _'зал')
      end;
    }:attr 'scenery,scenery,enterable';
  };
}

room {
  -"библиотека";
  nam = "библиотека";
  title = "Библиотека Правления";
  dsc = function(s)
    p("Высокий зал с винтовыми чугунными лестницами. По рельсам вдоль полок скользят стремянки с захватами. На пюпитре — прикованный цепью фолиант чертежей. Пахнет пылью и кожей переплётов. Позади — дверь в галерею.")
    if not dnevnik then
      p("Между листами со схемами пневмоприводов зажат черновик записки с пятнами сажи.")
    end
  end;
  before_Exam = function(s, w, wh)
    if w == _'дневник' and not dnevnik then
      p("«Они именуют себя Избавителями от страданий. Их логика проста: живой человек голодает, мёрзнет и мыслит. Заводной автомат, оживлённый человеческим сердцем, сыт и покорен. Сюзанну увели на нижний горизонт...»")
      dnevnik = true
    elseif w == _'полки' then
      p("Атласы по часовым механизмам, анатомия гидравлических кукол, финансовые гроссбухи. Среди них — старые морские карты: Зурбаган, Лисс, Гель-Гью. Схемы подключения живых вен к золотниковым коробкам помечены «Одобрено к производству».")
    else
      return false
    end
  end;
  obj = {
    obj {
      -"дневник,черновик|записка";
      nam = "дневник";
    }:attr 'scenery,scenery';

    obj {
      -"полки,атласы|карты|стеллажи";
      nam = "полки";
    }:attr 'scenery,scenery';

    obj {
      -"коридор|галерея";
      nam = "путь_библиотека_коридор";
      before_Walk = function(s, w, wh)
        move(me(), _'коридор')
      end;
      before_Enter = function(s, w, wh)
        move(me(), _'коридор')
      end;
    }:attr 'scenery,scenery';
  };
}

room {
  -"архив";
  nam = "архив";
  title = "Секретный архив";
  dsc = function(s)
    p("Каземат без окон, освещённый дуговой лампой. Вдоль стен — стальные шкафы. За столом — женщина с землистым лицом и короткими волосами. На стене — огромное полотно в позолоченной раме. Позади — дверь в галерею.")
    if arch_open then
      p("Полотно сдвинуто по рельсам. В нише — круглая дверца сейфа, как корабельный люк.")
    end
  end;
  before_Exam = function(s, w, wh)
    if w == _'картина' then
      p("Залитый солнцем Зурбаган. Белые террасы, лазурная бухта, клипера на волне, акации. От полотна веет солью и теплом нагретого камня.")
    elseif w == _'рама' then
      if not have(_'осколок') and not arch_open then
        p("Рама сплошная, вмурованная в кладку.")
      elseif have(_'осколок') and not arch_open then
        p("Сквозь скол видна зубчатая передача за позолотой. Полотно — на скрытых рельсах сейфа.")
      else
        p("Полотно уже отъехало, открывая нишу с сейфом.")
      end
    else
      return false
    end
  end;
  before_Turn = function(s, w, wh)
    if w == _'код_архив' and not arch_open then
      if code_known then
        p("Вы провернули лимб: 4-12-709. Свист воздуха, и картина отъехала в сторону.")
        arch_open = true
      else
        p("Вы вертите лимб наугад. Механизм молчит — нужно знать комбинацию.")
      end
    else
      return false
    end
  end;
  before_Talk = function(s, w, wh)
    if w == _'женщина' and not poet_saved and not poet_lost then
      p('Она пишет карандашом на обороте ведомости. "Я записываю живой мир, пока город не переплавили в чугун. Пока звучит строка — автоматоны не победили."')
    else
      return false
    end
  end;
  before_Yes = function(s, w, wh)
    if not poet_saved and not poet_lost then
      p('"Пишите. Ваше слово сильнее всех шестерёнок". Женщина поднимает глаза: "Возьмите песнь о Зурбагане и карандаш. Она — для тех, чьё сердце не согласно стать механизмом."')
      poet_saved = true
      enable(_'поэма')
      take(_'поэма')
    else
      return false
    end
  end;
  before_No = function(s, w, wh)
    if not poet_saved and not poet_lost then
      p('"Бросьте рифмы. В этом мире выживают сталью и пайками". Женщина гасит лампу и уходит во тьму.')
      poet_lost = true
    else
      return false
    end
  end;
  before_Enter = function(s, w, wh)
    if w == _'сейф_архив' then
      if arch_open and have(_'поэма') then
        move(me(), _'зурбаган')
      elseif arch_open and not have(_'поэма') then
        p("Вы шагнули в люк, но упёрлись в глухую заслонку. Без живой мечты этот ход мёртв.")
      else
        p("Сейф ещё закрыт.")
      end
    else
      return false
    end
  end;
  obj = {
    obj {
      -"картина|полотно|зурбаган";
      nam = "картина";
    }:attr 'scenery,scenery';

    obj {
      -"рама,позолота";
      nam = "рама";
    }:attr 'scenery,scenery';

    obj {
      -"женщина,поэтесса";
      nam = "женщина";
    }:attr 'animate';

    obj {
      -"стихи|песнь,строка";
      nam = "стихи";
    }:attr 'scenery,scenery';

    obj {
      -"смирение|покой,порядок";
      nam = "смирение";
    }:attr 'scenery,scenery';

    obj {
      -"сейф,люк|дверца";
      nam = "сейф_архив";
    }:attr 'scenery,scenery,enterable';

    obj {
      -"код|комбинация|лимб,412709,709|цифры";
      nam = "код_архив";
    }:attr 'scenery,scenery';

    obj {
      -"коридор|галерея";
      nam = "путь_архив_коридор";
      before_Walk = function(s, w, wh)
        move(me(), _'коридор')
      end;
      before_Enter = function(s, w, wh)
        move(me(), _'коридор')
      end;
    }:attr 'scenery,scenery';
  };
}

room {
  -"кабинет";
  nam = "кабинет";
  title = "Кабинет Председателя";
  dsc = function(s)
    p("Овальный зал в стиле ампир. В камине горят дрова. Вдоль стен — двадцать портретов хозяина: на каждом следующем он выше и величественнее. За пультом из красного дерева сидит господин в цилиндре и визитке. Под его ладонью — тяжёлая серебряная печать Правления. Рядом — модель парусника под стеклом, тонкая, как паутина. Позади — дверь в галерею.")
    if not bird_freed then
      p("На каминной полке в золочёной клетке — заводной соловей. Рубиновые глаза.")
    end
    if bird_freed then
      p("Клетка пуста, дверца распахнута.")
    end
    if boss_banished then
      p("Камин чадит. В кресле — цилиндр, опавшая визитка и горсть пепла.")
    end
    if boss_banished and not have(_'печать') then
      p("На пульте — тяжёлая серебряная печать Правления.")
    end
  end;
  before_Exam = function(s, w, wh)
    if w == _'клетка' then
      if not bird_freed then
        p("В клетке — искусная латунная птица. При шаге её пружина сухо щёлкает, имитируя щебет.")
      else
        p("Дверца распахнута настежь. Клетка пуста.")
      end
    elseif w == _'парусник' then
      if not boss_banished then
        p("Тонкая работа. Паруса — из пергамента, рангоут — из меди. На борту — имя: «Зурбаган». Хозяин держит его под стеклом, как держат сердце.")
      else
        p("Модель парусника «Зурбаган» цела. Стекло треснуло от жара камина, но корабль уцелел.")
      end
    else
      return false
    end
  end;
  before_Open = function(s, w, wh)
    if w == _'клетка' then
      if boss_banished and not bird_freed then
        p("Вы откинули крючок. Соловей встрепенулся, издал чистую трель — словно свобода вдохнула душу в металл — и спорхнул на карниз открытой форточки, растворившись серебряным отблеском в метели.")
        bird_freed = true
      elseif bird_freed then
        p("Клетка уже открыта, птица на свободе.")
      else
        p('Хозяин кладёт ладонь на дверцу: "Не трогайте соловья. Он поёт только по моим законам."')
      end
    else
      return false
    end
  end;
  before_Talk = function(s, w, wh)
    if w == _'господин' then
      if not boss_banished then
        p('Он улыбается тонкой, нарисованной улыбкой. "Добро пожаловать. На улице — голод, тиф, тьма. А здесь — идеальный покой. Отдайте мне ваше зеркало, выпейте чаю с сахаром. Сюзанна вернётся к вам в фарфоре и шелках, совершенная и вечно молодая."')
      else
        p("В кресле — лишь помятый цилиндр и опавшая визитка. Говорить не с кем.")
      end
    else
      return false
    end
  end;
  before_Show = function(s, w, wh)
    if w == _'осколок' and have(_'осколок') and not boss_banished then
      p("Вы вскинули осколок перед его глазами. В амальгаме — плешивая крыса в золотой короне из шестерён. Тварь завизжала, дёрнула рычаг люка и провалилась в жерло мусоросброса.")
      boss_banished = true
    else
      return false
    end
  end;
  before_Give = function(s, w, wh)
    if w == _'осколок' and have(_'осколок') and not boss_banished then
      walk(_'dollend')
    else
      return false
    end
  end;
  obj = {
    obj {
      -"клетка|соловей|птица";
      nam = "клетка";
    }:attr 'scenery,scenery';

    obj {
      -"парусник|модель|корабль";
      nam = "парусник";
    }:attr 'scenery,scenery';

    obj {
      -"господин,председатель,хозяин";
      nam = "господин";
    }:attr 'animate';

    obj {
      -"печать";
      nam = "печать";
      before_Take = function(s, w, wh)
        if not boss_banished then
          p('Господин накрывает печать ладонью: "Это печать Правления. Не торопите события."')
          return
        end
        p("Тяжёлая печать Правления: шестерня, обвитая колосьями, и корона.")
        return false
      end;
    };

    obj {
      -"коридор|галерея";
      nam = "путь_кабинет_коридор";
      before_Walk = function(s, w, wh)
        move(me(), _'коридор')
      end;
      before_Enter = function(s, w, wh)
        move(me(), _'коридор')
      end;
    }:attr 'scenery,scenery';
  };
}

room {
  -"будуар";
  nam = "будуар";
  title = "Будуар кукол";
  dsc = function(s)
    p("Будуар с лиловыми шелковыми обоями. В резном кресле — девушка фарфоровой красоты, пастушка из придворной сказки. Пахнет миндальным кремом, розовым маслом и часовой смазкой. Налево — дверь в галерею. В глубине комнаты — шёлковый альков, затянутый тяжёлой портьерой.")
    if not doll_true then
      p("Глаза опущены, веки сомкнуты, пальцы сжимают веер.")
    end
    if doll_true and not corinna_awake then
      p("На затылке откинута золочёная крышка: внутри вращается латунный барабан шкатулки со стальными штифтами.")
    end
    if corinna_awake then
      p('Взгляд куклы обрёл осмысленность и грусть. "Я слышу вас. Меня зовут Коринна. Я больше не заводная кукла тирана."')
    end
  end;
  before_Exam = function(s, w, wh)
    if w == _'девушка' then
      if not doll_true then
        p("Она кажется спящей, но грудь неподвижна, а на запястьях — шарнирные головки с винтами.")
      end
    elseif w == _'альков' then
      if corinna_awake then
        p("За портьерой — потайная панель, отъехавшая в сторону: за ней узкий ход в изолятор кукол.")
      elseif doll_true then
        p("За портьерой — потайная панель, запертая пружинным ригелем. Механизм молчит, сколько ни нажимай.")
      else
        p("За портьерой — глухая стена. Ни шва, ни скважины.")
      end
    else
      return false
    end
  end;
  before_Show = function(s, w, wh)
    if w == _'осколок' and have(_'осколок') then
      if not doll_true then
        p("В зеркале вместо шёлка — латунный скелет, пружинные тяги и микропоршни.")
        doll_true = true
      else
        p("В зеркале всё тот же холодный латунный каркас. Скрывать больше нечего.")
      end
    else
      return false
    end
  end;
  before_Rewrite = function(s, w, wh)
    if w == _'строка' then
      if doll_true and have(_'поэма') and not corinna_awake then
        p('Карандашом поэтессы вы нанесли строфу о Зурбагане на барабан шкатулки. Музыка ожила хрустальным перезвоном. Кукла повернула голову: "Вы подарили мне душу. Я открыла потайной люк в изолятор кукол. Спешите! А в машинном зале вложите стихи в считывающий валик органа — остальное я сделаю сама."')
        corinna_awake = true
      elseif doll_true and have(_'поэма') and corinna_awake then
        p("Строфа уже выбита на барабане. Механизм Коринны оживлён.")
      end
    else
      return false
    end
  end;
  before_Talk = function(s, w, wh)
    if w == _'девушка' and corinna_awake then
      p("Торопитесь в изолятор! Я проберусь по вентиляционным каналам к машинному отделению и перехвачу тяги клапана.")
    else
      return false
    end
  end;
  obj = {
    obj {
      -"девушка,кукла,коринна,пастушка";
      nam = "девушка";
    }:attr 'animate';

    obj {
      -"строка,строфа|барабан|шкатулка";
      nam = "строка";
    }:attr 'scenery,scenery';

    obj {
      -"альков|портьера,панель";
      nam = "альков";
    }:attr 'scenery,scenery';

    obj {
      -"коридор|галерея";
      nam = "путь_будуар_коридор";
      ["before_Walk,Enter"] = function(s, w, wh)
        move(me(), _'коридор')
      end;
    }:attr 'scenery,scenery';

    obj {
      -"кладовая|изолятор";
      nam = "путь_будуар_кладовая";
      ["before_Walk,Enter"] = function(s, w, wh)
        if corinna_awake then
          move(me(), _'кладовая')
        elseif doll_true then
          p("Пружинный ригель заперт снаружи. Коринна должна открыть его изнутри — но она ещё спит.")
          return
        else
          p("Тайник ещё не обнаружен.")
          return
        end
      end;
    }:attr 'scenery,scenery,enterable';
  };
}

room {
  -"бухгалтерия|расчётная|палата";
  nam = "бухгалтерия";
  title = "Расчетная палата";
  dsc = function(s)
    p("Зал конторских столов, засыпанных перфолентами. В центре — пишущая машинка «Ундервуд», соединённая тягами с замками конторки. Позади — дверь в галерею.")
    if not have(_'карточка') then
      p("Из лотка торчит учётная карточка.")
    end
  end;
  before_Type = fn_type_name;
  before_Push = fn_type_name;
  before_Exam = function(s, w, wh)
    if w == _'тайник' and type_done and not have(_'ключ_подвала') then
      p("В тайнике — тяжёлый трёхгранный ключ от жалюзи машинного зала.")
      enable(_'ключ_подвала')
      take(_'ключ_подвала')
    else
      return false
    end
  end;
  obj = {
    obj {
      -"карточка|учётная";
      nam = "карточка";
      before_Take = function(s, w, wh)
        p("Карточка на имя Марии Бранд, перфораторщицы. В графе: «Передана для сборки ритмического узла котельной».")
        return false
      end;
    };

    obj {
      -"машинка|ундервуд|литеры|клавиши";
      nam = "машинка";
    }:attr 'scenery,scenery';

    obj {
      -"имя|буквы|мария";
      nam = "имя";
    }:attr 'scenery,scenery';

    obj {
      -"тайник|тумба,крышка";
      nam = "тайник";
    }:attr 'scenery,scenery';

    obj {
      -"коридор|галерея";
      nam = "путь_бухгалтерия_коридор";
      before_Walk = function(s, w, wh)
        move(me(), _'коридор')
      end;
      before_Enter = function(s, w, wh)
        move(me(), _'коридор')
      end;
    }:attr 'scenery,scenery';
  };
}

room {
  -"подвал,коллектор,тоннель";
  nam = "подвал";
  title = "Подземный коллектор";
  dsc = function(s)
    p("Сводчатый тоннель из кирпича. Под ногами — сточная жижа. Пар со свистом вырывается из фланцев. Вдоль стен — пучки гидравлических шлангов. Пять люков ведут во тьму: один — наверх, в караулку; четыре — в котельную, мастерскую, депозитарий и прачечную.")
  end;
  obj = {
    Path {
      -"охрана,караулка|наверх";
      nam = "путь_подвал_охрана";
      walk_to = 'охрана';
    };

    Path {
      -"котельная";
      nam = "путь_подвал_котельная";
      walk_to = 'котельная';
    };

    Path {
      -"мастерская,лаборатория";
      nam = "путь_подвал_мастерская";
      walk_to = 'мастерская';
    };

    Path {
      -"депозитарий";
      nam = "путь_подвал_депозитарий";
      walk_to = 'депозитарий';
    };

    Path {
      -"прачечная";
      nam = "путь_подвал_прачечная";
      walk_to = 'прачечная';
    };
  };
}

room {
  -"котельная|водогрейная";
  nam = "котельная";
  title = "Водогрейная секция";
  dsc = function(s)
    p("Огромные котлы дрожат от давления. В поддувалах гудит пламя. Манометры бьются, выпуская струи пара. У топки — сгорбленный седой старик в кожаном фартуке со стальной лопатой. Позади — дверь в коллектор.")
  end;
  before_Talk = function(s, w, wh)
    if w == _'кочегар' then
      if not brand_spoken then
        p('Старик хрипит сквозь вой пламени: "Я Бранд, старший механик пара. Сорок лет топлю котлы этого банка-ловушки. Теперь здесь жгут книги и жизни. Где моя Маша? Она ушла наверх за талонами и не вернулась."')
      else
        p("Запомнил мелодию? Замки сейфа настроены на водяной метроном в прачечной.")
      end
    else
      return false
    end
  end;
  before_Show = function(s, w, wh)
    if w == _'карточка' and have(_'карточка') then
      if not brand_spoken then
        p('Старик роняет лопату. "Значит, разобрали мою девочку на шестерни... Слушай и запоминай ритм восстания: семь долей вверх, четыре вниз — так усыпляют стаю и сбивают ход гигантских поршней. Флейта мастера — в сейфе депозитария." Он тихо напевает древнюю мелодию Крысолова.')
        brand_spoken = true
      else
        p("Старик уже знает правду о Маше. Он молча смотрит в пламя топок.")
      end
    else
      return false
    end
  end;
  obj = {
    obj {
      -"кочегар,старик,бранд,механик";
      nam = "кочегар";
    }:attr 'animate';

    obj {
      -"котлы|топка|пламя";
      nam = "котлы";
    }:attr 'scenery,scenery';

    Path {
      -"подвал,коллектор";
      nam = "путь_котельная_подвал";
      walk_to = 'подвал';
    };
  };
}

room {
  -"мастерская,лаборатория";
  nam = "мастерская";
  title = "Механическая лаборатория";
  dsc = function(s)
    p("Лаборатория часовщика. Под потолком на цепях — разобранные анатомические автоматоны. На верстаках — шестерни, реторты с глицерином, хирургические пилы. Позади — дверь в коллектор.")
  end;
  before_Exam = function(s, w, wh)
    if w == _'чертежи' then
      p("Чертежи шагающего парового автоматона. Примечание инженера: клапан имеет обратный конус золотника; если заклинить им распределитель — скопившийся конденсат вызовет сокрушительный гидроудар и разорвёт паровую машину изнутри.")
    else
      return false
    end
  end;
  obj = {
    obj {
      -"клапан,лепесток";
      nam = "клапан";
      before_Take = function(s, w, wh)
        p("Шедевр точной механики. Лепесток пружинит под пальцами, как живое маленькое сердечко.")
        return false
      end;
    };

    obj {
      -"чертежи,верстаки|автоматоны";
      nam = "чертежи";
    }:attr 'scenery,scenery';

    Path {
      -"подвал,коллектор";
      nam = "путь_мастерская_подвал";
      walk_to = 'подвал';
    };
  };
}

room {
  -"депозитарий";
  nam = "депозитарий";
  title = "Главный депозитарий";
  dsc = function(s)
    p("Круглая бронированная комната. Посреди зала — тяжёлый сейф-монолит с зубчатыми передачами и кодовым штурвалом. Позади — дверь в коллектор.")
    if not dep_open then
      p("Сейф закрыт шестью ригелями.")
    end
    if dep_open and have(_'флейта') then
      p("Сейф распахнут, лоток пуст.")
    end
    if dep_open and not have(_'флейта') then
      p("В сейфе — резная чёрная флейта с чеканными серебряными кольцами.")
    end
  end;
  before_Turn = function(s, w, wh)
    if w == _'код_депо' and not dep_open then
      if code_known then
        p("Диски провернулись: 4-12-709. Стальная плита отошла в сторону.")
        dep_open = true
        enable(_'флейта')
      else
        p("Вы вертите лимб наугад. Механизм молчит — нужно знать комбинацию.")
      end
    else
      return false
    end
  end;
  obj = {
    obj {
      -"сейф,штурвал,монолит";
      nam = "сейф_депо";
    }:attr 'scenery,scenery';

    obj {
      -"флейта|инструмент";
      nam = "флейта";
      before_Take = function(s, w, wh)
        p("Вы взяли инструмент Крысолова. Чёрное дерево под пальцами кажется живым и слегка теплеет.")
        return false
      end;
    }:disable();

    obj {
      -"код|комбинация|штурвал,412709,709|цифры";
      nam = "код_депо";
    }:attr 'scenery,scenery';

    Path {
      -"подвал,коллектор";
      nam = "путь_депозитарий_подвал";
      walk_to = 'подвал';
    };
  };
}

room {
  -"прачечная|санитарная";
  nam = "прачечная";
  title = "Санитарная прачечная";
  dsc = function(s)
    p("Каменные чаны с щелочной пеной. Потолок рассечён трещиной, сквозь которую хлещет вода. Как будто где-то рядом, за стеной, шумит прибой. Позади — дверь в коллектор.")
    if not have(_'медальон') then
      p("На краю цинкового лотка поблёскивает вещица.")
    end
  end;
  before_Exam = function(s, w, wh)
    if w == _'вода' then
      p("Струя бьёт в таз мерно, как заводной механизм: 4 резких удара, 12 глухих капель, после паузы — частый плеск на 709 ударов. Ритм гидроаккумулятора.")
      code_known = true
    elseif w == _'чаны' then
      p("В баках замочена гражданская одежда. Людей раздевали здесь перед отправкой на конвейер.")
    else
      return false
    end
  end;
  obj = {
    obj {
      -"медальон|вещица";
      nam = "медальон";
      before_Take = function(s, w, wh)
        p("Медный медальон Сюзанны — тот самый, материнский. Внутри — засушенный василёк и прядка материнских русых волос. Пахнет её духами и полынью.")
        return false
      end;
    };

    obj {
      -"вода,струя|таз";
      nam = "вода";
    }:attr 'scenery,scenery';

    obj {
      -"чаны,баки|одежда";
      nam = "чаны";
    }:attr 'scenery,scenery';

    Path {
      -"подвал,коллектор";
      nam = "путь_прачечная_подвал";
      walk_to = 'подвал';
    };
  };
}

room {
  -"зал,колонный";
  nam = "зал";
  title = "Колонный зал";
  dsc = function(s)
    p("Парадная зала под куполом. Вдоль стен — столы с золотой посудой, дичью и графинами. Слева — дверь в галерею. Справа — низкая дверь кладовой. В глубине, за тяжёлой решёткой, — спуск к машинному залу.")
    if not rats_cleared then
      p("За столами пируют серые тени во фраках и лохмотьях. Звон золота, лязг зубов, блеск сотен бусинок глаз.")
    end
    if rats_cleared then
      p("Столы опрокинуты, посуда разбита. В выбитые витражи врывается метель.")
    end
  end;
  before_Exam = function(s, w, wh)
    if w == _'столы' then
      if not rats_cleared then
        p("Блюда источают дурманящий аромат мяса и хлеба.")
      else
        p("Разбитая посуда, перевёрнутые блюда. Ветер задувает свечи одну за другой.")
      end
    else
      return false
    end
  end;
  before_Eat = function(s, w, wh)
    if w == _'столы' then
      if not rats_cleared then
        walk(_'death_eat1')
      else
        walk(_'death_eat2')
      end
    else
      return false
    end
  end;
  obj = {
    obj {
      -"столы|яства,блюда|пир";
      nam = "столы";
    }:attr 'scenery,scenery';

    Path {
      -"коридор|галерея";
      nam = "путь_зал_коридор";
      walk_to = 'коридор';
    };

    obj {
      -"кладовая|изолятор";
      nam = "путь_зал_кладовая";
      ["before_Walk,Enter"] = function(s, w, wh)
        if not rats_cleared then
          p("За дверью — чавкающий пир. Не пройти.")
          return
        end
        move(me(), _'кладовая')
      end;
    }:attr 'scenery,scenery,enterable';

    obj {
      -"сердце|решётка|машинный";
      nam = "путь_зал_сердце";
      ["before_Walk,Enter"] = function(s, w, wh)
        if not have(_'ключ_подвала') then
          p("Доступ преграждает тяжёлая решётка. Замок не сдвинуть без ключа.")
          return
        end
        if not have(_'печать') then
          p("Решётка поднята, но пульт заблокирован щитом с гербовым гнездом под печать Правления.")
          return
        end
        move(me(), _'сердце')
      end;
    }:attr 'scenery,scenery,enterable';
  };
}

room {
  -"кладовая|изолятор";
  nam = "кладовая";
  title = "Изолятор кукол";
  dsc = function(s)
    p("Мрачный склад. На мешках из-под отрубей, среди сломанных шестерён, неподвижно лежит фигура в синем креповом платье. Справа — дверь в зал. Слева, за штабелем ящиков, — узкая щель потайного хода в будуар.")
    if not fake_tested then
      p("Это Сюзанна! Лицо бледно, ресницы опущены, руки скрещены на груди.")
    end
    if fake_tested then
      p("Зеркальный скол снял морок: перед вами механический манекен-ловушка.")
    end
  end;
  before_Exam = function(s, w, wh)
    if w == _'фигура' then
      if have(_'осколок') and not fake_tested then
        p("Под восковой кожей — латунный каркас и взведённая пружина. Приманка! Настоящая Сюзанна жива и заперта у главного привода машины.")
        fake_tested = true
      elseif not have(_'осколок') then
        p("Девушка кажется спящей, но неподвижность пугает. На запястье нет пульса.")
      end
    else
      return false
    end
  end;
  before_Touch = function(s, w, wh)
    if w == _'фигура' then
      if not fake_tested then
        walk(_'death_embrace')
      else
        p("Вы знаете, что это смертоносный муляж. Прикасаться — безумие.")
      end
    else
      return false
    end
  end;
  obj = {
    obj {
      -"фигура,сюзанна|манекен|девушка";
      nam = "фигура";
    }:attr 'scenery,scenery';

    obj {
      -"будуар,тайник";
      nam = "путь_кладовая_будуар";
      ["before_Walk,Enter"] = function(s, w, wh)
        if not corinna_awake then
          p("Пружинный ригель заперт снаружи.")
          return
        end
        move(me(), _'будуар')
      end;
    }:attr 'scenery,scenery,enterable';

    obj {
      -"зал";
      nam = "путь_кладовая_зал";
      ["before_Walk,Enter"] = function(s, w, wh)
        if not rats_cleared then
          p("За дверью — чавкающий пир. Не пройти.")
          return
        end
        move(me(), _'зал')
      end;
    }:attr 'scenery,scenery,enterable';
  };
}

room {
  -"сердце|машинное";
  nam = "сердце";
  title = "Машинное отделение: Серое Сердце";
  dsc = function(s)
    p("Подземная пещера, похожая на нутро железного исполина. В центре высится Серое Сердце — пульсирующий медно-чугунный агрегат высотой в три этажа, соединённый с трубами парового органа. В кварцевой колбе с прозрачным соляным раствором парит живая Сюзанна. Её дыхание соединено трубками с центральным регулятором машины. Позади — ход в зал, через поднятую решётку.")
  end;
  before_Exam = function(s, w, wh)
    if w == _'колба' then
      p("Сюзанна жива. Сквозь толщу кварца видно, как слабо вздрагивают её веки. Она беззвучно шевелит губами — и в этом движении вы вдруг узнаёте голос, который уже слышали: там, в раструбе и в трубке, сквозь треск реле, — «...помогите...» Это была она.")
    else
      return false
    end
  end;
  before_Show = function(s, w, wh)
    if w == _'медальон' and have(_'медальон') and wh == _'сюзанна' then
      if not medallion_shown then
        p("Сюзанна видит тусклый блеск меди и прижимает ладонь к стеклу изнутри. По её щеке бежит слеза. Дыхание выравнивается.")
        medallion_shown = true
      else
        p("Сюзанна по-прежнему прижимает ладонь к стеклу, не отрывая от вас преданного взгляда.")
      end
    else
      return false
    end
  end;
  before_Attack = function(s, w, wh)
    if w == _'колба' then
      if not tube_hit then
        p("Вы ударили по кварцу кулаком. Кварц отозвался глухим гулом и острой болью в суставах пальцев.")
        tube_hit = true
      else
        p("Кварц не поддаётся. Кулак уже саднит, а толку нет.")
      end
    else
      return false
    end
  end;
  before_Play = function(s, w, wh)
    if w == _'флейта' and have(_'флейта') then
      if brand_spoken then
        walk(_'win1')
      else
        p("Дерево молчит под пальцами: вы не знаете напева. Старик у топок помнит ритм бунта.")
      end
    else
      return false
    end
  end;
  before_Insert = function(s, w, wh)
    if wh == _'валик' and have(_'поэма') then
      if corinna_awake then
        walk(_'win3')
      else
        p("Вы не знаете, как перенастроить сложную гидравлику органа на ритм строфы. Нужна помощь Коринны — той, что знает устройство машины.")
      end
    elseif wh == _'распределитель' and have(_'клапан') then
      if have(_'ключ_подвала') then
        walk(_'win2')
      else
        p("Клапан не вогнать в шестерни голыми руками. Нужен тяжёлый трёхгранный ключ.")
      end
    else
      return false
    end
  end;
  obj = {
    obj {
      -"колба|кварц,цилиндр";
      nam = "колба";
    }:attr 'scenery,scenery';

    obj {
      -"сюзанна";
      nam = "сюзанна";
    }:attr 'animate';

    obj {
      -"валик|стихи|строфа";
      nam = "валик";
    }:attr 'scenery,scenery,container';

    obj {
      -"распределитель|шестерни|золотники";
      nam = "распределитель";
    }:attr 'scenery,scenery,container';

    obj {
      -"агрегат,орган,колосс";
      nam = "агрегат";
    }:attr 'scenery,scenery';

    Path {
      -"зал";
      nam = "путь_сердце_зал";
      walk_to = 'зал';
    };
  };
}

room {
  -"зурбаган|гавань,пристань";
  nam = "зурбаган";
  title = "Зурбаган (Пространство мечты)";
  dsc = function(s)
    p("Знойный полдень над гаванью. Пахнет просмолёнными канатами, апельсинами и морем. Белые паруса бригантин колышутся на лазурной воде. Здесь нет пайков, тифозной сыпи, доносчиков и шестерёнок мёртвого короля. Но в этом солнечном покое вы одни: Сюзанны здесь нет, и полдень кажется призрачным и неполным. Позади — сияющая арка, ведущая обратно в архив.")
  end;
  before_Exam = function(s, w, wh)
    if w == _'море' then
      p("Бирюзовая гладь уходит к самому горизонту, где тает дымок далёкого парохода.")
    elseif w == _'гавань' then
      p("Моряки в холщовых рубахах катят бочки с мускатом, с террасы кофейни доносится перебор мандолины.")
    else
      return false
    end
  end;
  before_Wait = function(s, w, wh)
    walk(_'win4')
  end;
  obj = {
    obj {
      -"море|гладь|горизонт";
      nam = "море";
    }:attr 'scenery,scenery';

    obj {
      -"гавань|моряки|бригантины";
      nam = "гавань";
    }:attr 'scenery,scenery';

    Path {
      -"архив|арка";
      nam = "путь_зурбаган_архив";
      walk_to = 'архив';
    };
  };
}

obj {
  -"ключ клерка,ключ от зала";
  nam = "ключ_клерка";
}:disable()

obj {
  -"поэма,песнь|листок";
  nam = "поэма";
}:disable()

obj {
  -"трёхгранный ключ,ключ от жалюзи";
  nam = "ключ_подвала";
}:disable()

gameover {
  nam = "badend";
  dsc = "Вы поворачиваетесь и уходите в морозную тьму. За спиной остаётся гранитная громада — и Сюзанна, которую вы не спасли. Каждую ночь вы будете слышать в вое труб глухой рокот прибоя и голос: «...помогите...»";
}

gameover {
  nam = "dollend";
  dsc = "Вы положили скол на пульт. Господин нажал кнопку — пол опустился. Чашка сладкого чая коснулась губ. Мороз, боль, Сюзанна — всё исчезло в шелесте шестерёнок. Вы стали винтиком великого дворца, забыв собственное имя.";
}

gameover {
  nam = "death_eat1";
  dsc = "Голод лишил вас рассудка. Вы впились в холодное мясо. Вкус божествен, но мысли погасли. Под столом сработал пружинный люк — и вы скатились в яму к стае.";
}

gameover {
  nam = "death_eat2";
  dsc = "Вы подобрали с пола кусок замерзшего мяса. Блюда были пропитаны карболкой и трупным ядом. Спазм скрутил желудок, сознание угасло.";
}

gameover {
  nam = "death_embrace";
  dsc = "Вы бросились к ней и сжали в объятиях. Из рукавов выскочили стальные иглы, вонзившись в сердце. Вы застыли рядом — два экспоната дворцового склада.";
}

gameover {
  nam = "win1";
  dsc = "Вы поднесли флейту к губам и вывели древний напев Бранда. Звуки наполнили трубы парового органа. Многотонный колосс дрогнул, поршни замедлили бег и застыли. Кварцевый цилиндр опустился на помост и раскрылся. Вы подхватили Сюзанну на руки. Стальной гигант склонил чугунную главу, пробив стену дворца и открывая путь наружу. Вы вышли на волю, на морозную набережную живого Петрограда!";
}

gameover {
  nam = "win2";
  dsc = "Вы вставили стальной клапан в шестерни распределителя и вогнали его трёхгранным ключом. Зубья смяло. Скопившийся конденсат запер золотники — и сокрушительный гидроудар разорвал паровые цилиндры! Грохот и облака перегретого пара наполнили зал. Обжигаясь брызгами кипятка, вы вытащили полуживую Сюзанну сквозь пролом в фундаменте прямо на лёд Мойки. Дворец-машина повержен, но город остался один на один со свободной, голодной зимой.";
}

gameover {
  nam = "win3";
  dsc = "Бесшумно выступив из тени паропроводных труб, Коринна приняла листок и заправила его в приёмный валик органа. Грохот гидравлики сменился хрустальным перезвоном колокольчиков и шумом морского прибоя. Каменные своды темницы растаяли лёгким туманом. Вы стоите на прогретом солнцем молу Зурбагана. Белые чайки кружат над синей водой, а рядом открывает глаза живая, улыбающаяся Сюзанна.";
}

gameover {
  nam = "win4";
  dsc = "Вы бросили морозный ад Петрограда. Вы остались на залитой солнцем пристани, растворившись в вечном сияющем полдне. Сюзанна осталась там, во тьме дворца, но вы больше не помните её имени.";
}

function mp:Play(w, wh)
  p "Сейчас не время для музыки."
end

function mp:Type(w, wh)
  p "Печатать можно только на машинке."
end

function mp:Rewrite(w, wh)
  p "Переписать это невозможно."
end
