-- generated by mise.py; do not edit

--$Name:Плащ Тьмы$
require "fmt"
require "parser/mp-ru"

obj {
  nam = "none";
}

Door = Class({
  from = 'none';
  to = 'none';
  door_to = function(s)
    if here() == _(s.from) then
      return _(s.to)
    end
    if here() == _(s.to) then
      return _(s.from)
    end
    return false
  end;
}, door):attr 'open'

Path = Class {
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(std.ref(s.walk_to)) then return end
    walk(s.walk_to)
  end;
  before_Default = function(s, ev, w, wh)
    if s.desc then p(s.desc) return end
    p([[Ты можешь пойти в ]], std.ref(s.walk_to):noun('вн'), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

global 'score' (0)

_'game'.hint_verbs = { "#Exam", "#Walk", "#Take", "#Drop" }

VerbExtendWord { "#Drop", "повес/ить", "{noun}/вн,held на {noun}/вн,supporter : PutOn", "~ на {noun}/вн,supporter {noun}/вн,held : PutOn reverse" }

game.dsc = [[^{$fmt b|ПЛАЩ ТЬМЫ}^^Тривиальная Информ-демонстрация.
^^Торопливо пробираясь сквозь дождливую и холодную ноябрьскую ночь,
Вы радостно заметили неподалеку ярко горящие огни Оперного театра.^
Конечно, очень странно, что рядом не заметно ни одной живой души...
но стоит ли ждать слишком много от простенькой демонстрационной игры?..^]]
function start(load)
  move(me(), _'foyer')
  move(_'cloak', me())
  _'cloak':attr("worn")
end
function init()
end

room {
  -"фойе";
  nam = "foyer";
  title = "Фойе Оперного Театра";
  dsc = [[Вы стоите в центре просторного холла,
полного роскоши и декорированного красным и золотым.
Массивные люстры ярко сияют под потолком.
На север отсюда имеется выход на улицу,
две другие двери ведут в южном и западном направлении.]];
  s_to = 'bar';
  w_to = 'cloakroom';
  n_to = function(s)
    p("Вы только пришли сюда. К тому же, погода снаружи заметно ухудшается.")
  end;
}

room {
  -"гардероб";
  nam = "cloakroom";
  title = "Гардероб";
  dsc = [[Когда-то на стенах этой комнаты было множество крючков,
предназначенных для одежды, но сохранился только один.
Единственный выход отсюда -- восточная дверь.]];
  e_to = 'foyer';
  obj = {
    obj {
      -"маленький бронзовый крючок,крючок|вешалка";
      nam = "hook";
      description = function(s)
        p("Всего лишь маленький бронзовый крючок для одежды,")
        if where(_'cloak') == s then
          p("с которого свисает черный бархатный плащ.")
        else
          p("привинченный к стене.")
        end
      end;
    }:attr 'scenery,supporter';
  };
}

room {
  -"буфет";
  nam = "bar";
  title = "Буфет";
  dsc = [[Театральный буфет (намного более скромный,
чем можно было предположить после роскоши фойе,
расположенного к северу отсюда) совершенно пуст.
Но похоже, что в пыли на полу написано что-то важное.]];
  n_to = 'foyer';
  before_Walk = function(s, w, wh)
    if (mp:compass_dir(w) or nil) ~= "n_to" and not w:has("light") then
      _'message'.number = _'message'.number + (2)
      p("Слоняться в кромешной тьме -- не самая лучшая идея.")
      return
    end
    return false
  end;
  before_Default = function(s, ev, w, wh)
    if ev == 'Exit' then
      return false
    end
    if not s:has("light") then
      _'message'.number = _'message'.number + (1)
      p("В непроглядной темноте это очень трудно...")
      return
    end
    return false
  end;
  obj = {
    obj {
      -"надпись|пыль";
      nam = "message";
      number = 0;
      description = function(s)
        if s.number < 2 then
          p("Начертанная в пыли надпись сообщает Вам, что...")
          walk(_'goodend')
        else
          p([[Полустертую надпись разобрать очень трудно.
С трудом можно различить такие слова...]])
          walk(_'badend')
        end
      end;
    }:attr 'scenery';
  };
}:attr '~light'

obj {
  -"бархатный плащ,плащ";
  nam = "cloak";
  scored = false;
  description = [[
Хороший плащ (из черного бархата с атласной прокладкой),
немного промокший от дождя. Его чернота настолько глубока,
что возникает ощущение, словно он втягивает в себя весь свет
из окружающего мира.]];
  ["before_Drop,PutOn"] = function(s, w, wh)
    if here() == _'cloakroom' then
      _'bar':attr("light")
      if (mp.event) == 'PutOn' and not s.scored then
        s.scored = true
        score = score + (1)
      end
      return false
    else
      p("Не самое подходящее место для того, чтобы оставлять здесь свою одежду.")
      return
    end
  end;
  after_Take = function(s, w, wh)
    _'bar':attr("~light")
    return false
  end;
  after_PutOn = function(s, w, wh)
    if w ~= _'hook' then
      return false
    end
    p("Ты повесил плащ на крючок.")
  end;
}:attr 'clothing'

gameover {
  nam = "badend";
  title = "Вы проиграли";
  dsc = false;
}

gameover {
  nam = "goodend";
  title = "Вы выиграли";
  dsc = function(s)
    p('Ваш счет: ', score)
  end;
}
