-- generated by mise.py; do not edit

--$Name:t$
require "fmt"
require "parser/mp-ru"

local function fn_pick(s)
  if ((((function(o) local m = getmetatable(s) while m do if m == o then return true end m = getmetatable(m) end return false end)(_G[("Tree")])))) then
    return [[дерево]]
  elseif s:has("scenery") then
    return [[декорация]]
  else
    return [[прочее]]
  end
end

obj {
  nam = "none";
}

Door = Class({
  from = 'none';
  to = 'none';
  door_to = function(s)
    if here() == _(s.from) then
      return _(s.to)
    end
    if here() == _(s.to) then
      return _(s.from)
    end
    return false
  end;
}, door):attr 'open'

Path = Class {
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(std.ref(s.walk_to)) then return end
    walk(s.walk_to)
  end;
  before_Default = function(s, ev, w, wh)
    if s.desc then p(s.desc) return end
    p([[Ты можешь пойти в ]], std.ref(s.walk_to):noun('вн'), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

Tree = Class {
}:attr 'scenery'

obj {
  -"коробка";
  nam = "box";
  Take = function(s, w, wh)
    local o = seen('box')
    if o then
      o:attr("seen")
      p(fn_pick(s))
    else
      p([[не видно]])
    end
  end;
}

_'box'.Gaze = function(s, w, wh)
  p([[смотрят]])
  local style = "light"
  if style == "light" then
    return false
  end
  local e = 'Exam'
  if e == 'Wear' then
    p([[одежда]])
  end
end;
