-- generated by mise.py; do not edit

--$Name:talk$
require "fmt"
require "parser/mp-ru"

obj {
  nam = "none";
}

Door = Class({
  from = 'none';
  to = 'none';
  door_to = function(s)
    if here() == _(s.from) then
      return _(s.to)
    end
    if here() == _(s.to) then
      return _(s.from)
    end
    return false
  end;
}, door):attr 'open'

Path = Class {
  walk_to = 'none';
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(_(s.walk_to)) then
      return
    end
    walk(_(s.walk_to))
  end;
  before_Default = function(s, ev, w, wh)
    local d = (s.desc)
    if d then
      p(d)
      return
    end
    p('Ты можешь пойти в ', _(s.walk_to):noun_hint("вн"), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

global 'met' (false)
global 'q1' (0)

function start(load)
  move(me(), _'hall')
end
function init()
end

room {
  -"зал";
  nam = "hall";
  dsc = "Большой зал.";
}

obj {
  -"гид,проводник";
  nam = "guide";
  dsc = "Суровый гид.";
  found_in = 'hall';
  talk_to = 'разговор_с_гидом';
}

dlg {
  nam = 'разговор_с_гидом';
  phr = {
    "-- Здравствуйте, путник.";
    {
      "Что тут случилось?";
      "-- Обвал в шахте.";
      {
        "Кто виноват?";
        function(s)
          p("-- Никто.")
          q1 = q1 + (1)
        end;
      };
      {
        "Секретный вариант";
        function(s)
          p("-- Тс-с-с.")
          q1 = q1 + (10)
        end;
        hidden = true;
      };
      {
        "Только один раз";
        only = true;
        next = '#финал';
      };
      cond = function() return not met end;
    };
    {
      "Я скоро вернусь.";
      function(s)
        met = true
        walkout()
      end;
      always = true;
    };
  };
  obj = {
    {
      '#финал';
      "-- Продолжение следует.";
      {
        "Спасибо.";
        function(s)
          met = true
          walkout()
        end;
      };
    };
  };
}
