-- generated by mise.py; do not edit

--$Name:Хейди$
require "fmt"
require "parser/mp-ru"

local function fn_compass_dir(w)
  local d = mp:compass_dir(w)
  return d or nil
end

local function fn_event()
  return mp.event
end

local function fn_call_before(s, ev)
  s['before_' .. ev](s)
end

local function fn_arg_word(i)
  return mp.args[i] and mp.args[i].word or ''
end

local function fn_tiny()
  return instead.tiny
end

Path = Class {
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(std.ref(s.walk_to)) then return end
    walk(s.walk_to)
  end;
  before_Default = function(s, ev, w)
    if s.desc then p(s.desc) return end
    p([[Ты можешь пойти в ]], std.ref(s.walk_to):noun('вн'), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

_'game'.hint_verbs = { "#Exam", "#Walk", "#Take", "#Drop" }

game.dsc = [[^Пример простой игры на Inform.
^Авторы: Роджер Фирт (Roger Firth) и Соня Кессерих (Sonja Kesserich).
^Перевод Юрия Салтыкова a.k.a. G.A. Garinson^
^Перевод на МЕТАПАРСЕР 3 выполнил Петр Косых.
^
]]
pl.word = -"ты/жр,2л"
pl.description = "Здесь нет зеркала."
pl.capacity = 1
function start(load)
  move(me(), _'before_cottage')
end
function init()
end

room {
  -"перед домом";
  nam = "before_cottage";
  title = "Перед домом";
  dsc = "Ты стоишь около избушки, на восток от которой раскинулся лес.";
  e_to = 'forest';
  in_to = function(s)
    p("Такой славный денек... Он слишком хорош, чтобы прятаться внутри.")
  end;
  cant_go = "Единственный путь ведет на восток.";
  obj = {
    obj {
      -"домик,дом|избушка,избу*,терем*,коттедж*,хат*,строени*";
      nam = "cottage";
      description = "Домик мал и неказист, но ты очень счастлива, живя здесь.";
      before_Enter = [[Такой славный денек...
Он слишком хорош, чтобы прятаться внутри.]];
    }:attr 'scenery';
  };
}

room {
  -"чаща|лес";
  nam = "forest";
  title = "В лесной чаще";
  dsc = [[На западе, сквозь густую листву, можно разглядеть небольшое строение.^
Тропинка ведет на северо-восток.]];
  w_to = 'before_cottage';
  ne_to = 'clearing';
  obj = {
    obj {
      -"птенчик,птенец|птица,птичка|детёныш";
      nam = "bird";
      description = "Слишком мал, чтобы летать, птенец беспомощно попискивает.";
      before_Listen = "Жалобный писк испуганной птички разрывает тебе сердце.^Надо помочь!";
    }:attr '~animate';
  };
}

room {
  -"полянка,поляна";
  nam = "clearing";
  title = "Полянка";
  dsc = [[Посреди полянки стоит высокий платан.
Тропинка вьется меж деревьев, уводя на юго-запад.]];
  sw_to = 'forest';
  u_to = 'top_of_tree';
  obj = {
    obj {
      -"гнездо|мох|прутики,прутья";
      nam = "nest";
      description = function(s)
        p("Гнездо сплетено из прутиков и аккуратно устлано мхом.")
        mp:content(s)
      end;
    }:attr 'container,open';

    obj {
      -"платан|дерево|ствол";
      nam = "tree";
      description = [[Величавое дерево стоит посреди поляны.
Кажется, по его стволу будет несложно влезть наверх.]];
      before_Climb = function(s, w, wh)
        move(me(), _'top_of_tree')
      end;
    }:attr 'scenery';
  };
}

room {
  -"верхушка";
  nam = "top_of_tree";
  title = "На верхушке дерева";
  dsc = "На этой высоте цепляться за ствол уже не так удобно.";
  d_to = 'clearing';
  after_Drop = function(s, w, wh)
    move(w, _'clearing')
    return false
  end;
  obj = {
    obj {
      -"сук|ветка";
      nam = "branch";
      description = "Сук достаточно ровный и крепкий, чтобы на нем надежно держалось что-то не очень большое.";
      each_turn = function(s)
        if _'bird':inside(_'nest') and _'nest':inside(_'branch') then
          walk(_'happyend')
        end
      end;
    }:attr 'supporter,static';
  };
}

gameover {
  nam = "happyend";
  title = "Конец";
  dsc = "Поздравляем! Вы прошли игру.";
}
