-- generated by mise.py; do not edit

--$Name:stdlib$
require "fmt"
require "parser/mp-ru"

local function fn_probe(w, t, ev)
  w:hasnt("open")
  w:once('tag')
  w:once()
  mp:subaction(ev)
  mp:subaction(ev, w, w)
  DaemonStart(w)
  DaemonStop(w)
  enable(w)
  disable(w)
  isDaemon(w)
  getDaemons()
  disabled(w)
  walkin(_'hall')
  take(w)
  drop(w)
  pairs(t)
  ipairs(t)
  walkout()
  visits(w)
  (mp.xevent or nil)
  visited(w)
  w:access()
  mp:offerslight(w)
  mp:visible_scope(_'hall')
  inroom(w)
  mp:thedark(w)
  w:multi_alias()
  w:gram()
  walkback()
  remove(w)
  push(w)
  mp:check_held(w)
  mp:check_live(w)
  mp:check_touch()
  mp:check_worn(w)
  mp:clear()
  mp:cls_prompt()
  w:need_scene(true)
  player_moved()
  lifeon(w)
  lifeoff(w)
  std.call(w, 'before_' .. ev)
  mp:runmethods('obj', 'take')
  mp:runorval(w, 'inv')
  theme.name()
  std.pclr()
  std.ref('box')
  ((mp.args[1] or {}).word or '')
  (instead.tiny)
  snd.music('x')
  rnd(1)
end

obj {
  nam = "none";
}

Door = Class({
  from = 'none';
  to = 'none';
  door_to = function(s)
    if here() == _(s.from) then
      return _(s.to)
    end
    if here() == _(s.to) then
      return _(s.from)
    end
    return false
  end;
}, door):attr 'open'

Path = Class {
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(std.ref(s.walk_to)) then return end
    walk(s.walk_to)
  end;
  before_Default = function(s, ev, w, wh)
    if s.desc then p(s.desc) return end
    p([[Ты можешь пойти в ]], std.ref(s.walk_to):noun('вн'), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

room {
  -"зал";
  nam = "hall";
  dsc = "Зал.";
}

obj {
  -"ящик";
  nam = "box";
}:attr 'container,open'
