import os
import sys

from . import state as S
from .common import *
from .parse import parse_source
from .prescan import apply_includes, prescan
from .decl import classify, parse_fn_sig
from .emit import Emitter
from .emitlogic import emit_logic
from .exprparse import fn_name


_SKIP_KINDS = ("skip", "type", "extend_type", "mixin",
               "refs", "extend_refs", "props")


def _as_list(v):
    if isinstance(v, list):
        return v
    return [] if v is None else [v]


def _joined_params(plist, variadic):
    prm = ", ".join(pn for pn, _pt in plist)
    if variadic:
        prm = (prm + ", ...") if prm else "..."
    return prm


def _fn_body(ctx, em, val, plist, ret, name, prm):
    if isinstance(val, Lua):
        return reindent(val.s, IND)
    if not isinstance(val, Logic):
        raise Error("fn %s must be a | block" % name)
    owner = plist[0][1] if plist else None
    prev = ctx.current_owner
    if owner in ctx.classes:
        ctx.current_owner = owner
    try:
        return "\n".join(emit_logic(val.stmts, IND,
                                    em.param_env(prm, name), ret,
                                    name, ctx=ctx))
    finally:
        ctx.current_owner = prev


def _emit_fn(ctx, em, key, val):
    """Emit a `local function fn_...` body, or None when inlined."""
    name, plist, ret, variadic = parse_fn_sig(
        key, set(ctx.types) | ctx.classes)
    ctx.fns.add(name)
    if name in ctx.inline:
        return None
    prm = _joined_params(plist, variadic)
    hb = _fn_body(ctx, em, val, plist, ret, name, prm)
    return "local function %s(%s)\n%s\nend" % (fn_name(name), prm, hb)


def _lua_decl(_em, _info, _key, val):
    return val.s


def _class_decl(em, info, _key, val):
    return em.cls(val, info[0], info[1])


def _impl_decl(em, info, _key, val):
    return em.impl(info, val)


def _setup_decl(em, _info, _key, val):
    return "\n".join(em.setup(val))


def _const_decl(em, _info, _key, val):
    return "\n".join(em.const(val))


def _global_decl(em, _info, _key, val):
    return "\n".join(em.glob(val))


def _event_decl(em, info, _key, val):
    return em.event(info, val) or None


def _block_decl(em, _info, key, val):
    return em.decl(key, val, "")


# the emitters of the non-fn top-level kinds
DECL_FORMS = {
    "lua": _lua_decl,
    "class": _class_decl,
    "impl": _impl_decl,
    "setup": _setup_decl,
    "const": _const_decl,
    "global": _global_decl,
    "event_decl": _event_decl,
    "decl": _block_decl,
    "verb": _block_decl,
    "extend": _block_decl,
    "talk": _block_decl,
}


def _emit_decl(em, kind, key, val, info):
    """Emit one non-fn declaration; None means nothing to append."""
    form = DECL_FORMS.get(kind)
    if form is None:
        raise Error("unknown declaration: " + key)
    return form(em, info, key, val)


def _require_text(val):
    return [v.s if hasattr(v, "s") else str(v) for v in _as_list(val)]


def _add_fn(ctx, em, key, val, fn_body):
    block = _emit_fn(ctx, em, key, val)
    if block is not None:
        fn_body.append(block)


def _add_decl(em, kind, key, val, info, body):
    chunk = _emit_decl(em, kind, key, val, info)
    if chunk is not None:
        body.append(chunk)


def _body_items(ctx, em, root):
    header: list = []
    body: list = []
    fn_body: list = []
    reqs: list = []
    for _i, (key, val) in enumerate(root.items):
        CURRENT_LINE[0] = root.line_at(_i)
        kind, info = classify(key)
        if kind == "meta":
            header.append("--$%s:%s$" % (key.title(), val.s))
        elif kind in _SKIP_KINDS:
            continue
        elif kind == "require":
            reqs.extend(_require_text(val))
        elif kind == "fn":
            _add_fn(ctx, em, key, val, fn_body)
        else:
            _add_decl(em, kind, key, val, info, body)
    return header, fn_body + body, reqs


def _prelude(root, header, reqs):
    lang = root.get("lang")
    lang = lang.s if isinstance(lang, Bare) else "ru"
    pre = ["-- generated by mise.py; do not edit", ""] + header + [
        'require "fmt"']
    for v in _as_list(root.get("fmt")):
        if isinstance(v, (Bare, Text)):
            pre.append("fmt.%s = true" % v.s)
    pre.append('require "parser/mp-%s"' % lang)
    pre += ['require "%s"' % r for r in reqs]
    return pre


def transpile(src, src_dir=""):
    ctx = S.Ctx(src_dir)
    em = Emitter(ctx)
    CURRENT_LINE[0] = None
    root = parse_source(src)
    apply_includes(root, ctx)
    prescan(root, ctx)
    header, body, reqs = _body_items(ctx, em, root)
    pre = _prelude(root, header, reqs)
    return "\n".join(pre) + "\n\n" + "\n\n".join(body) + "\n"


def main(argv):
    if len(argv) < 2:
        print("usage: mise.py <game.mise> [-o out.lua]", file=sys.stderr)
        return 2
    with open(argv[1], encoding="utf-8") as f:
        src = f.read()
    out = transpile(src, os.path.dirname(os.path.abspath(argv[1])))
    if "-o" in argv:
        with open(argv[argv.index("-o") + 1], "w", encoding="utf-8") as outf:
            outf.write(out)
    else:
        sys.stdout.write(out)
    return 0
