import os
import sys

from . import state as S
from .common import *
from .parse import parse_source
from .prescan import apply_includes, prescan
from .decl import classify, parse_fn_sig
from .emit import Emitter
from .emitlogic import emit_logic
from .expr import fn_name


def transpile(src, src_dir=""):
    ctx = S.Ctx(src_dir)
    em = Emitter(ctx)
    root = parse_source(src)
    apply_includes(root, ctx)
    prescan(root, ctx)
    header = []
    body = []
    fn_body = []
    reqs = []
    for key, val in root.items:
        kind, info = classify(key)
        if kind == "meta":
            header.append("--$%s:%s$" % (key.title(), val.s))
        elif kind == "skip":
            continue
        elif kind == "require":
            vals = val if isinstance(val, list) else [val]
            for v in vals:
                reqs.append(v.s if hasattr(v, "s") else str(v))
        elif kind == "events":
            vals = val if isinstance(val, list) else [val]
            for v in vals:
                name = v.s if hasattr(v, "s") else str(v)
                ctx.extra_events[name] = name
        elif kind == "lua":
            body.append(val.s)
        elif kind == "class":
            body.append(em.cls(val, info[0], info[1]))
        elif kind == "fn":
            name, plist, ret, variadic = parse_fn_sig(key)
            ctx.fns.add(name)
            if name in ctx.wrappers or name in ctx.adapters:
                continue
            prm = ", ".join(pn for pn, _pt in plist)
            if variadic:
                prm = (prm + ", ...") if prm else "..."
            if isinstance(val, Lua):
                hb = reindent(val.s, IND)
            elif isinstance(val, Logic):
                hb = "\n".join(emit_logic(val.stmts, IND,
                                          em.param_env(prm, name), ret, name,
                                          ctx=ctx))
            else:
                raise Error("fn %s must be a | block"
                            % name)
            fn_body.append("local function %s(%s)\n%s\nend"
                           % (fn_name(name), prm, hb))
        elif kind == "patch":
            body.append(em.patch(info, val))
        elif kind == "setup":
            body.append("\n".join(em.setup(val)))
        elif kind == "const":
            body.append("\n".join(em.const(val)))
        elif kind == "global":
            body.append("\n".join(em.glob(val)))
        elif kind in ("decl", "verb", "extend", "talk"):
            body.append(em.decl(key, val, ""))
        else:
            raise Error("unknown declaration: " + key)
    body = fn_body + body
    lang = root.get("lang")
    lang = lang.s if isinstance(lang, Bare) else "ru"
    pre = ["-- generated by mise.py; do not edit", ""] + header + [
        'require "fmt"']
    root_fmt = root.get("fmt")
    if root_fmt:
        vals = root_fmt if isinstance(root_fmt, list) else [root_fmt]
        for v in vals:
            if isinstance(v, (Bare, Text)):
                pre.append("fmt.%s = true" % v.s)
    pre.append('require "parser/mp-%s"' % lang)
    pre += ['require "%s"' % r for r in reqs]
    return "\n".join(pre) + "\n\n" + "\n\n".join(body) + "\n"


def main(argv):
    if len(argv) < 2:
        print("usage: mise.py <game.mise> [-o out.lua]", file=sys.stderr)
        return 2
    with open(argv[1], encoding="utf-8") as f:
        src = f.read()
    out = transpile(src, os.path.dirname(os.path.abspath(argv[1])))
    if "-o" in argv:
        with open(argv[argv.index("-o") + 1], "w", encoding="utf-8") as f:
            f.write(out)
    else:
        sys.stdout.write(out)
    return 0
