import os
import sys

from . import state as S
from .common import *
from .parse import parse_source
from .prescan import apply_includes, prescan
from .decl import classify, parse_fn_sig
from .emit import Emitter
from .emitlogic import emit_logic
from .expr import fn_name


_SKIP_KINDS = ("skip", "type", "extend_type", "mixin",
               "refs", "extend_refs")


def _as_list(v):
    if isinstance(v, list):
        return v
    return [] if v is None else [v]


def _emit_fn(ctx, em, key, val):
    """Emit a `local function fn_...` body, or None when inlined."""
    name, plist, ret, variadic = parse_fn_sig(
        key, set(ctx.types) | ctx.classes)
    ctx.fns.add(name)
    if name in ctx.inline:
        return None
    prm = ", ".join(pn for pn, _pt in plist)
    if variadic:
        prm = (prm + ", ...") if prm else "..."
    if isinstance(val, Lua):
        hb = reindent(val.s, IND)
    elif isinstance(val, Logic):
        owner = plist[0][1] if plist else None
        prev = ctx.current_owner
        if owner in ctx.classes:
            ctx.current_owner = owner
        try:
            hb = "\n".join(emit_logic(val.stmts, IND,
                                      em.param_env(prm, name), ret,
                                      name, ctx=ctx))
        finally:
            ctx.current_owner = prev
    else:
        raise Error("fn %s must be a | block" % name)
    return "local function %s(%s)\n%s\nend" % (fn_name(name), prm, hb)


def _emit_decl(em, kind, key, val, info):
    """Emit one non-fn declaration; None means nothing to append."""
    if kind == "lua":
        return val.s
    if kind == "class":
        return em.cls(val, info[0], info[1])
    if kind == "impl":
        return em.impl(info, val)
    if kind == "setup":
        return "\n".join(em.setup(val))
    if kind == "const":
        return "\n".join(em.const(val))
    if kind == "global":
        return "\n".join(em.glob(val))
    if kind == "event_decl":
        return em.event(info, val) or None
    if kind in ("decl", "verb", "extend", "talk"):
        return em.decl(key, val, "")
    raise Error("unknown declaration: " + key)


def _body_items(ctx, em, root):
    header: list = []
    body: list = []
    fn_body: list = []
    reqs: list = []
    for _i, (key, val) in enumerate(root.items):
        CURRENT_LINE[0] = root.line_at(_i)
        kind, info = classify(key)
        if kind == "meta":
            header.append("--$%s:%s$" % (key.title(), val.s))
        elif kind in _SKIP_KINDS:
            continue
        elif kind == "require":
            reqs.extend(v.s if hasattr(v, "s") else str(v)
                        for v in _as_list(val))
        elif kind == "fn":
            block = _emit_fn(ctx, em, key, val)
            if block is not None:
                fn_body.append(block)
        else:
            chunk = _emit_decl(em, kind, key, val, info)
            if chunk is not None:
                body.append(chunk)
    return header, fn_body + body, reqs


def _prelude(root, header, reqs):
    lang = root.get("lang")
    lang = lang.s if isinstance(lang, Bare) else "ru"
    pre = ["-- generated by mise.py; do not edit", ""] + header + [
        'require "fmt"']
    for v in _as_list(root.get("fmt")):
        if isinstance(v, (Bare, Text)):
            pre.append("fmt.%s = true" % v.s)
    pre.append('require "parser/mp-%s"' % lang)
    pre += ['require "%s"' % r for r in reqs]
    return pre


def transpile(src, src_dir=""):
    ctx = S.Ctx(src_dir)
    em = Emitter(ctx)
    CURRENT_LINE[0] = None
    root = parse_source(src)
    apply_includes(root, ctx)
    prescan(root, ctx)
    header, body, reqs = _body_items(ctx, em, root)
    pre = _prelude(root, header, reqs)
    return "\n".join(pre) + "\n\n" + "\n\n".join(body) + "\n"


def main(argv):
    if len(argv) < 2:
        print("usage: mise.py <game.mise> [-o out.lua]", file=sys.stderr)
        return 2
    with open(argv[1], encoding="utf-8") as f:
        src = f.read()
    out = transpile(src, os.path.dirname(os.path.abspath(argv[1])))
    if "-o" in argv:
        with open(argv[argv.index("-o") + 1], "w", encoding="utf-8") as f:
            f.write(out)
    else:
        sys.stdout.write(out)
    return 0
