-- generated by mise.py; do not edit

--$Name:СКВОЗЬ ЗЕРКАЛО$
require "fmt"
require "parser/mp-ru"

obj {
  nam = "none";
}

Door = Class({
  from = 'none';
  to = 'none';
  door_to = function(s)
    if here() == _(s.from) then
      return _(s.to)
    end
    if here() == _(s.to) then
      return _(s.from)
    end
    return false
  end;
}, door):attr 'open'

Path = Class {
  walk_to = 'none';
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(_(s.walk_to)) then
      return
    end
    walk(_(s.walk_to))
  end;
  before_Default = function(s, ev, w, wh)
    local d = (s.desc)
    if d then
      p(d)
      return
    end
    p('Ты можешь пойти в ', _(s.walk_to):noun_hint("вн"), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

const 'HELD_STATE' (0)
const 'QUEEN_STATE' (1)
const 'WOOL_STATE' (2)
const 'CHAIR_STATE' (3)

_'game'.hint_verbs = { "#Exam", "#Walk", "#Push", "#Take", "#Drop", "#Search", "#Give", "#Touch" }

game.dsc = [[^Маленькая интерактивная Информ-обучалка^
   (написанная Гаретом Ризом и переведенная Денисом Гаевым)^
Перенесена на МЕТАПАРСЕР3 Петром Косых
^^Хотя за окном стоит холодный зимний день,
за зеркалом над каминной полкой почему-то еще продолжается лето!^
Так хочется оказаться там!^
Ну неужели не существует никакого способа попасть ЗА зеркало?]]
pl.word = -"ты/жр,2л"
function init()
  move(me(), _'Drawing_Room')
  DaemonStart(_'white_kitten')
  DaemonStart(_'black_kitten')
end

mp.Reflect = function(s, w, wh)
  if wh ~= _'mirror' then
    p("Сюрреализму этой идеи позавидовал бы и сам Льюис Кэрролл!")
    return
  end
  if w == _'hearth' or w == _'mirror' or (where(me()) ~= _'mantelpiece' and where(me()) ~= _'armchair') then
    p("Но Алисе вряд ли удастся поднести это к зеркалу!")
    return
  end
  p('Отражение ')
  if w == me() then
    p("Алисы")
  else
    p(w:noun_hint('рд'))
  end
  p(' в зеркале выглядит ')
  if where(me()) == _'mantelpiece' then
    p("слишком уж расплывчатым и размытым.")
    return
  end
  p('точь-в-точь как {#word/настоящий,#first}')
  if w == me() then
    p("Алиса")
  else
    p(w:noun_hint())
  end
  p('-- только левая и правая сторона поменялись местами!')
end

room {
  -"гостиная|снег|снежинки";
  nam = "Drawing_Room";
  title = "Гостиная";
  dsc = [[Там, за оконной рамой, беззвучно парят снежинки и властвует холод.
Алиса так рада, что она внутри, в тепле и уюте!
Гостиная отражается в большом зеркале, висящем на стене
над каминной полкой. И гостиная, и ее отражение в зеркале одинаково уютные --
с жарко пылающим камином, мягким ковриком перед ним,
и глубоким удобным креслом, в котором можно свернуться
клубочком и немного подремать.]];
  ["before_Exam,Search,Enter,ThrowAt,ThrownAt,Reflect,Touch"] = function() return false end;
}

obj {
  -"Чёрная Королева,королева,чёрная/жр|ферзь";
  nam = "red_queen";
  description = "Маленькая (но какая своенравная!) шахматная фигурка.";
}:attr '~animate'

obj {
  -"шахматная доска,доска";
  nam = "chess_board";
  found_in = 'Drawing_Room';
  init_dsc = function(s)
    p("На полу лежит раскрытая шахматная доска.")
    mp:content(s)
  end;
  description = "На полу лежала раскрытая шахматная доска с недоигранной партией. Но ни одной фигурки на ней уже не осталось -- котята играют с ними в менее интеллектуальные игры.";
}:attr 'supporter'

obj {
  -"камин,огонь|пламя|решетка";
  nam = "hearth";
  found_in = 'Drawing_Room';
  description = "За бронзовой каминной решеткой весело потрескивает огонь.";
}:attr 'scenery':dict { ["огонь/вн"] = "огонь" }

obj {
  -"каминный коврик,коврик|ковер";
  nam = "rug";
  founded = false;
  found_in = 'Drawing_Room';
  description = function(s)
    p([[Красивый каминный коврик из какой-то далекой страны -- может быть, Индии или Аравии.]])
  end;
  before_Take = "Но коврик слишком большой и тяжелый!";
  ["before_Push,Pull"] = "Но место каминного коврика -- рядом с камином!";
}:attr 'concealed,static,supporter,enterable'

obj {
  -"кресло|стул";
  nam = "armchair";
  found_in = 'Drawing_Room';
  moved = false;
  before_Transfer = "[Если так уж хочется сдвинуть кресло с места, попробуйте тянуть или толкать его.]";
  ["before_Climb,Enter"] = function(s, w, wh)
    move(me(), s)
    p("Алиса забралась с ногами в мягкое удобное кресло.")
  end;
  before_Take = "Но кресло слишком тяжелое для маленькой девочки!";
}:attr 'static,concealed,supporter,enterable'

obj {
  -"каминная полка,полка";
  nam = "mantelpiece";
  found_in = 'Drawing_Room';
}:attr 'concealed,supporter,enterable,static'

obj {
  -"зеркало,стекло";
  nam = "mirror";
  found_in = 'Drawing_Room';
  ["before_Touch,Pull,Push"] = { "Рука проходит сквозь серебристый туман", "не встречая сопротивления!" };
  before_ThrownAt = "И заработать семь лет несчастий и бед?!";
}:attr 'static,concealed,enterable'

obj {
  -"клубок шерсти,клубок|шерсть";
  nam = "worsted";
  found_in = 'Drawing_Room';
  sputan = false;
}

obj {
  -"окно|рама";
  nam = "window";
  found_in = 'Drawing_Room';
  description = [[За окном неторопливо кружатся снежинки,
заставляющие Алису радоваться, что она внутри дома, в тепле и уюте.]];
  before_Open = function(s, w, wh)
    p("И подхватить простуду?! Лучше оставить окно закрытым.")
  end;
  before_Search = function(s, w, wh)
    mp:xaction('Exam', s)
  end;
}:attr 'scenery'

Kitten = Class {
  other_kitten = 'none';
  life_Kiss = function(s, w, wh)
    p('Алиса чмокнула ', s:noun_hint('вн', 1), [[ в носик,
и тот взглянул на нее сконфуженно, но довольно.]])
  end;
  life_Attack = "Разве можно напасть на такое крохотное и беззащитное создание!";
  Show = function(s, w, wh)
    p(s:Noun_hint(1), ', протянув лапку, опасливо дотронулся до ', w:noun_hint('рд'), '.')
  end;
  ["before_Touch,Rub"] = function(s, w, wh)
    p(s:Noun_hint(1), ' в ответ потерся головой об Алисину руку и что-то тихонько промурлыкал.')
  end;
}:attr 'animate'

Kitten {
  -"белый котенок,котенок,белый";
  nam = "white_kitten";
  state = CHAIR_STATE;
  seen = false;
  found_in = 'Drawing_Room';
  this_kittens_turn = false;
  other_kitten = 'black_kitten';
}

Kitten {
  -"чёрный котенок,котенок,чёрный";
  nam = "black_kitten";
  state = CHAIR_STATE;
  seen = false;
  found_in = 'Drawing_Room';
  this_kittens_turn = true;
  other_kitten = 'white_kitten';
}

VerbExtend { "#Exam", "{noun}/вн,scene в {noun}/пр,2,scene : Reflect", "~ на {noun}/вн,scene в {noun}/пр,2,scene : Reflect", "~ в {noun}/пр,2,scene на {noun}/вн : Reflect reverse" }

mp.Untangle = function(s, w, wh)
  p("Что, распутать ЭТО?!")
end

Verb { '#Untangle', "размот/ать,распут/ать", "{noun}/вн : Untangle" }

Verb { '#Touch2', "ласк/ать,чеса/ть,почес/ать,почеш/и,чеши/", "{noun}/вн : Touch" }

_'Drawing_Room'.before_Exit = function(s, w, wh)
  if where(me()) ~= _'mantelpiece' then
    return false
  end
  if (mp:compass_dir(w) or nil) == "d_to" or (mp:compass_dir(w) or nil) == "out_to" or w == s then
    p("Таким путем вряд ли удастся спуститься с каминной полки!")
    return
  end
  return false
end;
_'Drawing_Room'.before_Walk = function(s, w, wh)
  if where(me()) ~= _'mantelpiece' then
    return false
  end
  if (mp:compass_dir(w) or nil) == "d_to" or (mp:compass_dir(w) or nil) == "out_to" or w == s then
    p("Таким путем вряд ли удастся спуститься с каминной полки!")
    return
  end
  return false
end;
_'Drawing_Room'.before_Default = function(s, ev, w, wh)
  if where(me()) ~= _'mantelpiece' then
    return false
  end
  if w and not w:inside(_'mantelpiece') then
    p('Отсюда трудно дотянуться до ')
    p(w:noun_hint('рд'), '.')
    return
  end
  if wh and not wh:inside(_'mantelpiece') then
    p('Отсюда трудно дотянуться до ')
    p(w:noun_hint('рд'), '.')
    return
  end
  return false
end;

_'red_queen'.dsc = function(s)
  if _'white_kitten'.state == QUEEN_STATE or _'black_kitten'.state == QUEEN_STATE then
    return
  end
  return false
end
_'red_queen'.after_Take = function(s, w, wh)
  if _'white_kitten'.state == QUEEN_STATE then
    _'white_kitten'.state = CHAIR_STATE
  end
  if _'black_kitten'.state == QUEEN_STATE then
    _'black_kitten'.state = CHAIR_STATE
  end
  return false
end;
_'red_queen'.after_PutOn = function(s, w, wh)
  if w == _'chess_board' then
    p([[В гордом одиночестве на шахматной доске, Черная Королева --
самодержавная повелительница 32 белых и 32 черных клеток.]])
    return
  end
  return false
end;
_'red_queen'.after_Transfer = function(s, w, wh)
  if w == _'chess_board' then
    p([[В гордом одиночестве на шахматной доске, Черная Королева --
самодержавная повелительница 32 белых и 32 черных клеток.]])
    return
  end
  return false
end;
_'red_queen'.after_Insert = function(s, w, wh)
  if w == _'chess_board' then
    p([[В гордом одиночестве на шахматной доске, Черная Королева --
самодержавная повелительница 32 белых и 32 черных клеток.]])
    return
  end
  return false
end;

_'rug'.before_LookUnder = function(s, w, wh)
  if where(me()) == _'mantelpiece' or where(me()) == _'armchair' then
    p("Отсюда вряд ли возможно дотянуться до коврика!")
    return
  end
  if where(me()) == s then
    p([[Алиса попыталась приподнять угол коврика, но потерпела неудачу.
Причиной оказалось то, что она стояла прямо на нем.
Мм-да, мир полон неожиданностей.]])
    return
  end
  if not s.founded then
    s.founded = true
    move(_'red_queen', me())
    p([[Алиса приподняла угол коврика -- и, заглянув под него,
обнаружила там Черную Королеву из шахматного набора!]])
    return
  end
  return false
end;

_'armchair'.description = function(s)
  p([[Большое глубокое кресло. Отличное место для котенка
или маленькой девочки, где можно устроиться поудобнее и подремать.
Сейчас оно стоит рядом с ]])
  if s.moved then
    p("камином.")
  else
    p("окном.")
  end
  return false
end
_'armchair'.before_Push = function(s, w, wh)
  local loc = where(me())
  if loc then
    if loc ~= _'Drawing_Room' then
      p('Для начала необходимо покинуть ', loc:noun_hint('вн'), '.')
      return
    end
  end
  if have(_'white_kitten') or have(_'black_kitten') then
    p("Только не с котенком в руках!")
    return
  end
  local k = _'none'
  if _'white_kitten'.state == CHAIR_STATE then
    k = _'white_kitten'
  elseif _'black_kitten'.state == CHAIR_STATE then
    k = _'black_kitten'
  end
  if k ~= _'none' then
    p([[Начав двигать кресло, Алиса обнаружила, что ]])
    p(k:noun_hint(1))
    p([[ находится прямо на его пути. Хорошо, что она заметила это
вовремя -- а то могла бы просто раздавить бедное создание!]])
    return
  end
  if s.moved then
    s.moved = false
    p("Алиса отодвинула кресло дальше от камина.")
    return
  end
  s.moved = true
  p("Алиса придвинула кресло ближе к камину.")
end;
_'armchair'.before_Pull = function(s, w, wh)
  local loc = where(me())
  if loc then
    if loc ~= _'Drawing_Room' then
      p('Для начала необходимо покинуть ', loc:noun_hint('вн'), '.')
      return
    end
  end
  if have(_'white_kitten') or have(_'black_kitten') then
    p("Только не с котенком в руках!")
    return
  end
  local k = _'none'
  if _'white_kitten'.state == CHAIR_STATE then
    k = _'white_kitten'
  elseif _'black_kitten'.state == CHAIR_STATE then
    k = _'black_kitten'
  end
  if k ~= _'none' then
    p([[Начав двигать кресло, Алиса обнаружила, что ]])
    p(k:noun_hint(1))
    p([[ находится прямо на его пути. Хорошо, что она заметила это
вовремя -- а то могла бы просто раздавить бедное создание!]])
    return
  end
  if s.moved then
    s.moved = false
    p("Алиса отодвинула кресло дальше от камина.")
    return
  end
  s.moved = true
  p("Алиса придвинула кресло ближе к камину.")
end;

_'mantelpiece'.description = function(s)
  p([[Она довольно высоко (гораздо выше, чем Алиса может достать),
но зато выглядит достаточно прочной и широкой,
чтобы на ней можно было стоять без риска.]])
  return false
end
_'mantelpiece'.before_Enter = function(s, w, wh)
  if where(me()) == s then
    p("Но Алиса уже на ней!")
    return
  end
  if where(me()) ~= _'armchair' then
    p("Каминная полка слишком высоко, чтобы до нее достать.")
    return
  end
  if not _'armchair'.moved then
    p("Отсюда невозможно дотянуться до каминной полки!")
    return
  end
  if (#(inv())) > 0 then
    p("Для этого руки должны быть свободны!")
    return
  end
  move(me(), _'mantelpiece')
  p("Алиса ловко вскарабкалась на каминную полку.")
end;
_'mantelpiece'.before_Climb = function(s, w, wh)
  if where(me()) == s then
    p("Но Алиса уже на ней!")
    return
  end
  if where(me()) ~= _'armchair' then
    p("Каминная полка слишком высоко, чтобы до нее достать.")
    return
  end
  if not _'armchair'.moved then
    p("Отсюда невозможно дотянуться до каминной полки!")
    return
  end
  if (#(inv())) > 0 then
    p("Для этого руки должны быть свободны!")
    return
  end
  move(me(), _'mantelpiece')
  p("Алиса ловко вскарабкалась на каминную полку.")
end;
_'mantelpiece'.before_Receive = function(s, w, wh)
  if where(me()) ~= s and (where(me()) ~= _'armchair' or not _'armchair'.moved) then
    p("Полка слишком высоко, за пределами досягаемости.")
    return
  end
  return false
end;
_'mantelpiece'.before_LetGo = function(s, w, wh)
  if where(me()) ~= s and (where(me()) ~= _'armchair' or not _'armchair'.moved) then
    p("Полка слишком высоко, за пределами досягаемости.")
    return
  end
  return false
end;

_'mirror'.description = function(s)
  if where(me()) == _'mantelpiece' then
    p([[Невероятно -- но стеклянная поверхность зеркала
тает на глазах, подобно призрачному серебристому пару!]])
    return
  end
  if where(me()) == _'armchair' then
    p([[В зеркале отражается хорошо знакомая гостиная -- в ней
все такое же, как и по эту сторону, только наоборот.
Но почему-то Алиса уверена в том, что за краем зеркала,
куда никак невозможно заглянуть, лежит мир Зазеркалья --
и он совершенно не похож на привычный...]])
    return
  end
  p([[Отсюда в зеркале можно разглядеть только потолок гостиной.
Впрочем, он ничем не отличается от потолка по эту сторону зеркала.]])
end
_'mirror'.before_Any = function(s, ev, w, wh)
  if (mp.event) ~= 'Exam' and (mp.event) ~= 'Reflect' and (mp.event) ~= 'Search' and (mp.event) ~= 'ThrownAt' and where(me()) ~= _'mantelpiece' then
    p("Отсюда невозможно даже дотянуться до зеркала!")
    return
  end
  return false
end;
_'mirror'.before_Enter = function(s, w, wh)
  p([[Рука Алисы без труда прошла через серебряный туман...
за ней последовало остальное тело...
и вот она уже по ту сторону зеркала!!!]])
  walk(_'theend')
end;

_'worsted'.dsc = function(s)
  if where(s) ~= here() then
    return false
  end
  if _'white_kitten'.state ~= WOOL_STATE and _'black_kitten'.state ~= WOOL_STATE then
    p("На полу лежит клубок шерсти.")
  end
end
_'worsted'.description = function(s)
  if s.sputan then
    p([[Сейчас он спутан так, что почти не размотаешь.
Сколько времени Алиса потратила на то, чтобы намотать шерсть
аккуратным клубком -- и вот, теперь на него страшно взглянуть!]])
  else
    p("Клубок очень хорошей голубой шерсти, готовый к вязанию.")
  end
end
_'worsted'.before_Untangle = function(s, w, wh)
  if s.sputan then
    s.sputan = false
    p([[Это оказалось не быстрым и не простым делом...
зато теперь клубок совсем как новый -- тугой и аккуратный!]])
  else
    p("Но шерсть не спутана!")
  end
end;
_'worsted'.after_Take = function(s, w, wh)
  if _'white_kitten'.state == WOOL_STATE then
    _'white_kitten'.state = CHAIR_STATE
  end
  if _'black_kitten'.state == WOOL_STATE then
    _'black_kitten'.state = CHAIR_STATE
  end
  return false
end;

Kitten.dsc = function(s)
  if s.state == QUEEN_STATE then
    p('^', s:Noun_hint(1), ' играет с Черной Королевой.')
  elseif s.state == WOOL_STATE then
    p('^', s:Noun_hint(1), ' играет с клубком шерсти.')
  elseif s.state == CHAIR_STATE then
    if s.seen then
      return
    end
    if _(s.other_kitten).state == CHAIR_STATE then
      _(s.other_kitten).seen = true
      p([[^Пара котят резвятся друг с другом на коврике рядом с креслом.]])
      return
    end
    p(s:Noun_hint(1), ' резвится на коврике рядом с креслом.')
    return
  else
    return
  end
end
Kitten.description = function(s)
  p([[Какой красивый котенок! Из пары именно он -- Алисин любимчик,
и намного симпатичней ей, чем непослушный и непоседливый ]])
  p(_(s.other_kitten):noun_hint(), '.')
end
Kitten.life_Ask = function(s, w, wh)
  p(s:Noun_hint(1), [[, шевеля усами, смотрит на Алису
с таким умным видом, что она почти готова поверить,
будто он понимает каждое ее слово.]])
end;
Kitten.life_Answer = function(s, w, wh)
  p(s:Noun_hint(1), [[, шевеля усами, смотрит на Алису
с таким умным видом, что она почти готова поверить,
будто он понимает каждое ее слово.]])
end;
Kitten.life_Tell = function(s, w, wh)
  p(s:Noun_hint(1), [[, шевеля усами, смотрит на Алису
с таким умным видом, что она почти готова поверить,
будто он понимает каждое ее слово.]])
end;
Kitten.life_Talk = function(s, w, wh)
  p(s:Noun_hint(1), [[, шевеля усами, смотрит на Алису
с таким умным видом, что она почти готова поверить,
будто он понимает каждое ее слово.]])
end;
Kitten.life_Give = function(s, w, wh)
  if w ~= _'red_queen' and w ~= _'worsted' then
    if (mp.event) == 'ThrowAt' then
      move(w, _'Drawing_Room')
      p('Алиса бросила ', w:noun_hint('вн'), ' на пол, и ', s:noun_hint(1))
    else
      p(s:Noun_hint(1))
    end
    p(' рассматривает ', w:noun_hint('вн'), ' с озадаченным видом.')
    return
  end
  p('Алиса бросила ', w:noun_hint('вн'), ' на пол. Немедленно ')
  pr(s:noun_hint(1))
  if have(s) then
    p(', выскользнув из ее рук,')
  end
  move(w, _'Drawing_Room')
  move(s, _'Drawing_Room')
  pr(' бросился за ', w:noun_hint('тв'))
  if w == _'worsted' then
    _'worsted'.sputan = true
    s.state = WOOL_STATE
    pr(', мгновенно превратив его в дикую путаницу')
  else
    s.state = QUEEN_STATE
  end
  p('.')
end;
Kitten.life_ThrowAt = function(s, w, wh)
  if w ~= _'red_queen' and w ~= _'worsted' then
    if (mp.event) == 'ThrowAt' then
      move(w, _'Drawing_Room')
      p('Алиса бросила ', w:noun_hint('вн'), ' на пол, и ', s:noun_hint(1))
    else
      p(s:Noun_hint(1))
    end
    p(' рассматривает ', w:noun_hint('вн'), ' с озадаченным видом.')
    return
  end
  p('Алиса бросила ', w:noun_hint('вн'), ' на пол. Немедленно ')
  pr(s:noun_hint(1))
  if have(s) then
    p(', выскользнув из ее рук,')
  end
  move(w, _'Drawing_Room')
  move(s, _'Drawing_Room')
  pr(' бросился за ', w:noun_hint('тв'))
  if w == _'worsted' then
    _'worsted'.sputan = true
    s.state = WOOL_STATE
    pr(', мгновенно превратив его в дикую путаницу')
  else
    s.state = QUEEN_STATE
  end
  p('.')
end;
Kitten.before_Take = function(s, w, wh)
  if have(_(s.other_kitten)) then
    p("Двух котят сразу Алисе ни за что не удержать!")
    return
  end
  s.state = HELD_STATE
  move(s, me())
  p('Алиса взяла на руки ', s:noun_hint('вн'), '. Ну что за прелестное создание!')
end;
Kitten.after_Drop = function(s, w, wh)
  s.state = CHAIR_STATE
  move(s, _'Drawing_Room')
  p(s:Noun_hint(1), ', выскользнув из рук Алисы, убежал прочь.')
end;
Kitten.after_Transfer = function(s, w, wh)
  s.state = CHAIR_STATE
  local p = where(s)
  if p then
    pr(s:Noun_hint(1), ', спрыгнув с ', p:noun_hint('рд'))
  end
  move(s, _'Drawing_Room')
  p(', ловко приземлился на полу и убежал прочь.')
end;
Kitten.after_PutOn = function(s, w, wh)
  s.state = CHAIR_STATE
  local p = where(s)
  if p then
    pr(s:Noun_hint(1), ', спрыгнув с ', p:noun_hint('рд'))
  end
  move(s, _'Drawing_Room')
  p(', ловко приземлился на полу и убежал прочь.')
end;
Kitten.after_Insert = function(s, w, wh)
  s.state = CHAIR_STATE
  local p = where(s)
  if p then
    pr(s:Noun_hint(1), ', спрыгнув с ', p:noun_hint('рд'))
  end
  move(s, _'Drawing_Room')
  p(', ловко приземлился на полу и убежал прочь.')
end;
Kitten.daemon = function(s)
  s.seen = false
  s.this_kittens_turn = not s.this_kittens_turn
  if not s.this_kittens_turn or rnd(3) == 2 then
    return
  end
  p(s:Noun_hint(1))
  if s.state == HELD_STATE then
    local n = rnd(5)
    if n == 1 then
      p(' жалобно мяукнул.')
    elseif n == 2 then
      p(' тихо мурлыкнул.')
    elseif n == 3 then
      p(' удовлетворенно промурлыкал что-то.')
    elseif n == 4 then
      p(' потерся ушками о руку Алисы.')
    elseif n == 5 then
      move(s, _'Drawing_Room')
      s.state = CHAIR_STATE
      p(' спрыгнул на пол, ловко выскользнув из Алисиных рук.')
    end
    return
  elseif s.state == QUEEN_STATE then
    local n = rnd(5)
    if n == 1 then
      p(' ткнул Черную Королеву лапкой.')
    elseif n == 2 then
      p(' оставив на время игру, сидит с подчеркнуто невинным видом.')
    elseif n == 3 then
      p(' катает бедную Королеву туда-сюда по полу.')
    elseif n == 4 then
      p(' кончил умываться и осматривается по сторонам.')
    elseif n == 5 then
      p([[ взял Черную Королеву, укусил, и начал яростно трясти,
чтобы убедиться, что с ней покончено.]])
    end
    return
  elseif s.state == WOOL_STATE then
    _'worsted'.sputan = true
    local n = rnd(5)
    if n == 1 then
      p(' ткнул клубок шерсти лапкой.')
    elseif n == 2 then
      p(' покатил клубок по полу, преследуя его по пятам.')
    elseif n == 3 then
      p(' сцепился с клубком в жестокой схватке.')
    elseif n == 4 then
      p([[ прыгнул на клубок сверху,
и окончательно запутался в мешанине шерстяных нитей.]])
    elseif n == 5 then
      p(' прервав игру, чешет себя за ушами.')
    end
    return
  elseif s.state == CHAIR_STATE then
    if _(s.other_kitten).state == CHAIR_STATE and rnd(2) == 1 then
      local n = rnd(5)
      if n == 1 then
        p(' преследует ')
      elseif n == 2 then
        p(' прыгнул на ')
      elseif n == 3 then
        p(' умывает лапкой ')
      elseif n == 4 then
        p(' обежал вокруг ')
      elseif n == 5 then
        p(' ткнул ')
      end
      pr(_(s.other_kitten):noun_hint('вн'))
      if n == 2 then
        p(' и они вместе покатились по полу.')
      elseif n == 4 then
        p(' и бросился за ним.')
      elseif n == 5 then
        p(' лапкой.')
      else
        p('.')
      end
      return
    end
    local n = rnd(5)
    if n == 1 then
      p(' гоняет по полу комок пыли.')
    elseif n == 2 then
      p(' катается по полу.')
    elseif n == 3 then
      p(' сидит и тщательно вылизывает свой хвост.')
    elseif n == 4 then
      p(' трется головой о ножки кресла.')
    elseif n == 5 then
      p(' гоняется за своим хвостом.')
    end
  end
end

gameover {
  nam = "theend";
  title = "Конец";
  dsc = false;
}
