-- generated by mise.py; do not edit

--$Name:t$
require "fmt"
require "parser/mp-ru"

local function fn_is_lit(w)
  return w:has("light")
end

local function fn_mark(w)
  w:attr("seen")
end

local function fn_run(f)
  return f(_'box')
end

local function fn_each(t, f)
  for _, w in ipairs(t) do
    f(w)
  end
end

local function fn_total(n)
  local r = 0
  for i = 1, n do
    r = r + (i)
  end
  return r
end

obj {
  nam = "none";
}

Door = Class({
  from = 'none';
  to = 'none';
  door_to = function(s)
    if here() == _(s.from) then
      return _(s.to)
    end
    if here() == _(s.to) then
      return _(s.from)
    end
    return false
  end;
}, door):attr 'open'

Path = Class {
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(std.ref(s.walk_to)) then return end
    walk(s.walk_to)
  end;
  before_Default = function(s, ev, w, wh)
    if s.desc then p(s.desc) return end
    p([[Ты можешь пойти в ]], std.ref(s.walk_to):noun('вн'), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

Tree = Class {
}:attr 'scenery'

obj {
  -"коробка";
  nam = "box";
  Take = function(s, w, wh)
    if fn_run(fn_is_lit) then
      p([[светло]])
    end
    s:for_plural(fn_mark)
    fn_each(inv(), fn_mark)
    if fn_total(3) > 0 then
      return false
    end
  end;
}
