-- generated by mise.py; do not edit

--$Name:t$
require "fmt"
require "parser/mp-ru"

local function fn_mark(w)
  w:attr("seen")
end

obj {
  nam = "none";
}

Door = Class({
  from = 'none';
  to = 'none';
  door_to = function(s)
    if here() == _(s.from) then
      return _(s.to)
    end
    if here() == _(s.to) then
      return _(s.from)
    end
    return false
  end;
}, door):attr 'open'

Path = Class {
  walk_to = 'none';
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(_(s.walk_to)) then
      return
    end
    walk(_(s.walk_to))
  end;
  before_Default = function(s, ev, w, wh)
    local d = (s.desc)
    if d then
      p(d)
      return
    end
    p('Ты можешь пойти в ', _(s.walk_to):noun_hint("вн"), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

Tree = Class {
}:attr 'scenery'

Tree {
  -"дерево";
  nam = "tree";
}

_'tree'.before_Take = function(s, w, wh)
  s:for_plural(fn_mark)
  mp:trace(s, fn_mark)
  if ((((function(o) local m = getmetatable(s) while m do if m == o then return true end m = getmetatable(m) end return false end)(_G[("Tree")])))) then
    p([[дерево]])
  end
end;
