-- generated by mise.py; do not edit

--$Name:t$
require "fmt"
require "parser/mp-ru"

obj {
  nam = "none";
}

Door = Class({
  from = 'none';
  to = 'none';
  door_to = function(s)
    if here() == _(s.from) then
      return _(s.to)
    end
    if here() == _(s.to) then
      return _(s.from)
    end
    return false
  end;
}, door):attr 'open'

Path = Class {
  walk_to = 'none';
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(_(s.walk_to)) then
      return
    end
    walk(_(s.walk_to))
  end;
  before_Default = function(s, ev, w, wh)
    local d = (s.desc)
    if d then
      p(d)
      return
    end
    p('Ты можешь пойти в ', _(s.walk_to):noun_hint("вн"), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

mp.before_Any = function(s, ev, w, wh)
  if ev == 'Walk' and w:has("door") then
    p([[дверь]])
  end
end
mp.Any = function(s, ev, w, wh)
  if ev == 'Exam' and w:has("scenery") then
    p([[осмотр декорации]])
  elseif ev == 'Wear' then
    p([[надели]])
  end
end

mp.Default = function(s, ev, w, wh)
  p([[нет обработчика]])
end
