-- generated by mise.py; do not edit

--$Name:t$
require "fmt"
require "parser/mp-ru"

obj {
  nam = "none";
}

Door = Class({
  from = 'none';
  to = 'none';
  door_to = function(s)
    if here() == _(s.from) then
      return _(s.to)
    end
    if here() == _(s.to) then
      return _(s.from)
    end
    return false
  end;
}, door):attr 'open'

Path = Class {
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(std.ref(s.walk_to)) then return end
    walk(s.walk_to)
  end;
  before_Default = function(s, ev, w, wh)
    if s.desc then p(s.desc) return end
    p([[Ты можешь пойти в ]], std.ref(s.walk_to):noun('вн'), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

Bird = Class {
  before_Climb = function(s, w, wh)
    p([[взлетел]])
  end;
}:attr 'animate'

Bird {
  -"орёл";
  nam = "eagle";
}

obj {
  -"попугай";
  nam = "parrot";
  heard = false;
  before_Talk = function(s, w, wh)
    s.heard = true
    p([[поговорили]])
  end;
}

obj {
  -"ворона";
  nam = "crow";
  heard = false;
  before_Talk = function(s, w, wh)
    p([[кар]])
  end;
}
