-- generated by mise.py; do not edit

--$Name:t$
require "fmt"
require "parser/mp-ru"

local function fn_label(w, n, nn)
  if n and nn then
    return w:noun_hint(n, nn)
  end
  if n then
    return w:noun_hint(n)
  end
  return w:noun_hint()
end

local function fn_label2(w, n)
  return w:noun_hint(n)
end

local function fn_first_str(t)
  return t[1]
end

local function fn_on_take(s)
  if s.weight + 1 > 0 then
    p([[тяжёлый]])
  end
  p(fn_label(s))
  p(fn_label(s, "им"))
  p(fn_label(s, "вн"))
  p(s:noun_hint("вн"))
  p(s:noun_hint("зв"))
  p(s:noun_hint(({ "рд", 2 })))
  p(s:noun_hint(({ "рд", 2 })))
  p(s:noun_hint("им"))
  p(s:noun_hint(({ "вн", 2 })))
  p(s:noun_hint(({ "пр", "мн" })))
  p(s:noun_hint(({ "тв", 2 })))
  p(s:noun_hint(({})))
  p(s:Noun_hint(({ "рд", 2 }), 1))
  p(fn_first_str(({ [[a]], [[b]] })))
  local h = ({ "вн", "мн" })
  p(s:noun_hint(h))
  local w = inv()[1]
  w:noun_hint()
  p(fn_label2(s, 2))
  fn_label(s, 1, 2)
end

obj {
  nam = "none";
}

Door = Class({
  from = 'none';
  to = 'none';
  door_to = function(s)
    if here() == _(s.from) then
      return _(s.to)
    end
    if here() == _(s.to) then
      return _(s.from)
    end
    return false
  end;
}, door):attr 'open'

Path = Class {
  walk_to = 'none';
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(_(s.walk_to)) then
      return
    end
    walk(_(s.walk_to))
  end;
  before_Default = function(s, ev, w, wh)
    local d = (s.desc)
    if d then
      p(d)
      return
    end
    p('Ты можешь пойти в ', _(s.walk_to):noun_hint("вн"), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

Box = Class {
  weight = 0;
}:attr 'container'

Box {
  -"ящик";
  nam = "crate";
}

_'crate'.before_Take = fn_on_take;
