-- generated by mise.py; do not edit

--$Name:t$
require "fmt"
require "parser/mp-ru"

local function fn_on_take(s)
  if s.weight + 1 > 0 then
    p([[тяжёлый]])
  end
end

obj {
  nam = "none";
}

Door = Class({
  from = 'none';
  to = 'none';
  door_to = function(s)
    if here() == _(s.from) then
      return _(s.to)
    end
    if here() == _(s.to) then
      return _(s.from)
    end
    return false
  end;
}, door):attr 'open'

Path = Class {
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(std.ref(s.walk_to)) then return end
    walk(s.walk_to)
  end;
  before_Default = function(s, ev, w, wh)
    if s.desc then p(s.desc) return end
    p([[Ты можешь пойти в ]], std.ref(s.walk_to):noun('вн'), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

Box = Class {
  weight = 0;
}:attr 'container'

Box {
  -"ящик";
  nam = "crate";
}

_'crate'.before_Take = fn_on_take;
