-- generated by mise.py; do not edit

--$Name:t$
require "fmt"
require "parser/mp-ru"

local function fn_label(w, n, nn)
  if n and nn then
    return w:noun(n, nn)
  end
  if n then
    return w:noun(n)
  end
  return w:noun()
end

local function fn_label2(w, n)
  return w:noun(n)
end

local function fn_on_take(s)
  if s.weight + 1 > 0 then
    p([[тяжёлый]])
  end
  p(fn_label(s))
  p(fn_label(s, 'им'))
  p(fn_label(s, "вн"))
  p(s:noun("вн"))
  p(s:noun('рд,2'))
  p(s:noun('вн,мн'))
  p(fn_label2(s, 2))
  fn_label(s, 1, 2)
end

obj {
  nam = "none";
}

Door = Class({
  from = 'none';
  to = 'none';
  door_to = function(s)
    if here() == _(s.from) then
      return _(s.to)
    end
    if here() == _(s.to) then
      return _(s.from)
    end
    return false
  end;
}, door):attr 'open'

Path = Class {
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(std.ref(s.walk_to)) then return end
    walk(s.walk_to)
  end;
  before_Default = function(s, ev, w, wh)
    if s.desc then p(s.desc) return end
    p([[Ты можешь пойти в ]], std.ref(s.walk_to):noun('вн'), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

Box = Class {
  weight = 0;
}:attr 'container'

Box {
  -"ящик";
  nam = "crate";
}

_'crate'.before_Take = fn_on_take;
