-- generated by mise.py; do not edit

--$Name:kinds$
require "fmt"
require "parser/mp-ru"

obj {
  nam = "none";
}

Door = Class({
  from = 'none';
  to = 'none';
  door_to = function(s)
    if here() == _(s.from) then
      return _(s.to)
    end
    if here() == _(s.to) then
      return _(s.from)
    end
    return false
  end;
}, door):attr 'open'

Path = Class {
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(std.ref(s.walk_to)) then return end
    walk(s.walk_to)
  end;
  before_Default = function(s, ev, w, wh)
    if s.desc then p(s.desc) return end
    p([[Ты можешь пойти в ]], std.ref(s.walk_to):noun('вн'), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

fmt.verbose = true
game.hint_verbs = { "#Look" }
pl.word = -"ты"
function start(load)
  move(me(), _'hall')
end
function init()
  take('statue')
end

cutscene {
  nam = "intro";
  dsc = "Пролог.";
  after_Enter = function(s, w, wh)
    p([[История началась.]])
  end;
}

obj {
  -"небо";
  nam = "sky";
  dsc = "Небо в облаках.";
}:attr 'scenery'

room {
  -"зал";
  nam = "hall";
  dsc = "Большой зал.";
  Enter = function(s, w, wh)
    p([[Вы вошли.]])
  end;
  Walk = function(s, w, wh)
    p([[Вы идёте.]])
  end;
  Look = function(s, w, wh)
    p([[Вы осматриваетесь.]])
  end;
  post_Look = function(s, w, wh)
    p([[Уже осмотрелись.]])
  end;
  ["life_Give,Show"] = function(s, w, wh)
    p([[Жизнь кипит.]])
  end;
  after_Turn = function(s, w, wh)
    p([[Повернулись.]])
  end;
  s_to = 'garden';
  obj = {
    'sky';
  };
}:dict { "зал" }

door {
  -"ворота";
  nam = "gate";
  d_to = 'hall';
  n_to = 'garden';
}

room {
  -"сад";
  nam = "garden";
  dsc = "Тихий сад.";
  home_to = 'hall';
}

obj {
  -"статуя";
  nam = "statue";
  mood = "calm";
}:attr 'scenery'

obj {
  -"реликвия";
  nam = "relic";
  mood = "tired";
}:disable()

Verb { "#Probe", "пробовать", "{noun}/вн : Probe", prio = 10, hint = function(s)
  p([[Подсказка.]])
end }
