-- generated by mise.py; do not edit

--$Name:Метель$
--$Version:2.1$
--$Author:Peter Kosyh & Pakowacz$
--$Info:Что тебя ждёт за снежной пеленой?$
require "fmt"
fmt.dash = true
fmt.quotes = true
require "parser/mp-ru"

local function fn_event()
  return mp.event
end

local function fn_call_before(s, ev)
  s['before_' .. ev](s)
end

local function fn_arg_word(i)
  return mp.args[i] and mp.args[i].word or ''
end

local function fn_tiny()
  return instead.tiny
end

local function fn_set_help(mobile)
  mp.togglehelp = mobile
  mp.autohelp = mobile
  mp.autohelp_limit = mobile and 1000 or 8
  mp.compl_thresh = mobile and 0 or 1
end

local function fn_tbl1()
  return { "Машину потряхивает на снежных ухабах."; "По другую сторону окна кружатся снежинки."; "Вы проезжаете мимо занесённых снегом коттеджей."; "Машину слегка заносит на снежной дороге."; }
end

local function fn_tbl2()
  return { "-- Ты не собираешься со мной поговорить?"; "-- Почему ты молчишь?"; "-- Давай поговорим?"; "-- Ну, чего ты молчишь?"; }
end

local function fn_tbl3()
  return { "Ты делаешь пару неудачных фоток и удаляешь их из телефона."; "Ты сделала удачную фотку."; "Ты сделала пару фоток и селфи."; }
end

local function fn_tbl4()
  return { "-- Иди ко мне скорее, моё дитя!", "-- Что же ты медлишь? Обними и поцелуй свою мать!", "-- Я так долго тебя ждала!", "-- Теперь всё будет хорошо, я буду любить тебя всегда!", "-- Мы будем вместе!", }
end

local function fn_tbl5()
  return { "Ты чувствуешь на своём лице дуновение холодного ветра."; "Рой маленьких колких снежинок ударяется в щёки."; "Снежинки снова и снова ударяются о твоё лицо."; "Небольшая метель метёт тебе прямо в глаза."; }
end

local function fn_tbl6()
  return { "Небольшая комната. В ней ты видишь мужчину и женщину. У обоих раздражение на лице. В комнате ты видишь детскую кроватку."; "Ванная комната. Мужчина лет 40 бреется. Уголки губ опущены вниз."; "Помещение, напоминающее школьный класс. Сейчас он пуст. Только молодая учительница сидит за столом. Рядом с ней -- стопка тетрадей."; "Большой зал торгового центра. Ты видишь магазин с одеждой, заполненный посетителями."; "Аптека. Полки с лекарствами. Ты видишь провизора в белом халате. Это пожилая женщина."; "Спортивный зал. Натянута сетка. Дети играют в волейбол."; "Танцевальный зал. Много молодых людей и девушка - инструктор."; "Тёмная комната завалена хламом и пустыми бутылками. На диване лежит мужчина."; "За поверхностью зеркала -- темнота."; "Салон легковой машины. На заднем сидении сидит мальчик с грустными глазами."; "Мужской туалет. Все писсуары свободны."; }
end

local function fn_tbl7()
  return { "-- Дрянь! -- шипит Снежная Королева."; "Снежная Королева стонет."; "-- Я до тебя доберусь! -- произносит Снежная Королева."; }
end

local function fn_have_compass()
  return have(_'телефон') and _'телефон'.compass
end

local function fn_check_compass(w)
  if w == 'u_to' or w == 'd_to' or w == 'in_to' or w == 'out_to' then
    return false
  end
  if not fn_have_compass() then
    p("Чтобы ориентироваться в пространстве, тебе нужен компас.")
    return true
  end
  return false
end

local function fn_forest_scenery(s)
  disable(_'сова')
  disable(_'олень')
  disable(_'#ручей')
  disable(_'#поляна')
  if s.depth == 0 then
    enable(_'сова')
  elseif s.depth == 2 then
    enable(_'#ручей')
  elseif s.depth == 3 then
    enable(_'#поляна')
    enable(_'олень')
    pic_set('22')
    _'олень'.step = 0
    _'олень'.sit = false
    DaemonStart(_'олень')
  end
end

Path = Class {
  ["before_Walk,Enter"] = function(s, w, wh)
    if mp:check_inside(std.ref(s.walk_to)) then return end
    walk(s.walk_to)
  end;
  before_Default = function(s, ev, w)
    if s.desc then p(s.desc) return end
    p([[Ты можешь пойти в ]], std.ref(s.walk_to):noun('вн'), '.')
  end;
  default_Event = "Walk";
}:attr 'scenery,enterable'

global 'blizzard' (0)

function pic_push(name)
end

function pic_pop()
end

function pic_set(name)
end

include "pic"
--"фонарик,фонарь"
--"сообщения|сообщение"

cutscene {
  nam = "intro";
  text = [[Старенький синий седан едет по заснеженной трассе. Внутри машины -- двое.^^
		Ведёт машину усталая женщина лет 35. На заднем сидении справа сидит её дочь -- девочка-подросток.^^
		Девочка прислонилась лбом к холодному стеклу. Мать продолжает начатый разговор...^^
		-- Вот увидишь, тебе там понравится.]];
  enter = function(s)
    pic_set('1')
  end;
  next_to = 'В_машине';
}

obj {
  -"браслет";
  nam = "браслет";
  after_Wear = "Надев браслет на правое запястье, ты чувствуешь, что на душе у тебя потеплело.";
  before_Disrobe = function(s, w, wh)
    if visited(_'gotmirror') then
      p("Тебе кажется, что в этом странном месте лучше никогда не снимать этот браслет!")
    else
      return false
    end
  end;
  before_Exam = function(s, w, wh)
    p("Этот детский браслет мама подарила тебе на Рождество, когда тебе было ещё 9 лет.\nПросто игрушка. Леска, на которую нанизаны бусинки и пластмассовое сердечко.")
    if s:once() then
      p("Странно, что он оказался в бардачке... Ты думала, что он давно потерялся.")
    end
  end;
  before_Give = function(s, w, wh)
    if w == _'королева' then
      walk(_'badend4')
      return
    end
    return false
  end;
}:attr 'clothing'

Title = Class({
  OnError = function(s)
    mp:clear()
    std.pclr()
  end;
  title = false;
  before_Default = function(s, ev, w)
    if ev == 'Next' then
      return false
    end
    mp:clear()
    me():need_scene(true)
  end;
}, cutscene):attr 'noprompt'

Prop = Class {
  before_Default = function(s, ev, w)
    p("Тебе нет дела до ", s:noun('рд'), ".")
  end;
}:attr 'scenery'

Useless = Class {
  before_Default = function(s, ev, w)
    p("Тебе нет дела до ", s:noun('рд'), ".")
  end;
}

room {
  -"машина";
  nam = "В_машине";
  before_Cry = function(s, w, wh)
    if fn_seen('#мама') then
      p("-- Прекрати истерику! -- произносит мать.")
    else
      return false
    end
  end;
  daemon = function(s)
    local t = fn_tbl1()
    if blizzard >= 2 then
      blizzard = blizzard + 1
      if blizzard < 7 and blizzard > 3 then
        pic_set('2-pan-left')
      end
      if blizzard > 5 then
        enable(_'#заправка')
        disable(_'#метель')
        if blizzard == 7 then
          p("Мать заглушила двигатель.")
          return
        end
        if blizzard == 8 then
          pic_set('7')
          p("-- Подожди меня, я скоро вернусь. -- говорит тебе мать и выходит из машины, захлопывая за собой дверь.")
          remove(_'#мама')
          return
        end
        if blizzard == 11 then
          p("Ты ждёшь мать, но её все нет. Может быть, выйти из машины?")
          return
        end
        if blizzard > 8 then
          return
        end
        p("Вы подъезжаете к заправке.")
        return
      end
    end
    if here() == s and fn_rnd(100) <= 25 then
      pn(t[fn_rnd(#t)])
    end
  end;
  dsc = "Ты сидишь на заднем сидении машины и смотришь в окно.";
  enter = function(s)
    DaemonStart(s)
    DaemonStart(_'#мама')
  end;
  exit = function(s)
    if fn_seen('#мама') then
      DaemonStop(_'#мама')
    end
  end;
  out_to = function(s)
    if blizzard < 7 then
      p("Лучше не делать этого, пока машина движется.")
    elseif fn_seen('#мама') then
      p("Там холодно.")
    else
      DaemonStop(s)
      if not have(_'скрипка') then
        move(_'скрипка', _'машина')
      end
      if not have(_'телефон') then
        move(_'телефон', _'бардачок')
      end
      walk(_'метель1')
    end
  end;
  before_Listen = function(s, w, wh)
    if fn_seen('#мама') then
      p("Ты слышишь шум мотора и музыку, доносящуюся из радио.")
    else
      p("В машине играет радио.")
    end
  end;
  obj = {
    'скрипка';

    obj {
      -"мать,мама,женщина";
      nam = "#мама";
      daemon = function(s)
        local t = fn_tbl2()
        s.time = s.time + 1
        if s.time > 3 then
          if fn_rnd(3) == 1 then
            p(t[fn_rnd(#t)])
            p("-- обращается к тебе мать.")
          end
        end
      end;
      init_dsc = "Машину ведёт твоя мать.";
      time = 0;
      ["before_Ask,Tell,Talk"] = function(s, w, wh)
        if visited(_'разговор1') then
          if _'телефон'.seen and have(_'телефон') then
            p("-- Я не буду с тобой разговаривать, пока ты не отдашь мне телефон! Ну же!")
            return
          end
          if blizzard > 0 then
            if blizzard >= 2 then
              p("-- Мама! Это важно!^")
              if not disabled(_'#заправка') then
                p("-- Сейчас заправимся и поговорим.")
              else
                p("-- Скоро заправка, подожди пять минут и поговорим!")
              end
              return
            end
            p("-- Мама! Посмотри, там справа. Что то странное...^")
            p("-- Не отвлекай меня от дороги!")
            pic_set('6')
            blizzard = 2
            return
          end
          p("Ты не решаешься поговорить с ней.")
          return
        end
        walk(_'разговор1')
      end;
      before_Exam = "Твоя мать очень много работает и поэтому выглядит усталой.";
      before_Kiss = "Ты зла на свою мать и сейчас ваши отношения нельзя назвать близкими.";
    }:attr 'animate';

    Prop {
      -"бардачок";
      before_Exam = function(s, w, wh)
        if _'телефон':inside(_'бардачок') then
          p("Бардачок закрыт.")
          return
        end
        p("Тебе нет до него дела.")
      end;
      before_Open = "Ты не можешь дотянуться до него с заднего сидения.";
    };

    Prop {
      -"дверь";
      before_Close = "Дверь закрыта.";
      before_Enter = function(s, w, wh)
        fn_xaction('Exit')
      end;
      before_Open = function(s, w, wh)
        fn_xaction('Exit')
      end;
    };

    Prop {
      -"руль|радио";
    };

    obj {
      -"метель,буря|смерч|клубы";
      nam = "#метель";
      before_Default = "Она пока ещё далеко.";
      before_Exam = "Буря, метель или ... смерч? Что бы это ни было, оно пугает тебя.";
    }:attr 'scenery':disable();

    obj {
      -"окно,стекло";
      nam = "#окно";
      before_Open = "Слишком холодно, чтобы опускать стекло.";
      ["before_Search,Exam"] = function(s, w, wh)
        if not disabled(_'#заправка') then
          p("За стеклом ты видишь смутный силуэт заправки.")
          return
        end
        if visited(_'разговор1') and _'телефон'.seen then
          if blizzard == 0 then
            pn("Разглядывая белоснежный пейзаж, ты замечаешь вдали нечто странное.")
            enable(_'#метель')
            blizzard = 1
            pic_set('5')
          end
          pn("Ты видишь, как по земле ползут огромные клубы пара или снега.")
          p("Огромная снежная буря, накрывая деревья, движется к трассе!")
          return
        end
        p("Ты видишь, как за стеклом кружится метель.")
        if s:once() then
          pic_set('2-pan-left')
        end
      end;
    }:attr 'scenery,openable';

    Prop {
      -"заправка";
      nam = "#заправка";
      before_Exam = "Сквозь метель ты едва различаешь темные очертания заправки.";
    }:disable();
  };
}

dlg {
  nam = 'разговор1';
  title = false;
  enter = function(s)
    pic_set('3')
  end;
  phr = {
    "-- Я говорю, тебе там понравится. Там хорошая школа, я узнавала... И музыкальная школа совсем недалеко. -- ты слышишь в голосе матери настойчивость.";
    {
      "Я устала терять друзей.";
      "-- Ты же знаешь, что это необходимо! Я должна работать, чтобы ты смогла учиться в хорошем вузе! И это не конец света! На новом месте заведёшь новых друзей.";
      next = '#дальше';
    };
    {
      "Хорошо, мама...";
      "-- Ну что ты вечно строишь из себя мученика? Ты всего-лишь меняешь школу. Я работаю на твоё будущее и никакой благодарности!";
      next = '#дальше';
    };
  };
  obj = {
    {
      '#дальше';
      {
        "Я заранее знаю всё, что ты скажешь!";
        "-- Ну зачем ты так? Ты стала такой грубой!";
      };
      {
        "Ты меня не поймёшь.";
        "-- А тебе не приходило в голову, что мне тоже было 13 лет?";
      };
      {
        "Просто мне очень плохо.";
        "-- Ты ведёшь себя как эгоистичный ребёнок. Ты думаешь мне легко?";
        {
          "Я ненавижу твою работу!";
          "-- Ты неблагодарная! Вместо поддержки, ты снова треплешь мне нервы!";
          {
            "Я устала от твоих скандалов. Замолчи!";
            "-- Ты это матери говоришь? Таким тоном? Как ты... можешь!";
          };
          {
            "Давай просто закончим этот разговор.";
            "-- Ты жестокая! Я отдала тебе все! И это моя самая большая ошибка!";
            {
              "Мама, прекрати!";
              function(s)
                p("-- Да, не ожидала я... Что у меня такая дочь...")
                if have(_'телефон') then
                  DaemonStart(_'телефон')
                end
                walkback()
              end;
            };
          };
        };
        {
          "Ты могла бы сменить работу...";
          "-- Да? И получать гроши. И кто оплатит твоё обучение?";
        };
      };
    };
  };
}

obj {
  nam = "телефон";
  word = function(s)
    pr("мобильный телефон,телефон,мобильник,смартфон")
    if s.flash then
      pr("|фонарик,фонарь")
    end
    if have(s) and here() == _'В_машине' then
      pr("|сообщения|сообщение")
    end
  end;
  ["before_Burn,Light"] = function(s, w, wh)
    s.flash = true
    if s:has("light") then
      p("Фонарик в телефоне и так включён.")
      return
    end
    if not fn_thedark(here()) then
      p("Тут и так светло.")
      return
    end
    p("Ты включила в мобильнике фонарик.")
    me():need_scene(true)
    s:attr("light")
  end;
  compass = false;
  daemon = function(s)
    if fn_rnd(10) > 3 then
      p("Ты слышишь сигнал входящего сообщения на своём смартфоне.")
    end
  end;
  each_turn = function(s)
    if here() == _'пещера2' and s:has("light") and not here().solved then
      p("В ту же секунду ты слышишь хлопанье крыльев и успеваешь заметить,\nкак множество чёрных теней бросаются к тебе с потолка. Инстинктивно ты успеваешь выключить фонарик. Удивительно, но это успокаивает тварей. Некоторое время ты слышишь шум их крыльев. Затем всё затихает.")
      s:attr("~light")
      return
    end
    if here():has("light") and s:has("light") then
      p("В целях экономии заряда ты выключила фонарик.")
      s:attr("~light")
    end
  end;
  flash = false;
  seen = false;
  before_Exam = function(s, w, wh)
    if not s:has("on") then
      p("Телефон выключен.")
      return
    end
    if s:has("light") then
      p("В телефоне включён фонарик.")
      return
    end
    if fn_seen('#мама') then
      p("Ты собираешься проверить новые сообщения, но\nтвоя мать замечает это в зеркале заднего вида.^\n-- Ты круглые сутки сидишь с телефоном! Отдай его мне, сейчас же!")
      s.seen = true
      DaemonStop(s)
    else
      if not s.flash and fn_thedark(here()) then
        p("Тебе приходит в голову мысль, что можно посветить телефоном...")
        s.flash = true
        return
      end
      if not s.compass then
        p("Странно, нет приёма...")
      end
      if here() == _'поле' or here() == _'В_лесу' then
        if not s.compass then
          p("Но в твоём смартфоне есть компас. И, похоже, он работает! Теперь ты можешь ориентироваться по сторонам света.")
          s.compass = true
        else
          p("Здорово, что в твоём смарфоне есть компас! В целях экономии батареи ты включаешь режим \"в полёте\".")
        end
      else
        p("Это твой старенький китайский смартфон. В основном, ты используешь его для социальных сетей.")
        p("А сейчас он служит тебе компасом.")
        if s.flash then
          p("И фонариком.")
        end
      end
    end
  end;
  before_Give = function(s, w, wh)
    if w == _'#мама' then
      p("Ты протягиваешь телефон матери, она молча забирает его и кладёт в бардачок.")
      if not s.seen then
        s.seen = true
        DaemonStop(s)
        p("^Мать выглядит немного удивлённой -- ведь ты обычно тяжело расстаёшься со своим смартфоном.")
      end
      move(s, _'бардачок')
      pic_set('4')
      return
    end
    return false
  end;
  before_SwitchOff = function(s, w, wh)
    if s:has("light") then
      p("Ты выключила фонарик в телефоне.")
      s:attr("~light")
      me():need_scene(true)
      return
    end
    if s:multi_alias() == 2 then
      p("Фонарик и так выключен.")
      return
    end
    if s.compass then
      p("Если ты выключишь телефон, ты лишишься компаса.")
      return
    end
    if not s.seen then
      p("Ты не любишь, когда твой смартфон выключен.")
      return
    end
    return false
  end;
  before_SwitchOn = function(s, w, wh)
    if s:multi_alias() == 2 then
      fn_call_before(s, 'Light')
      return
    end
    if not s.flash and fn_thedark(here()) then
      p("Тебе приходит в голову мысль, что в телефоне есть фонарик и его можно включить...")
      s.flash = true
      return
    end
    return false
  end;
}:attr 'switchable,on,multi'

obj {
  -"скрипка";
  nam = "скрипка";
  after_Play = "У тебя сейчас нет настроения играть.";
  init_dsc = "Рядом лежит скрипка.";
  before_Exam = "Твоя скрипка. Тебе остался год, чтобы закончить музыкальную школу. Если честно, благодаря музыкальной школе ты стала ненавидеть музыку.";
}

Verb { '#Attack2', "[|раз]бить,[|раз]бей", "{noun}/вн,scene : Attack" }

Verb { '#PutOn', "повес/ить", "{noun}/вн,held на {noun}/вн,scene : PutOn", "~ на {noun}/вн,scene {noun}/вн,held : PutOn reverse" }

Verb { '#Play', "играть,сыграть", "на {noun}/пр : Play", " : Play" }
mp.Play = function(s, w, wh)
  if not w then
    fn_xaction('Play', _'скрипка')
    return
  end
  if w ~= _'скрипка' then
    p("Ты умеешь играть только на скрипке.")
    return
  end
  if not have(_'скрипка') then
    p("Сначала тебе нужно взять скрипку в руки.")
    return
  end
  return false
end

Verb { '#Light', "[|по|под]свети/ть,[|по|свеч/у,освети/ть", "{noun}/тв,held : Light", hint = function(s)
  return fn_thedark(here()) and have(_'телефон')
end }
mp.Light = function(s, w, wh)
  if mp:check_held(w) then
    return
  end
  p("{#First} не {#if_hint/#first,plural,могут,может} светить.")
end

Verb { '#Cry', "[|по|за]крич/ать,[|по]звать,крикн/уть,[|за|по]плак/ать,[|за|по]плач/ь", ": Cry" }

Verb { '#Fun', "[|по|рас|за]смеяться,[|по|за|рас]смей/ся,[|по|за|рас]смею/сь,[|по|за|рас]хохо/таться", ": Fun" }

Verb { '#Knock', "[|по]стуч/ать", "в {noun}/вн : Knock", "по {noun}/дт : Knock" }
mp.Knock = function(s, w, wh)
  if mp:check_live(w) then
    return
  end
  if fn_arg_word(1) == 'в' then
    p("Ты постучала в")
    p(w:noun('вн'), ".")
  else
    p("Ты постучала по")
    p(w:noun('дт'), ".")
  end
  p("Ничего не произошло.")
end

Verb { '#Tune', "настро/ить,настра/ивать", "{noun}/вн : Tune" }
mp.Tune = function(s, w, wh)
  p("Тебе не нужно настраивать ", w:noun('вн'), ".")
end

Verb { '#Photo', "[|с|по]фото/графировать", "Photo" }
mp.Photo = function(s, w, wh)
  if not have(_'телефон') then
    p("Дебе нечем делать снимки.")
  elseif fn_thedark(here()) then
    p("Нет света. Может быть, посветить телефоном?")
  else
    local t = fn_tbl3()
    p(t[fn_rnd(#t)])
  end
end

game.dsc = false
pl.word = -"ты/жр,2л"
pl.description = "Тебя зовут Вера. Тебе почти 13 лет."
pl.before_LetGo = function(s, w, ww)
  if w == _'телефон' then
    local s = w
    if s.compass and ww ~= me() then
      p("В телефоне есть компас, который тебе нужен.")
      return
    end
    return false
  elseif w == _'скрипка' and here() == _'пещера2' and fn_thedark(here()) then
    p("Ты не хочешь расставаться со своей скрипкой.")
    return
  elseif w == _'осколки' then
    local s = w
    if not (here() == _'пещера2') then
      return false
    end
    p("Ты бросаешь осколки кристалла на пол пещеры. Маленькие светящиеся огоньки рассыпаются по ледяной поверхности. В тот же момент, пещеру заполняет шум хлопающих крыльев.")
    here().solved = true
    drop(s)
    return
  end
  return false
end;
function start(load)
  if not load then
    move(me(), _'intro')
  end
end
game.hint_verbs = {"#Exam","#Drop","#LookIn","#ThrowAt","#Walk","#Take","#Play","#Give","#Touch","#Attack2","#Talk","#Cry","#Open","#Close","#Jump","#Wait","#Wear","#Sit","#Exit","#SwitchOn","#SwitchOff","#PutOn","#Light"}
function init()
  take('телефон')
  if fn_theme_name() == '.mobile' or fn_theme_name() == '.mobile2' then
    fn_set_help(true)
  else
    fn_set_help(false)
  end
end

cutscene {
  nam = "метель1";
  text = [[Ты открываешь дверь и толкаешь её наружу.^^
		Ты чувствуешь, как ветер давит на дверь с другой стороны, но ты сильней и вот -- дверь открыта.^^
		Холод, вместе с вихрем злых снежинок, быстро забирается внутрь салона.^^
		Ты выходишь из машины когда...^^
		На тебя обрушивается...]];
  enter = function(s)
    pic_set('75')
    if std.ref('mplayer') then
      fn_lifeon(fn_ref('mplayer'))
    end
  end;
  exit = function(s)
    pic_set('81')
  end;
  next_to = 'метель2';
  title = false;
}

Title {
  nam = "метель2";
  text = [[{$fmt y,50%}{$fmt c|{$fmt b|МЕТЕЛЬ}}^^
{$fmt c|Игра на ЗОК-2019}^^^
{$fmt em|{$fmt c|Код: Пётр Косых^Графика: Pakowacz}}]];
  exit = function(s)
    pic_set('20-pan')
  end;
  next_to = 'поле';
}

obj {
  -"машина|дверь";
  nam = "машина";
  description = function(s)
    if s:multi_alias() == 2 then
      p("Тебе нет дела до двери.")
      return
    end
    return false
  end;
  dsc = function(s)
    p("В снегу стоит машина.")
    if where(_'перо') == s and _'перо':hasnt("moved") then
      _'перо':init_dsc()
    end
  end;
  inside_dsc = "Ты находишься в машине.";
  after_Close = function(s, w, wh)
    if _'перо':inside(s) and not have(_'перо') then
      p("Когда ты захлопнула дверь машины, перо упало с крыши в снег.")
      move(_'перо', _'поле')
      return
    end
    return false
  end;
  before_SwitchOff = "Двигатель не работает.";
  before_SwitchOn = "Тебе не удаётся завести машину. Впрочем, ты все-равно не умеешь водить.";
  obj = {
    obj {
      -"радио";
      nam = "радио";
      ["before_Turn,Tune"] = function(s, w, wh)
        if s:hasnt("on") then
          p("Радио выключено.")
          return
        end
        p("Ты пытаешься поймать какую-нибудь волну, но на всех частотах только шум помех.")
      end;
      when_off = false;
      when_on = "Радио в машине издаёт помехи.";
      after_SwitchOn = "Ты включаешь радио. Шум помех нарушает тишину.";
    }:attr 'static,switchable,on';

    obj {
      -"бардачок|перчаточный ящик";
      nam = "бардачок";
      when_closed = "Твоё внимание привлекает бардачок.";
      when_open = "Бардачок открыт.";
      before_Exam = function(s, w, wh)
        if s:hasnt("open") then
          p("Бардачок закрыт.")
          return
        end
        return false
      end;
      obj = {
        'браслет';
      };
    }:attr 'static,openable,container';
  };
}:attr 'container,openable,open,static,enterable,light'

Area = Class({
  cant_go = function(s, w)
    if fn_check_compass(w) then
      return
    end
    return false
  end;
  compass_look = function(s, w)
    if fn_check_compass(w) then
      return
    end
    if w == 'u_to' then
      fn_xaction('Exam', _'#небо')
      return
    end
    if w == 'd_to' then
      fn_xaction('Exam', _'#снег')
      return
    end
    return false
  end;
}, room)

Snow = Class {
  -"снег";
  after_Receive = function(s, w, wh)
    move(w, here())
    return false
  end;
  ["before_Enter,Walk"] = "Ты и так стоишь среди снега.";
  before_Receive = function(s, w, wh)
    if here() == _'В_лесу' then
      p("Потом ", w:noun('вн'), " сложно будет найти.")
    else
      return false
    end
  end;
  before_Take = "Тебе не хочется играть в снежки.";
}:attr 'scenery,supporter'

Sky = Class {
  -"небо|облака";
  before_Default = "Небо далеко...";
  before_Exam = "Бледное небо нависло над головой. Солнца не видно.";
}:attr 'scenery'

Area {
  -"поле";
  nam = "поле";
  before_Cry = "-- Ма-маааааа! -- нет ответа.";
  dsc = function(s)
    p("Ты стоишь в заснеженном поле.")
    if fn_have_compass() then
      p("На западе начинается хвойный лес.")
    else
      p("Неподалёку начинается хвойный лес.")
    end
  end;
  ["n_to,ne_to,e_to,se_to,s_to"] = function(s)
    if fn_event() == 'Exam' then
      return false
    end
    if fn_check_compass('w_to') then
      return
    end
    p([["Ты идешь некоторое время на ", (_('@'..t).word), "."]])
    p("Ничего не меняется. Вокруг все-такой же пустынный пейзаж. Ты решаешь вернуться к машине.")
  end;
  onenter = function(s, f)
    if visited(s) then
      return
    end
    p("Холод. Ты лежишь в снегу и медленно приходишь в себя.^\nНекоторое время ты смотришь в небо. Затем поднимаешься на ноги и оглядываешься.^\nСтранно, но ты не видишь никакой заправки. Впрочем, и трассы тоже.")
  end;
  out_to = function(s)
    p("Сначала нужно решить, куда тебе идти.")
  end;
  ["w_to,nw_to,sw_to"] = function(s)
    if fn_check_compass('w_to') then
      return
    end
    return _'#лес'
  end;
  before_Listen = function(s, w, wh)
    if _'радио':hasnt("on") then
      p("Стоит звенящая тишина.")
    else
      p("Ты слышишь шум радиопомех из машины.")
    end
  end;
  before_Walk = function(s, w, wh)
    if where(me()) == _'машина' then
      p("Машина не заводится. Придётся выйти и идти пешком.")
      return
    end
    return false
  end;
  obj = {
    'машина';

    Sky {
      nam = "#небо";
    };

    Snow {
      nam = "#снег";
      before_Exam = function(s, w, wh)
        p("Ты видишь запорошенные снегом следы, которые ведут в лес.")
        enable(_'#следы')
      end;
    };

    obj {
      -"хвойный лес,лес|чаща|деревья";
      nam = "#лес";
      before_Default = "Лес далеко.";
      before_Exam = "На деревьях лежит снег.";
      ["before_Walk,Enter,Climb"] = function(s, w, wh)
        walk(_'В_лесу')
      end;
    }:attr 'scenery';

    obj {
      nam = "#следы";
      before_Exam = "Следы уже почти скрылись под свежим снегом.";
    }:attr 'scenery';

    Prop {
      -"колёса|колесо|двери";
    };
  };
}

game:dict {
  ["деревья/мн,С"] = {
    "деревья/им";
    "деревья/вн";
    "деревьев/рд";
    "деревьями/тв";
    "деревьях/пр";
    "деревьям/дт";
  };
  ["огонь/вн"] = "огонь";
  ["стены/рд"] = "стен";
  ["голем/рд"] = "голема";
  ["голем/дт"] = "голему";
  ["голем/тв"] = "големом";
  ["голем/вн"] = "голема";
  ["голем/пр"] = "големе";
}

obj {
  -"олень";
  nam = "олень";
  daemon = function(s)
    s.step = s.step + 1
    if s.step > 5 then
      p("Олень скрылся в лесу.")
      disable(s)
      DaemonStop(s)
      s.step = 0
    end
    return
  end;
  init_dsc = "Ты видишь на поляне оленя.";
  ["life_Give,Show"] = function(s, w)
    if not (w == _'перо') then
      return false
    end
    if s.sit then
      p("Олень никак не отреагировал.")
      return
    end
    s.sit = true
    p("Ты подносишь перо к носу оленя. Чувствуя прикосновение, он шумно втягивает в себя воздух. Затем он опускается перед тобой на колени.")
    DaemonStop(s)
  end;
  sit = false;
  step = 0;
  ["before_Enter,Climb"] = function(s, w, wh)
    if where(me()) == s then
      p("Но ты уже и так на олене.")
      return
    end
    if not s.sit then
      fn_call_before(s, 'Touch')
      return
    end
    if not have(_'перо') then
      p("Ты подумала, что тебе стоит сначала взять с собой перо странной совы. Кто знает, куда умчит тебя олень?")
      return
    end
    DaemonStop(s)
    s.sit = false
    if here() == _'В_лесу' then
      walk(_'к_хребту')
    else
      walk(_'к_поляне')
    end
  end;
  before_Exam = function(s, w, wh)
    if s.sit then
      p("Олень стоит перед тобой на коленях.")
    else
      if s:once() then
        p("Ты замечаешь, что у оленя странные глаза.")
      else
        p("Чёрные дырки-глаза оленя пугают тебя.")
      end
    end
  end;
  ["before_Touch,Talk,Ask,Tell,Kiss"] = function(s, w, wh)
    s.step = 4
    p("Олень попятился и шумно задышал, жадно втягивая морозный воздух.")
  end;
  obj = {
    obj {
      -"глаза оленя,глаза,дыр*";
      before_Default = "Тебе не нравятся глаза оленя.";
      before_Exam = "Вместо глаз у оленя чёрные дырки.";
    }:attr 'scenery';

    Prop {
      -"рога оленя,рога";
    };
  };
}:attr 'supporter':disable()

Area {
  -"лес|чаща";
  nam = "В_лесу";
  before_Cry = "-- Ма-маааааа! -- нет ответа.";
  depth = 0;
  dsc = function(s)
    p("Ты находишься в хвойном лесу.")
    if s.depth == 0 then
      if not fn_have_compass() then
        p("Между деревьями ты видишь снежное поле.")
      else
        p("Между деревьями на востоке ты видишь снежное поле.")
      end
    elseif s.depth == 1 then
      p("Тебя окружают деревья.")
    elseif s.depth == 2 then
      p("Ты видишь здесь замёрзший ручей.")
    elseif s.depth == 3 then
      p("Ты вышла на небольшую поляну.")
    elseif (s.depth - 4) % 2 == 0 then
      p("Лес становится всё гуще.")
    elseif (s.depth - 4) % 2 == 1 then
      p("Деревья окружают тебя со всех сторон.")
    end
  end;
  ["e_to,se_to,ne_to"] = function(s, t)
    if fn_check_compass(t) then
      return
    end
    if s.depth == 0 then
      return _'#поле'
    end
    me():need_scene(true)
    s.depth = s.depth - 1
    p("Ты идешь некоторое время на ", (_('@' .. t).word), ".")
    if s.depth == 0 then
      p("За деревьями на востоке ты видишь снежное поле.")
    end
    fn_forest_scenery(s)
  end;
  enter = function(s)
    if fn_seen('сова') then
      DaemonStart(_'сова')
    end
  end;
  out_to = function(s)
    if s.depth == 0 then
      return _'#поле'
    end
    return false
  end;
  ["s_to,n_to"] = function(s, t)
    if fn_check_compass(t) then
      return
    end
    if s.depth <= 1 then
      p("Ты решила, что идти вдоль границы леса не очень хорошая идея.")
    else
      p("Ты решила, что лучше держаться западного направления.")
    end
  end;
  title = "Лес";
  ["w_to,nw_to,sw_to"] = function(s, t)
    if fn_check_compass(t) then
      return
    end
    s.depth = s.depth + 1
    if s.depth > 8 then
      s.depth = 6 + fn_rnd(3)
    end
    fn_forest_scenery(s)
    me():need_scene(true)
    p("Ты идешь некоторое время на ", (_('@' .. t).word), ".")
    if s.depth > 7 and fn_rnd(100) < 30 then
      p("^Ты можешь идти так целую вечность...")
    end
  end;
  before_Drop = function(s, w, wh)
    p("Зачем бросать ", w:noun('вн'), " в лесу?")
  end;
  obj = {
    'олень';

    Sky {
      nam = "#небо";
    };

    Snow {
      nam = "#снег";
      before_Exam = function(s, w, wh)
        if here().depth == 0 then
          p("Здесь едва заметный след теряется.")
        else
          return false
        end
      end;
    };

    obj {
      nam = "#поле";
      before_Default = "Поле далеко.";
      before_Exam = "Снежное поле выглядит бескрайним.";
      ["before_Walk,Enter,Climb"] = function(s, w, wh)
        if here().depth == 0 then
          walk(_'поле')
        else
          p("Поле где-то на востоке.")
        end
      end;
    }:attr 'scenery';

    Prop {
      -"деревья|дерево|сосна,ветк*";
      nam = "#деревья";
      ["before_Enter,Climb"] = "Первые ветки находятся высоко. У тебя не получится забраться.";
      before_Exam = function(s, w, wh)
        if s:hint("plural") then
          p("Деревья покрыты снегом.")
        else
          p("Ветви дерева покрыты снегом.")
        end
      end;
    };

    obj {
      -"полярная сова|сова,птица";
      nam = "сова";
      daemon = function(s)
        if s.talked then
          return
        end
        if where(s) == _'В_лесу' and where(s) == _'В_лесу' and _'В_лесу'.depth == 0 and fn_rnd(3) == 1 then
          p("Хлопая крыльями сова улетела в сторону поля.")
          move(s, _'поле')
        elseif here() == _'поле' and where(s) == _'поле' and s.talked and fn_rnd(3) == 1 then
          p("Хлопая крыльями сова улетела в сторону леса.")
          move(s, _'В_лесу')
        end
        return
      end;
      dsc = function(s)
        if where(s) == _'поле' then
          p("На машине сидит сова.")
        else
          p("На ветке сосны сидит сова.")
        end
      end;
      init_dsc = "Ты замечаешь большую сову, сидящую на ветке сосны.";
      seen = false;
      talk_to = function(s)
        if where(s) == _'В_лесу' then
          p("Хлопая крыльями сова улетела в сторону поля.")
          move(s, _'поле')
          return
        end
        if not s.seen then
          p("Сначала хорошо бы рассмотреть, с чем имеешь дело.")
          return
        end
        if s.talked then
          p("-- Что всё это значит?^\n-- Я сделала то, что мне повелела госпожа.")
          p("^Сова хлопнула крыльями и улетела.")
          remove(s)
          DaemonStop(s)
          return
        end
        return _'разговор_с_совой'
      end;
      talked = false;
      before_Exam = function(s, w, wh)
        p("Тебе кажется, что это полярная сова. Только у неё странные глаза.")
        if here() == _'поле' then
          pn()
          fn_call_before(_'#глаза_совы', 'Exam')
        end
      end;
      before_Touch = function(s, w, wh)
        if where(s) == _'В_лесу' then
          p("Она слишком высоко.")
          return
        end
        if not s.seen then
          p("Сначала хорошо бы рассмотреть, с чем имеешь дело.")
          return
        end
        if s.talked then
          p("Тебе не очень хочется иметь с ней дело.")
        else
          p("Ты осторожно дотронулась до птицы.^")
          p("Сова вздрогнула и её глаза-дырки уставились на тебя.")
        end
      end;
      obj = {
        obj {
          -"глаза совы,глаза,дыр*";
          nam = "#глаза_совы";
          before_Default = "Тебе не нравятся эти глаза.";
          before_Exam = function(s, w, wh)
            p("На месте глаз у совы зияют чёрные дырки.")
            if not _'сова'.seen then
              p("^Интересно, видит ли она тебя?")
            end
            _'сова'.seen = true
          end;
        };
      };
    };

    Prop {
      -"поляна";
      nam = "#поляна";
    }:attr 'scenery':disable();

    Prop {
      -"ручей";
      nam = "#ручей";
    }:attr 'scenery':disable();
  };
}

obj {
  -"перо";
  nam = "перо";
  init_dsc = function(s)
    if s:hasnt("moved") and where(me()) == _'машина' then
      return
    end
    p("На крыше машины лежит белое перо.")
  end;
  before_Exam = function(s, w, wh)
    p("Белое перо.")
    if have(s) then
      p("Зачем оно тебе?")
    else
      p("Его оставила сова с дырками вместо глаз.")
    end
  end;
}

dlg {
  nam = 'разговор_с_совой';
  title = false;
  enter = function(s)
    pic_set('21')
  end;
  phr = {
    "-- О, я слышу тебя, дитя! -- ответ птицы напугал тебя.";
    {
      "Ты меня не видишь?";
      "-- Я тебя чувствую...";
    };
    {
      "Ты умеешь говорить?";
      "-- Я разговариваю с тобой.";
    };
    {
      "Что с твоими глазами?";
      "-- Такой меня сделала моя госпожа.";
      {
        "Кто твоя госпожа?";
        "-- Она вызвала меня. Она сказала, чтобы я передала тебе...";
        {
          "Что?";
          "-- Твоя мама ждёт тебя во дворце. Поспеши.";
          next = '#deep';
        };
        {
          "Ты видела мою маму?";
          "-- Твоя мама ждёт тебя во дворце. Поспеши.";
          next = '#deep';
        };
      };
    };
  };
  obj = {
    {
      '#deep';
      {
        "Где этот дворец?";
        "-- Он за ледяным хребтом на западе.";
        {
          "Это далеко?";
          function(s)
            p("-- Расстояние -- всего лишь время. А время здесь замёрзло. Возьми перо. По нему тебя узнают другие слуги госпожи.")
            move(_'перо', _'машина')
            _'перо':attr("~moved")
            _'сова'.talked = true
            walkout()
          end;
        };
      };
      {
        "Что за бред ты несёшь.";
        "-- Моя госпожа сказала мне передать тебе...";
        {
          "Ладно, ладно...";
          "-- Поспеши же, дитя!";
        };
      };
    };
  };
}

cutscene {
  nam = "к_хребту";
  text = [[Ты садишься на оленя и он поднимается с колен.^^
		Вы мчитесь через лес на запад. Снова и снова олень ловко огибает встречные деревья и вы оставляете их позади.^^
		Постепенно лес начинает редеть и сквозь деревья ты видишь ледяные горы.^^
		Олень остановился перед ледяной стеной и опустился, чтобы ты могла слезть.]];
  next_to = 'Ледяные_горы';
  onexit = function(s, to)
    p("Ты слезаешь с оленя.")
    move(_'олень', to)
  end;
  title = false;
}

cutscene {
  nam = "к_поляне";
  text = [[Ты садишься на оленя и он поднимается с колен.^^
		Вы мчитесь через лес на восток. Снова и снова олень ловко огибает встречные деревья и вы оставляете их позади.^^
		Постепенно лес начинает редеть.^^
		Олень остановился и опустился на колени, чтобы ты могла слезть.]];
  next_to = 'В_лесу';
  onexit = function(s, to)
    p("Ты слезаешь с оленя.")
    move(_'олень', to)
  end;
  title = false;
}

Area {
  nam = "Ледяные_горы";
  dsc = "Ты стоишь перед ледяной стеной, которая продолжается на север и юг. На востоке начинается лес.";
  ["e_to,ne_to,se_to"] = '#лес';
  in_to = '#стена';
  ["nw_to,sw_to,n_to,s_to"] = function(s)
    p("По этому направлению нет ничего интересного. Такая же ледяная стена.")
  end;
  onexit = function(s, t)
    if t == _'пещера' and not visited(_'пещера') then
      pic_set('23-pan')
    end
  end;
  title = "У ледяных гор";
  w_to = '#стена';
  obj = {
    obj {
      -"хвойный лес,лес|чаща|деревья";
      nam = "#лес";
      before_Default = "Лес далеко.";
      before_Exam = "На деревьях лежит снег.";
      ["before_Walk,Enter,Climb"] = "В этом лесу можно ходить вечность.";
    }:attr 'scenery';

    Snow {
      nam = "#снег";
    };

    Sky {
      nam = "#небо";
    };

    obj {
      nam = "#стена";
      word = function(s)
        pr("ледяная стена,стена|лёд|лед|поверхность|скала|гора|горы/жр")
        if s.light > 0 then
          pr("|свечение/ср|свет")
        end
      end;
      before_Knock = function(s, w, wh)
        if s.light == 0 then
          return false
        end
        p("Ты попыталась постучать по стене, но у тебя это не вышло! Рука прошла сквозь лёд!")
      end;
      daemon = function(s)
        if player_moved() then
          s.light = 0
          DaemonStop(s)
          return
        end
        if s.light == 1 then
          p("Ты замечаешь, что под поверхностью льда разливается фиолетовое свечение.")
        elseif s.light == 2 then
          p("Фиолетовое свечение под поверхностью льда усиливается!")
        elseif s.light == 3 then
          p("Фиолетовое свечение ослабевает.")
        else
          DaemonStop(s)
          s.light = 0
          return
        end
        s.light = s.light + 1
      end;
      light = 0;
      before_Attack = "Скала {$fmt em|выглядит} твёрдой. Ты решила не рисковать.";
      before_Climb = "У тебя вряд ли это получится. Стена отвесная.";
      ["before_Enter,Walk"] = function(s, w, wh)
        if s.light == 0 then
          p("Как ты это сделаешь? Стена твёрдая, гладкая и скользкая.")
          return
        end
        walk(_'пещера')
      end;
      before_Exam = function(s, w, wh)
        if s.light > 0 then
          p("Сквозь лёд ты видишь фиолетовое свечение.")
        else
          p("Ледяная стена отвесно уходит вверх. Её поверхность выглядит скользкой.")
        end
      end;
      before_Taste = "А язык не приклеится?";
      ["before_Touch,Push"] = function(s, w, wh)
        p("Ты касаешься ладонью гладкой ледяной поверхности.")
        if s.light > 0 then
          p("Как странно, твоя рука проходит сквозь лёд!")
          s.light = 2
        else
          s.light = 1
        end
        DaemonStart(s)
      end;
    }:attr 'scenery';
  };
}

room {
  -"пещера";
  nam = "пещера";
  Play = function(s, w)
    if not w or not have(_'скрипка') then
      return false
    end
    if not w then
      w = _'скрипка'
    end
    if not (w == _'скрипка') then
      return false
    end
    if _'#кристаллы'.try == 0 or _'#кристаллы'.broken then
      return false
    end
    _'#кристаллы'.broken = true
    pic_set('24')
    p("Интересно... А что если? Не успев додумать мысль, ты уже берёшь скрипку в руки.^^\nТы извлекаешь \"ми\" второй октавы. Сначала ничего не происходит, но затем ты слышишь, как странный кристалл отзывается\nна звук твоей скрипки.^^\nЗвуки скрипки и кристалла усиливают друг друга в резонансе. Ты почти физически ощущаешь, как\nнапряжение кристалла достигает своего пика. И, наконец, он шумно взрывается на мелкие осколки.")
    enable(_'осколки')
  end;
  dark_dsc = "Ты видишь слабое свечение в темноте.";
  dsc = [[Ты находишься внутри небольшой ледяной пещеры. У восточной стены ты видишь странное свечение.^
Пещера продолжается на северо-запад.]];
  e_to = '#свечение';
  nw_to = function(s)
    if fn_thedark(here()) and not fn_visited(_'пещера2') then
      p("Ты же не видишь куда идти.")
      return
    end
    return _'пещера2'
  end;
  onenter = function(s, f)
    if not visited(s) then
      p("Доверившись интуиции, ты входишь в фиолетовое свечение, которое вдруг заполняет всё вокруг. Шаг. Еще один. И вдруг ты оказываешься в полной темноте. Если не считать слабого свечения позади.")
    end
  end;
  out_to = 'Ледяные_горы';
  title = function(s)
    if fn_thedark(here()) then
      p("В темноте")
    else
      p("Ледяная пещера")
    end
  end;
  obj = {
    obj {
      -"свечение";
      nam = "#свечение";
      ["before_Touch,Push,Knock"] = "Твоя рука проходит сквозь свечение.";
      before_Exam = function(s, w, wh)
        p("Этим путём ты попала сюда. Вероятно, с помощью него можно выйти наружу.")
        p("^Ты обращаешь внимание, что источником странного свечения служат фиолетовые кристаллы, растущие из стены.")
        enable(_'#кристаллы')
      end;
      ["before_Walk,Climb,Enter"] = function(s, w, wh)
        walk(_'Ледяные_горы')
      end;
    }:attr 'scenery,luminous';

    Prop {
      -"стены|стена|пол|потолок";
      nam = "#стены";
      ["before_Touch,Push,Knock"] = { "Похоже", "ты находишься в ледяной пещере." };
      before_Exam = function(s, w, wh)
        if fn_thedark(here()) then
          p("В полной темноте это будет сложно.")
        else
          return false
        end
      end;
    }:attr 'luminous';

    obj {
      -"кристаллы|кристалл";
      nam = "#кристаллы";
      ["before_Attack,Knock"] = function(s, w, wh)
        if s.broken then
          p("Ты уже разрушила один кристалл.")
          return
        end
        if s.try == 2 then
          p("Ты постучала по звонкому кристаллу.")
        else
          p("Ты постучала по одному из кристаллов.")
        end
        if s.try == 0 then
          s.try = 1
          p("Ответом был мелодичный звенящий звук. Твой музыкальный слух определил его как \"фа\" малой октавы, что\n\t\t\t\tнаходится вне диапазона твоей скрипки. Интересно, они все звучат одинаково?")
        elseif s.try == 1 then
          p("На этот раз звук оказался более высоким. Ты определила его как {$fmt em|\"ми\"} второй октавы.")
          p("^Ты решила запомнить этот кристалл.")
          s.try = 2
        else
          p("Звенящий звук кристалла долго отражается от ледяных стен. Ты чувствуешь вибрацию.")
        end
      end;
      broken = false;
      try = 0;
      before_Exam = "Полупрозрачные кристаллы растут прямо из льда.";
      before_Touch = function(s, w, wh)
        if s.try == 0 or s.broken then
          return false
        else
          p("Ты чувствуешь как кристалл вибрирует.")
        end
      end;
    }:attr 'luminous,static':disable();

    obj {
      -"осколки кристалла,осколок*|осколки|кусочки|куски";
      nam = "осколки";
      before_Light = "Свет испускаемый осколками очень тусклый для этого.";
      before_Exam = "Осколки кристалла пульсируют слабым фиолетовым свечением.";
      before_Take = function(s, w, wh)
        if here() == _'пещера2' and here().solved then
          p("Ты боишься беспокоить летучих мышей.")
          return
        end
        return false
      end;
    }:attr 'luminous':disable();
  };
}:attr '~light'

obj {
  -"обрыв,разлом|пропасть";
  nam = "ообрыв";
  before_Enter = "Прыгнуть в пропасть? Тебе нужно найти маму, а не сбегать от проблем...";
  before_Exam = "Глубокий разлом во льду. Света фонарика недостаточно, чтобы оценить его глубину. К счастью, ширина разлома не превышает двух метров.";
  before_JumpOver = function(s, w, wh)
    p("Ты разбегаешься и прыгаешь через пропасть...")
    if here() == _'обрыв' then
      walk(_'Другая_сторона')
    else
      walk(_'обрыв')
    end
  end;
  before_Receive = function(s, w, wh)
    p("Ты потом не сможешь достать ", w:noun('вн'), " из пропасти.")
  end;
}:attr 'scenery,container,open'

room {
  -"пещера";
  nam = "пещера2";
  dsc = function(s)
    pn("Стены этой части пещеры испещрены небольшими отверстиями.")
    if from() == _'пещера' then
      p("Ты попала сюда с юго-востока. Пещера продолжается на юго-запад.")
    else
      p("Ты попала сюда с юго-запада. Пещера продолжается на юго-восток.")
    end
    if not s.solved then
      p("^^Твой взгляд прикован к потолку, который усеян чёрными лоскутками. Ты вздрагиваешь, когда ответ приходит тебе в голову. Пещера заполнена летучими мышами!")
    else
      p("^^Ты видишь, как странные чёрные твари дерутся за фиолетовые осколки кристалла,\nкотрые ты рассыпала по полу пещеры.")
    end
  end;
  out_to = function(s)
    if from() == _'пещера' then
      return _'пещера'
    else
      return _'обрыв'
    end
  end;
  ["se_to,e_to"] = 'пещера';
  solved = false;
  ["sw_to,w_to"] = function(s)
    if fn_thedark(here()) and not fn_visited(_'обрыв') then
      p("Сложно сделать это в полной темноте.")
      return
    end
    return _'обрыв'
  end;
  title = "Пещера с летучими мышами";
  before_Listen = function(s, w, wh)
    if s.solved then
      p("Ты слышишь отвратительный писк и хлопанье крыльев.")
    else
      p("Стоит мёртвая тишина.")
    end
  end;
  obj = {
    Prop {
      -"стены|стена|пол|потолок";
    };

    obj {
      -"летучие мыши|мыши,твари,мышь*";
      nam = "#мыши";
      description = function(s)
        p("Тебе они не нравятся. Называя вещи своими словами -- ты их панически боишься.")
        if here().solved then
          p("^Но кажется, они поглощены борьбой за светящимися осколками кристалла.")
        end
      end;
      ["life_Show,Give"] = "Пока они заняты, лучше их не беспокоить.";
      before_Attack = "Тебе не удастся убить их всех.";
    }:attr 'concealed,animate';

    obj {
      -"отверстия|дырки|дыры";
      description = "Тебе приходит в голову, что эти отверстия могут быть норами. Лучше держаться от них подальше.";
      before_Receive = "Не стоит туда соваться.";
    }:attr 'scenery,container';
  };
}:attr '~light'

room {
  nam = "обрыв";
  dsc = "На западе гладкий пол пещеры заканчивается обрывом. Выход находится на юго-востоке.";
  out_to = 'пещера2';
  ["se_to,e_to"] = 'пещера2';
  w_to = 'ообрыв';
  obj = {
    'ообрыв';

    Prop {
      -"стены|стена|пол|потолок";
    };
  };
}:attr '~light'

obj {
  nam = "отверстие";
  word = function(s)
    pr("отверстие|выход|дырка|дыра")
    if here() == _'За_ледяной_стеной' then
      pr("|пещера")
    end
  end;
  ["before_Enter,Walk,Climb"] = function(s, w, wh)
    if here() == _'Другая_сторона' then
      walk(_'За_ледяной_стеной')
    else
      walk(_'Другая_сторона')
    end
  end;
  before_Exam = "Отверстие достаточно широкое для того, чтобы пролезть в него.";
}:attr 'scenery'

room {
  -"пещера";
  nam = "Другая_сторона";
  dsc = [[Здесь светло. Свет поступает в пещеру через широкое отверстие на западе.
Пропасть находится на востоке.]];
  e_to = 'ообрыв';
  out_to = 'отверстие';
  title = "Пещера";
  w_to = 'отверстие';
  obj = {
    'ообрыв';
    'отверстие';

    Prop {
      -"стены|стена|пол|потолок";
    };
  };
}

room {
  -"плато/ср";
  nam = "За_ледяной_стеной";
  cant_go = "На плато не видно ничего интересного, кроме скалы.";
  dsc = function(s)
    p("Ты находишься на снежном плато, рядом со входом в пещеру. Ледяные горы окружают плато со всех сторон. Может быть поэтому, стоит мёртвая тишина.")
    p("На западе, в центре плато возвышается ледяная скала.")
  end;
  e_to = 'отверстие';
  in_to = 'отверстие';
  title = "Плато";
  w_to = '#замок';
  obj = {
    'отверстие';

    Prop {
      -"горы/но,мн|стена|стены";
    };

    Snow {
      nam = "#снег";
    };

    Sky {
      nam = "#небо";
    };

    obj {
      -"скала|замок|дворец|вершины";
      nam = "#замок";
      before_Default = "Сначала к скале нужно подойти.";
      ["before_Enter,Walk,Climb"] = function(s, w, wh)
        walk(_'У_замка')
      end;
      before_Exam = "Остроконечные вершины ледяной громады высоко возвышаются над плато.";
    }:attr 'scenery';
  };
}

obj {
  -"разлом|проход|отверстие|щель|вход";
  nam = "ворота";
  description = "Высота разлома с неровными краями достигает трёх метров, а ширина -- двух. Верх отверстия имеет форму арки.";
  ["before_Walk,Enter,Climb"] = function(s, w, wh)
    if here() == _'У_замка' then
      fn_xaction('Enter', _'#замок')
    else
      walk(_'У_замка')
    end
  end;
}:attr 'scenery':disable()

obj {
  nam = "голем";
  word = function(s)
    if s:has("animate") then
      p("ледяной человек/ед,мр,од|человек|статуя|голем/ед,мр,од")
    else
      p("статуя|ледяной человек|человек")
    end
  end;
  description = function(s)
    if s:has("animate") then
      p("Высота ледяного человека около двух метров. У него есть руки и ноги, но вместо головы лишь небольшой выступ.")
      if visited(_'королева_диалог') and disabled(_'дверь') then
        p("Сейчас голем стоит у северной части зала и ждет тебя.")
      end
    else
      p("Статуя сделана из льда и изображает двухметрового человека с массивным телосложением.")
    end
  end;
  init_dsc = function(s)
    if s:has("animate") then
      p("У стены стоит ледяной человек.")
    else
      p("Твоё внимание привлекает огромная ледяная статуя.")
    end
  end;
  ["life_Give,Show,ThrowAt"] = function(s, w)
    if w == _'перо' then
      if disabled(_'ворота') then
        p("Едва ты достала перо, как статуя сдвинулась с места. Сделав два шага по направлению к тебе,\nстрашный ледяной человек остановился.^")
        enable(_'ворота')
        p("-- Госпожа ждёт тебя! -- прогремел голос с двух метровой высоты.^")
        p("После этих слов голем размахнулся и ударил своим кулаком в стену.")
        p("Стена с треском раскололась и в ней образовался проход.")
        s:attr("animate")
      else
        if not visited(_'Тронный_зал') then
          p("-- Госпожа ждёт тебя! -- прогремел голос с двух метровой высоты.")
        else
          p("-- Я узнал тебя.")
        end
      end
      return
    end
    return false
  end;
  before_Any = function(s, e)
    if e == 'Exam' or e == 'Walk' or e == 'Climb' or e == 'Enter' then
      return false
    end
    if not disabled(_'дверь') or not visited(_'королева_диалог') then
      return false
    end
    p("Сначала к голему нужно подойти.")
  end;
  before_Climb = "Это не так просто сделать.";
  ["before_Take,Push,Pull"] = function(s, w, wh)
    p(s:Noun(), " весит не меньше сотни килограмм. Как ты это сделаешь?")
  end;
  before_Taste = "А язык не приклеится?";
  ["before_Walk,Enter,Climb"] = function(s, w, wh)
    if visited(_'королева_диалог') and disabled(_'дверь') then
      p("Ты последовала за големом. Обогнув колонну и подойдя к северной стене, ты заметила небольшую деревянную дверь.")
      enable(_'дверь')
      return
    end
    return false
  end;
  obj = {
    Prop {
      -"ноги|руки|голова|выступ";
    };
  };
}:attr '~animate'

room {
  nam = "У_замка";
  dsc = function(s)
    p("Ты стоишь у подножия ледяной скалы. Отвесная стена уходит высоко вверх.")
    if not disabled(_'ворота') then
      p("В стене зияет разлом.")
    end
    p("Пещера, с помощью которой ты прошла сквозь горы, находится на востоке.")
  end;
  e_to = 'За_ледяной_стеной';
  in_to = '#замок';
  onenter = function(s, f)
    if not visited(s) then
      pic_set('25')
    end
  end;
  title = "У подножия скалы";
  w_to = '#замок';
  obj = {
    'голем';

    obj {
      -"скала|гора|замок|дворец|стена";
      nam = "#замок";
      description = "Острые вершины скалы устремлены в небо.";
      ["before_Enter,Walk,Climb"] = function(s, w, wh)
        if disabled(_'ворота') then
          return false
        end
        if _'голем':hasnt("moved") then
          move(_'голем', _'Тронный_зал')
        end
        walk(_'Тронный_зал')
      end;
      before_Taste = "А язык не приклеится?";
      obj = {
        'ворота';
      };
    }:attr 'scenery';

    Snow {
      nam = "#снег";
    };

    Sky {
      nam = "#небо";
    };
  };
}

obj {
  -"мама,мать,королева,женщина";
  nam = "королева";
  ["before_Talk,Say,Ask,Tell"] = function(s, w, wh)
    if not s.queen then
      p("Сначала ты хочешь рассмотреть её внимательней.")
    else
      DaemonStop(s)
      if visited(_'королева_диалог') then
        p("-- Ты уже готова стать моей дочерью?^\n-- Нет!^\n-- Ну что же, я подожду.")
      else
        if _'браслет':has("worn") then
          walk(_'королева_диалог')
        else
          walk(_'badend2')
        end
      end
    end
  end;
  daemon = function(s)
    local tt = fn_tbl4()
    p('tt[rnd(#tt), " -- произносит твоя мать с трона."')
  end;
  description = function(s)
    s.queen = true
    if _'Тронный_зал'.near then
      p("Женщина похожа на твою маму, но в чертах её лица ты видишь что-то незнакомое, чужое и, поэтому, неприятное.\nНо больше всего тебя пугают её глаза. Они закрыты. Ты растерянно вглядываешься в её лицо, снова и снова пытаясь отыскать родные черты.")
    else
      p("Это твоя мама! Не может быть! Что это за место? Что она тут делает? Столько вопросов!")
    end
  end;
  init_dsc = function(s)
    p("На троне сидит твоя мама.")
    if s.queen then
      p("Или это не мама?")
    end
  end;
  queen = false;
  ["before_Kiss,Touch"] = "Тебе кажется, что это не твоя мама. Тебе становится страшно.";
  before_Walk = function(s, w, wh)
    return fn_call_before(_'#трон', 'Walk')
  end;
  obj = {
    obj {
      -"лицо";
      description = function(s)
        if _'Тронный_зал'.near then
          _'королева':description()
        else
          p("Отсюда плохо видно её лицо.")
        end
      end;
    };

    obj {
      -"глаза";
      description = function(s)
        if _'Тронный_зал'.near then
          if not visited(_'королева_диалог') then
            p("Её глаза закрыты. Как будто она спит. Тебе становится страшно.")
          else
            p("Ты стараешься не думать о глазах твоей {$fmt em|новой} мамы.")
          end
        else
          p("Отсюда плохо видны её глаза.")
        end
      end;
    };
  };
}:attr 'animate'

room {
  -"зал";
  nam = "Тронный_зал";
  dsc = function(s)
    p("Ты находишься в огромном зале. В центре зала установлен трон. Все пространство зала залито светом, который отражается\nот ледяных стен, пола, потолка и массивных колонн. У южной стены расположена широкая лестница, ведущая вниз. Выход из зала находится на востоке.")
    if not fn_disabled(_'дверь') then
      p("Дверь в твою комнату находится в северной стене.")
    end
  end;
  enter = function(s)
    if s:once() then
      pn("Набравшись мужества ты вошла внутрь и оказалась в длинном коридоре.")
      p("Голем последовал за тобой. Его шаги гулко отражались от изломанных стен и сводчатого потолка.")
      pn("Через некоторое время коридор кончился и вы вошли в большой зал.")
      pn("Зал был огромен! В его центре ты увидела трон, на котором сидела женщина... Твоя... мама?")
      pn()
      DaemonStart(_'королева')
      remove(_'сова')
      pic_set('30')
    end
  end;
  in_to = function(s)
    if not disabled(_'дверь') then
      return _'дверь'
    end
    return false
  end;
  n_to = function(s)
    if disabled(_'дверь') and visited(_'королева_диалог') then
      return _'голем'
    end
    if not disabled(_'дверь') then
      return _'дверь'
    end
    return false
  end;
  near = false;
  onexit = function(s, to)
    if to == _'королева_диалог' or to == _'badend2' or to == _'badend4' then
      return
    end
    if not s.near then
      if _'браслет':hasnt("worn") then
        if to == _'Зал_с_зеркалами' then
          p("Сейчас не лучшее время для прогулок.")
          return false
        end
        p("Поддавшись смутному интуитивному чувству, ты покидаешь тронный зал.")
        DaemonStop(_'королева')
        return
      end
      p("Ты нашла свою маму! Не время уходить!")
      return false
    end
    if fn_seen('голем') then
      if not visited(_'королева_диалог') then
        p("Ты пытаешься уйти из зала, но ледяной голем преграждает тебе путь.")
        return false
      end
    end
  end;
  ["out_to,e_to"] = 'ворота';
  ["s_to,d_to"] = '#лестница';
  u_to = function(s)
    if visited(_'комната') then
      return _'дверь'
    end
    return false
  end;
  before_Default = function(s, e, w)
    if not w then
      return false
    end
    if not (w == _'королева') and not (w == _'#трон') then
      return false
    end
    if e == 'Exam' or s.near then
      return false
    end
    if e == 'Walk' then
      return false
    end
    p("Сначала нужно подойти к трону.")
  end;
  obj = {
    'королева';
    'ворота';

    obj {
      -"трон|кресло";
      nam = "#трон";
      description = "Великолепный трон сделан, как и всё вокруг, из льда. Высокая прямая спинка украшена причудливыми узорами.";
      ["before_Enter,Climb"] = function(s, w, wh)
        if fn_seen('королева') then
          p("Трон занят.")
        else
          p("Тебе не нужна власть. Тебе нужна мама.")
        end
      end;
      before_Walk = function(s, w, wh)
        if _'Тронный_зал'.near then
          return false
        end
        p("Ты бежишь к трону. Твоё сердце от радости выпрыгивает из груди. Но что-то странное ты замечаешь в облике матери.\nВ нерешительности ты останавливаешься в нескольких шагах от неё.")
        if _'браслет':hasnt("worn") then
          fn_daemonStop(_'королева')
          walk(_'badend2')
          return
        end
        _'Тронный_зал'.near = true
      end;
    }:attr 'scenery,supporter';

    Prop {
      -"узоры|спинка|колонны|стены";
    };

    door {
      -"деревянная дверь|дверь";
      nam = "дверь";
      description = function(s)
        p("Небольшая деревянная дверь. Странно, что она сделана не из льда.")
        return false
      end;
      door_to = function(s)
        if here() == _'комната' then
          return _'Тронный_зал'
        else
          return _'комната'
        end
      end;
    }:attr 'scenery':disable();

    obj {
      -"свет";
      before_Default = "Как ты сделаешь это с светом?";
      before_Exam = "Свет кажется тебе каким то бледным. Он не приносит радости.";
    }:attr 'scenery';

    obj {
      nam = "#лестница";
      description = "Широкая лестница начинается от южной стены и ведёт вниз.";
      ["before_Enter,Walk,Climb"] = function(s, w, wh)
        walk(_'Зал_с_зеркалами')
      end;
    }:attr 'scenery';
  };
}

dlg {
  nam = 'королева_диалог';
  title = false;
  exit = "^Твоя мама махнула рукой голему и тот, с грохотом, направился к северной стене зала. Дойдя до неё он остановился.";
  phr = {
    "-- Иди же и обними меня! -- глаза матери по прежнему закрыты и это пугает тебя.";
    {
      "Почему твои глаза закрыты?";
      "-- Поцелуй меня и я открою их.";
      next = '#дальше';
    };
    {
      "Ты точно моя мама?";
      "-- Да, а ты моя дочь. Я так ждала тебя, иди и обними меня.";
      next = '#дальше';
    };
  };
  obj = {
    {
      '#дальше';
      {
        "Я не верю тебе! Ты не моя мама!";
        "-- Ну зачем ты так? Ты стала такой грубой!";
        {
          "Хватит притворяться!";
          "-- Я твоя {$fmt em|другая} мама. Я буду любить тебя вечно. Поцелуй меня, дитя.";
        };
        {
          "Куда ты дела мою настоящую маму?";
          "-- Здесь нет другой мамы, кроме меня. Зачем ты упрямишься? У нас есть целая вечность, чтобы полюбить друг-друга.";
        };
        {
          "Открой свои... чёртовы глаза!";
          "-- Хорошо, как скажешь... -- женщина открыла глаза. На месте глаз ты видишь чёрные отверстия. Тебе кажется, что ты сходишь с ума.";
        };
        onempty = function(s)
          fn_push('#дальше2')
        end;
      };
      {
        "Хорошо, сейчас.";
        function(s)
          walk(_'badend')
        end;
      };
    };
    {
      '#дальше2';
      {
        "Я знаю, ты забрала мою маму! Сейчас же верни её!";
        "-- Хорошо, дитя. Жаль, что тебе нужно время, чтобы привыкнуть ко мне. Но я подожду. Мой слуга проводит тебя в твою комнату.";
        {
          "Я всё равно сбегу и найду свою настоящую маму! Я знаю -- она где-то здесь!";
          "-- Глупышка, ты думаешь я тебя обманываю? Знай, ты свободна ходить туда, куда хочешь. И делать то, что хочешь. Можешь искать свою... {$fmt em|другую} маму. Но не отказывай мне, посмотри свою комнату. Отдохни. И приходи ко мне, когда забудешь о своих фантазиях.";
          {
            "А если я найду маму, ты нас отпустишь?";
            "-- Ты никогда не найдёшь её. Но хорошо, я обещаю. Только и ты пообещай мне, что если отчаешься найти её, то станешь моей дочерью.";
            {
              "Хорошо, обещаю.";
              function(s)
                p("-- Ну что же, чувствуй себя как дома. Дворец в твоём распоряжении.")
                walkback(_'Тронный_зал')
              end;
            };
            {
              "Похоже, у меня нет выбора. Я в твоей власти? Мне не выбраться отсюда?";
              function(s)
                p("-- Хорошо, что мы поняли друг-друга. Дворец в твоём распоряжении.")
                walkback(_'Тронный_зал')
              end;
            };
          };
        };
      };
    };
  };
}

cutscene {
  nam = "badend";
  exit = function(s)
    pic_pop()
  end;
  next_to = 'королева_диалог';
  onenter = function(s, f)
    pic_push('99')
  end;
  title = "Конец";
  text = {
    [[Ты поднимаешься по ступенькам пьедестала и обнимаешь свою мать.^^
		От неё веет холодом, который сковывает тебя, но ты уже ничего не можешь изменить.^^
		Глаза Снежной Королевы открываются и ты смотришь в чёрную бездну...^^
		{$fmt b|{$fmt c|КОНЕЦ}}]];
    "{$fmt r|{$fmt em|Но всё могло закончиться по другому...}}";
  };
}

cutscene {
  nam = "badend2";
  exit = function(s)
    pic_pop()
  end;
  next_to = 'Тронный_зал';
  onenter = function(s, f)
    pic_push('99')
  end;
  title = false;
  text = {
    [[-- Не бойся меня, беззащитное дитя. Я вижу, что на тебе нет {$fmt em|её} талисмана. Это лучше для нас обеих, всё закончится быстро...^^
		И все сомнения вдруг уходят. Чувствуя в глубине ужас, ты поднимаешься по ступенькам пьедестала и обнимаешь свою мать.^^
		От неё веет холодом, который сковывает тебя, и ты уже ничего не можешь изменить.^^
		Ты смотришь внутрь черных дыр-глаз Снежной Королевы...^^
		{$fmt b|{$fmt c|КОНЕЦ}}]];
    "{$fmt r|{$fmt em|Но всё могло закончиться по другому...}}";
  };
}

cutscene {
  nam = "badend4";
  exit = function(s)
    pic_pop()
    enable(_'королева')
  end;
  next_to = 'Тронный_зал';
  onenter = function(s, f)
    pic_push('99')
    disable(_'королева')
  end;
  title = false;
  text = {
    [[-- Спасибо, дитя. Ты правильно сделала, что сама отдала мне {$fmt em|её} талисман. Это лучше для нас обеих, всё закончится быстро...^^
		И все сомнения вдруг уходят. Чувствуя в глубине ужас, ты поднимаешься по ступенькам пьедестала и обнимаешь свою мать.^^
		От неё веет холодом, который сковывает тебя, и ты уже ничего не можешь изменить.^^
		Ты смотришь внутрь черных дыр-глаз Снежной Королевы...^^
		{$fmt b|{$fmt c|КОНЕЦ}}]];
    "{$fmt r|{$fmt em|Но всё могло закончиться по другому...}}";
  };
}

dlg {
  nam = 'сова2_диалог1';
  title = false;
  enter = function(s)
    pic_set('21')
  end;
  phr = {
    "-- Я хочу помочь тебе, дитя. -- сказала странная птица.";
    {
      "Как именно?";
      "-- Я покажу тебе путь отсюда.";
      {
        "Но я нашла свою маму. Правда, она застряла в зеркале... Ты можешь помочь?";
        "-- Глупое дитя. Ты так ничего и не поняла? Повесь зеркало на стену.";
      };
    };
  };
}

dlg {
  nam = 'сова2_диалог2';
  title = false;
  enter = function(s)
    pic_set('21')
  end;
  phr = {
    "-- Итак, дитя, ты уже поняла, что твоя мама находится в нормальном мире? А ты -- за зеркалом?";
    {
      "Да.";
      "-- Хорошо, это сэкономит нам время. Итак, чтобы вернуться в нормальный мир, ты должна войти в зеркало...";
      next = '#дальше';
    };
    {
      "Нет.";
      "-- Всё просто, ты находишься за зеркалом. Твоя мама -- в обычном мире. Чтобы вернуться домой ты должна войти в зеркало...";
      next = '#дальше';
    };
  };
  obj = {
    {
      '#дальше';
      {
        "Просто войти в зеркало?";
        "-- Да. Но сначала, его нужно разморозить. И это могу сделать я. Для тебя.";
        {
          "Так сделай это!";
          "-- Я могу это сделать. Но для этого, мне нужны глаза.";
          next = '#дальше2';
        };
        {
          "Что ты хочешь взамен?";
          "-- Мне нужны глаза.";
          next = '#дальше2';
        };
      };
      {
        "Но я нашла свою маму. Значит, мы свободны!";
        "-- Снежная Королева всё равно не отпустит тебя, дитя. Но я могу тебе помочь.";
      };
      {
        "Зачем ты помогаешь мне?";
        "-- Я хочу стать свободной, мне надоело служить госпоже.";
      };
    };
    {
      '#дальше2';
      {
        "Глаза?";
        "-- Да. Существа, подобные мне, не могут даже коснуться зеркала. Но с настоящими глазами...";
        {
          "И где же я найду глаза?";
          "-- У тебя есть глаза. В этом месте ты единственная, у кого они есть. Отдай их мне!";
          {
            "Нет!";
            function(s)
              p('-- Я возьму их не надолго. Больно не будет. Тебе просто нужно согласиться. И помни. Я одна могу помочь тебе вернуться домой и увидеть маму. Так "да", или "нет"?')
              fn_push('#данет')
            end;
          };
          {
            "Хорошо.";
            "-- Мне нужен ответ. Да или нет?";
            {
              "Да.";
              function(s)
                walk(_'yes')
              end;
            };
            {
              "Нет!";
              function(s)
                p("-- Ну что же. Я подожду, если ты передумаешь...")
                walkout()
              end;
            };
            tag = "#данет";
          };
        };
      };
    };
  };
}

dlg {
  nam = 'сова2_диалог3';
  title = false;
  enter = function(s)
    pic_set('21')
  end;
  phr = {
    "-- Итак, дитя, что ты решила? Ты отдашь мне свои глаза?";
    {
      "Да.";
      function(s)
        walk(_'yes')
      end;
    };
    {
      "Нет!";
      function(s)
        p("-- Ну что же. Я подожду, если ты передумаешь...")
        walkout()
      end;
    };
  };
}

obj {
  -"полярная сова|сова,птица";
  nam = "сова2";
  daemon = function(s)
    s.num = s.num + 1
    if s.num < 3 then
      return
    end
    if _'#окно':hasnt("open") then
      p("Ты слышишь стук в окно.")
    else
      p("Ты видишь, как в открытое окно влетает полярная сова и садится прямо на стол.")
      DaemonStop(s)
      s.finside = true
      move(s, _'#стол')
      s:attr("~scenery")
    end
  end;
  description = "Похоже, это та самая сова, которая привела тебя в это место. Ты боишься смотреть в её чёрные глаза.";
  finside = false;
  num = 0;
  talk_to = function(s)
    if not s.finside then
      p("Она за стеклом.")
      return
    end
    if visited(_'сова2_диалог1') and not (fn_where(_'зеркало') == _'#стена') then
      p("-- Повесь зеркало на стену, дитя. Скорее!")
      return
    end
    if not visited(_'сова2_диалог1') and not (fn_where(_'зеркало') == _'#стена') then
      return _'сова2_диалог1'
    end
    if not visited(_'сова2_диалог2') then
      return _'сова2_диалог2'
    end
    return _'сова2_диалог3'
  end;
  obj = {
    obj {
      -"глаза совы,глаза,дыр*";
      nam = "#глаза_совы";
      before_Default = "Тебе не нравятся эти глаза.";
      before_Exam = "На месте глаз у совы зияют чёрные дырки.";
    };
  };
}:attr 'scenery,animate'

room {
  -"комната";
  nam = "комната";
  dsc = function(s)
    p("Это действительно твоя комната. Комната, которую ты покинула ещё совсем недавно. Перед тем... как вы уехали с мамой...^^\nТы видишь те же: стол, шкаф, кровать и книжные полки... И даже окно!")
    if not visited(_'gotmirror') then
      p("Правда, мебель стоит неправильно и на стене нет зеркала. Интересно, куда оно подевалось?")
    else
      p("Правда, мебель стоит неправильно.")
      if where(_'зеркало') == _'#стена' then
        p("На стене висит зеркало.")
      end
    end
    if fn_seen('королева2') then
      p("^^В комнате, прислонившись к стене, стоит Снежная Королева. Ты видишь как поверхность зеркала мерцает фиолетовым светом.")
    end
    if where(_'сова2') and where(_'сова2') == _'#стол' then
      p("^^Полярная сова по прежнему сидит на твоём столе.")
    end
  end;
  enter = function(s)
    if s:once() then
      p("За дверью оказалась лестница, которая вела наверх. Ты поднялась по ней и оказалась в ... своей комнате.")
      move(_'голем', _'У_замка')
    end
    if visited(_'gotmirror') and _'зеркало'.seen and not _'сова2'.finside then
      _'сова2'.num = 0
      DaemonStart(_'сова2')
    end
  end;
  exit = function(s)
    DaemonStop(_'сова2')
    if not _'сова2'.finside then
      remove(_'сова2')
    end
  end;
  onexit = function(s, t)
    if fn_seen('королева2') and not (t == _'комната2') then
      p("Если переход в зеркале закроется, ты никогда не вернёшься домой. Надо спешить!")
      return false
    end
  end;
  ["s_to,out_to"] = 'дверь';
  obj = {
    'дверь';

    obj {
      -"книжные полки/жр,мн|полки/мн,жр|полка/жр";
      description = function(s)
        p("Полки висят на стене прямо над столом.")
        if fn_where(fn_ref('сказки')) == s and fn_disabled(fn_ref('сказки')) then
          p("Они завалены школьными учебниками и тетрадками.")
          p("^Ты видишь на одной из полок сказки Андерсена. Ты узнала книгу по голубому цвету обложки и золотым буквам на корешке.")
          fn_enable(fn_ref('сказки'))
          return
        end
        return false
      end;
      obj = {
        Useless {
          -"учебники";
        };

        Useless {
          -"тетрадки";
        };

        obj {
          -"сказки/мн|книга";
          nam = "сказки";
          ["before_Consult,Search,Open,Exam"] = function(s, w, wh)
            if not have(s) then
              p("Сначала книгу нужно взять.")
              return
            end
            if s:once() then
              pn("Ты открыла книгу на случайной странице. Буквы были знакомыми, но текст не читался.\nНе сразу, но все-таки ты сообразила, что слова написаны наоборот. С трудом ты прочитала следующее:^")
            end
            p("{$fmt em|Стенами чертогам были вьюги, окнами и дверями буйные ветры. Сто с лишним зал тянулись здесь одна за другой так, как наметала их вьюга. Все они освещались северным сиянием, и самая большая простиралась на много-много миль. Как холодно, как пустынно было в этих белых, ярко сверкающих чертогах!}")
            p("^^Как странно...")
          end;
        }:attr 'openable':disable();
      };
    }:attr 'scenery,supporter';

    obj {
      -"стол";
      nam = "#стол";
      description = function(s)
        p("За этим столом ты обычно делаешь... делала уроки.")
        return false
      end;
      ["before_Push,Pull,Transfer"] = "Пусть стоит там, где ему место.";
    }:attr 'scenery,supporter';

    obj {
      -"шкаф";
      description = function(s)
        p("Платяной шкаф с твоей одеждой.")
        if s:has("open") then
          p("Шкаф открыт.")
        end
        return false
      end;
      inside_dsc = "Ты находишься внутри шкафа.";
      title = "В шкафу";
      ["before_Push,Pull,Transfer"] = "Пусть стоит там, где ему место.";
      obj = {
        Useless {
          -"одежда";
        };
      };
    }:attr 'scenery,openable,container,enterable';

    obj {
      -"кровать";
      before_Enter = "Хотя ты валишься с ног, ещё не время спать.";
      ["before_Push,Pull,Transfer"] = "Пусть стоит там, где ей место.";
    }:attr 'enterable,supporter,scenery';

    obj {
      -"окно";
      nam = "#окно";
      description = function(s)
        p("В окне ты видишь пустынный белый пейзаж.")
        if _'сова2'.num >= 3 and not _'сова2'.finside then
          p("Ты видишь за окном полярную сову.")
          move(_'сова2', here())
        end
        return false
      end;
      when_open = "Окно открыто. В твою комнату залетают колючие снежинки.";
      before_Enter = "Это слишком опасно.";
    }:attr 'scenery,openable';

    Prop {
      -"стена|шуруп";
      nam = "#стена";
      before_Exam = function(s, w, wh)
        if where(_'зеркало') ~= s then
          p("На стене у шкафа висело зеркало. Сейчас его нет.")
        else
          p("На стене висит зеркало.")
        end
      end;
    };

    Prop {
      -"стены|потолок|пол|снежинки";
    };

    Prop {
      -"мебель";
      before_Exam = "Здесь есть: стол, кровать, шкаф и полки.";
    };
  };
}

Useless {
  -"одежда";
}

room {
  -"зал";
  nam = "Зал_с_зеркалами";
  cant_go = "Ты можешь плутать по залу вечность. Ты раздавлена его масштабами и не видишь смысла блуждать между зеркалами в поисках чего-либо, кроме пустоты.";
  d_to = function(s)
    p("Интересно, есть ли другие лестницы ведущие ещё глубже?")
  end;
  daemon = function(s)
    if fn_rnd(100) < 25 then
      local t = fn_tbl5()
      p(t[fn_rnd(#t)])
    end
  end;
  dsc = [[Ты находишься в громадном зале. Ты даже боишься представить его размеры. Километры ледяных стен подсвеченные всполохами полярных сияний.
Высокие колонны пронзают пространство зала. Куда хватает взгляда ты видишь, что зал заполнен зеркалами. По залу кружатся мелкие колючие снежинки.^^
Здесь есть спиральная лестница, ведущая наверх.]];
  e_to = function(s)
    if not s.know then
      return false
    end
    p("Ты решила осмотреть восточное направление. Ведь именно туда дула метель. Ты долго шла на восток, сверяясь с компасом и вглядываясь в бесконечную\nчереду зеркал, но так ничего и не обнаружила. Разочарованная, ты вернулась к лестнице.")
  end;
  enter = function(s, f)
    if f == _'Тронный_зал' then
      p("Это была очень длинная лестница без перил. Закручиваясь спиралью вокруг массивной колонны, она вела глубоко вниз.^\nОпасный и долгий спуск по скользким ступенькам занял продолжительное время и открыл твоему взору грандиозный вид.")
    end
    DaemonStart(s)
  end;
  exit = function(s, t)
    if t == _'Тронный_зал' then
      p("Не без труда преодолевая скользкие ступени, ты покидаешь громадный зал.")
    end
    DaemonStop(s)
  end;
  know = false;
  o_to = '#лестница';
  u_to = 'Тронный_зал';
  w_to = function(s)
    if not s.know then
      return false
    end
    return _'портал1'
  end;
  ["before_Drop,ThrowAt"] = function(s, w, wh)
    if not (w == _'перо') then
      return false
    end
    if mp:check_held(w) then
      return
    end
    if s.know then
      p("Ты снова выпускаешь перо из рук и убеждаешься ещё раз, что метель дует с запада.")
    else
      p("Ты выпускаешь перо из рук и видишь, как оно улетает строго на восток. Это значит, что метель дует с запада.")
    end
    move(w, s)
    s.know = true
  end;
  obj = {
    obj {
      -"лестница";
      nam = "#лестница";
      description = "Широкая лестница без перил, закрученная спиралью вокруг массивной колонны, ведёт наверх -- к тронному залу.";
      ["before_Enter,Walk,Climb"] = function(s, w, wh)
        walk(_'Тронный_зал')
      end;
    }:attr 'scenery';

    obj {
      -"колонны";
      description = "Ты думаешь, что высота колонн может достигать пятидесяти метров.";
    }:attr 'scenery';

    obj {
      -"колонна";
      description = "Ледяная колонна уходит вертикально вверх. Ты думаешь, что высота колонны может достигать пятидесяти метров.";
    }:attr 'scenery';

    obj {
      -"потолок|потолки";
      description = "Потолок подсвечивается всполохами, похожими на полярное сияние.";
    }:attr 'scenery';

    obj {
      -"пол|поверхность";
      description = "Поверхность пола -- абсолютно гладкая ледяная поверхность.";
    }:attr 'scenery';

    obj {
      -"стены|стена";
      description = "Километры стен подсвечиваются всполохами, похожими на полярное сияние.";
    }:attr 'scenery';

    obj {
      -"зеркала|зеркало";
      description = [[Зеркала повсюду. Они разной формы, разного размера. Они висят на колоннах, вморожены в глыбы льда, закреплены на фрагментах стен.
Ты даже боишься представить сколько их может быть здесь, в этом громадном зале.]];
      before_Attack = "Ты не разобьешь их всех.";
      ["before_Push,Pull,Transfer"] = "Стоит ли это делать?";
      before_Search = function(s, w, wh)
        p("Ты подошла к одному из зеркал и заглянула в него. Странно, но вместо своего отражения ты видишь нечто другое....^^")
        local t = fn_tbl6()
        pn(t[fn_rnd(#t)])
        p("Изображение в зеркале статично. Словно кто-то сделал стоп-кадр. Ты отходишь от зеркала.")
      end;
      before_Take = "Зачем тебе это?";
      before_Touch = "Ты коснулась одного из зеркал. Холодное.";
    }:attr 'scenery';

    obj {
      -"снежинки|метель|ветер";
      description = "Интересно, откуда здесь снег? Странно, но тебе кажется, что метель дует с определённого направления...";
      before_Listen = "Тихо...";
    }:attr 'scenery';

    obj {
      -"всполохи|сияние";
      description = "Это похоже на полярное сияние. Правда, ты никогда не видела полярное сияние по-настоящему...";
    }:attr 'scenery';
  };
}

cutscene {
  nam = "портал1";
  text = [[Ты решаешь осмотреть западное направление. Ведь именно оттуда дует метель и эта загадка требует ответа.^^
		Ты идёшь на запад, сверяясь с компасом и вглядываясь в бесконечные зеркала. Сила ветра всё возрастает.^^
		Идти становится всё труднее и ты почти отчаялась, когда вдруг, ты замечаешь впереди нечто странное...]];
  next_to = 'ледяное_пламя';
  title = false;
}

room {
  nam = "ледяное_пламя";
  cant_go = "Ты можешь плутать по залу вечность. Ты раздавлена его масштабами и не видишь смысла искать здесь что-нибудь кроме пустоты.";
  daemon = function(s)
    if _'браслет':has("worn") then
      s.warm = s.warm + 1
      if s.warm == 3 then
        p("Ты чувствуешь, как браслет согревает твою руку.")
      elseif s.warm == 4 then
        p("Ты чувствуешь, как от браслета на твоей руке по телу начинает разливаться тепло.")
      elseif s.warm == 5 then
        p("Ты чувствуешь, как от браслета на твоей руке по телу разливается тепло.")
      elseif s.warm > 5 then
        p("Ты чувствуешь, как браслет согревает тебя.")
      end
    end
  end;
  dsc = function(s)
    p("Ты видишь перед собой мерцающее свечение. Словно пламя огромного фиолетового огня, пучки сияния вырываются из постамента\nи уходят высоко вверх. Переплетаясь между собой, языки странного пламени не греют.")
    if s.warm <= 5 then
      p("Наоборот, ты чувствуешь сильный всепроникающий холод.^^")
    else
      p("Наоборот, они излучают пронзительный холод. К счастью, ты чувствуешь как браслет защищает тебя от него.^^")
    end
    p("Ты пришла сюда с востока.")
  end;
  enter = function(s)
    s.warm = 0
    DaemonStart(s)
  end;
  exit = function(s)
    DaemonStop(s)
  end;
  ["out_to,e_to"] = 'Зал_с_зеркалами';
  title = "У ледяного огня";
  warm = 0;
  after_Disrobe = function(s, w, wh)
    if w == _'браслет' then
      s.warm = 0
    end
    return false
  end;
  obj = {
    obj {
      -"постамент";
      nam = "#постамент";
      description = function(s)
        p("Массивный постамент представляет из себя ледяную глыбу квадратной формы.")
        return false
      end;
      ["before_Enter,Climb"] = function(s, w, wh)
        fn_xaction('Enter', _'#пламя')
      end;
      obj = {
        obj {
          -"сияние|пламя|огонь|свечение";
          nam = "#пламя";
          dsc = "На постаменте пылает ледяное пламя.";
          before_Default = function(s, ev, w)
            if ev == 'ThrownAt' or ev == 'Receive' then
              p([["Тебе жаль расставаться с ", w:noun'тв', '. Ведь ты не сможешь забрать ', w:it'вн', ' назад.']])
            else
              p("Как ты сделаешь это?")
            end
          end;
          before_Enter = function(s, w, wh)
            if visited(_'gotmirror') then
              p("Ты уже взяла то, что тебе было нужно.")
              return
            end
            if here().warm <= 5 then
              walk(_'badend3')
            else
              walk(_'gotmirror')
            end
          end;
          before_Exam = "Языки странного огня излучают холод.";
          before_Listen = "Ты слышишь потрескивание.";
          before_Take = "Это невозможно взять.";
          before_Touch = function(s, w, wh)
            if here().warm <= 5 then
              p("Твоя рука моментально начинает замерзать. Лучше не пытаться это делать.")
            else
              p("Ты чувствуешь прохладу.")
            end
          end;
        };
      };
    }:attr 'scenery,supporter,enterable';
  };
}

cutscene {
  nam = "badend3";
  exit = function(s)
    pic_pop()
  end;
  next_to = 'ледяное_пламя';
  onenter = function(s, f)
    pic_push('99')
  end;
  title = "Конец";
  text = {
    [[Превозмогая холод, ты поднимаешься на пьедестал и входишь в ледяное пламя.^^
		Непонятно, на какое чудо ты надеялась? Ледяное пламя охватывает тебя.^^
		Ты успеваешь заметит, как твое тело превращается в лёд...^^
		{$fmt b|{$fmt c|КОНЕЦ}}]];
    "{$fmt r|{$fmt em|Но всё могло закончиться по другому...}}";
  };
}

obj {
  -"зеркало";
  nam = "зеркало";
  description = function(s)
    p("Небольшое овальное зеркало.")
    if fn_seen('королева2') then
      p("Поверхность зеркала сияет фиолетовым светом.")
    end
  end;
  seen = false;
  before_Attack = function(s, w, wh)
    if s.seen then
      p("Там твоя мама!")
    else
      p("Зачем разбивать зеркало, которое ты так долго искала?")
    end
  end;
  before_Enter = function(s, w, wh)
    if fn_seen('королева2') then
      walk(_'комната2')
    else
      return false
    end
  end;
  before_PutOn = function(s, w, wh)
    if mp:check_held(s) then
      return
    end
    if w == _'#стена' and here() == _'комната' then
      move(s, w)
      p("Ты нашла в стене одинокий шуруп и повесила на него зеркало.")
      return
    end
    return false
  end;
  before_Search = function(s, w, wh)
    if here() == _'комната' and not _'сова2'.finside and not s.seen then
      _'сова2'.num = 0
      DaemonStart(_'сова2')
    end
    s.seen = true
    p("Вместо своего отражения, ты видишь в зеркале свою маму! {$fmt em|Настоящую} маму.")
    if where(s) == _'#стена' then
      p("Ты видишь в зеркале комнату. Все вещи в ней находятся на своих местах.")
    end
    if fn_seen('королева2') then
      p("Поверхность зеркала сияет фиолетовым светом.")
    end
  end;
  before_Take = function(s, w, wh)
    if fn_seen('королева2') then
      p("Лучше как можно быстрее бежать отсюда!")
      return
    end
    p("Ты забираешь зеркало.")
    move(s, me())
  end;
  before_Touch = function(s, w, wh)
    if fn_seen('королева2') then
      p("Твоя рука свободно проходит сквозь поверхность зеркала.")
    else
      p("Какое оно холодное...")
    end
  end;
}

cutscene {
  nam = "gotmirror";
  text = [[Ты входишь в ледяное пламя и странное свечение окутывает тебя со всех сторон.^^
		Ничто живое не смогло бы пережить этот холод, но ты чувствуешь, как тебя согревает браслет матери.^^
		Ты вглядываешься в фиолетовые языки ледяного пламени и вдруг замечаешь, что можешь охватить взором весь этот громадный зал.^^
		Сотни тысяч зеркал, среди которых есть то, что ты ищешь...^^
		Ты протягиваешь руки и вот -- ты уже держишь его! Зеркало из твоей комнаты. Ты выходишь из ледяного пламени.]];
  exit = function(s)
    take(_'зеркало')
    remove(_'королева')
  end;
  next_to = 'ледяное_пламя';
  title = false;
}

cutscene {
  nam = "happyend";
  exit = function(s)
    pic_set('81')
  end;
  next_to = "titles";
  onenter = function(s, f)
    pic_set('31')
  end;
  title = "Конец";
  text = {
    "-- Ты что -- совсем рехнулась?";
    "... Что ты устраиваешь?";
    "... Я понимаю, ты не хочешь этого переезда, но надо держать себя в руках!";
    "... Определённо, тебя надо показать психологу!";
    "... Ты бы видела себя! Ты же способна сделать что угодно!";
    "-- Всё хорошо, мама. Я собрала вещи мы можем ехать.";
    "-- Что?";
    "-- Всё хорошо. У нас теперь всё будет хо-ро-шо!...";
  };
}

cutscene {
  nam = "yes";
  next_to = 'Тьма';
  title = false;
  text = {
    "Звук твоих слов еще отражался от стен комнаты, когда ты услышала смех {$fmt em|другой} мамы.";
    "-- Как просто! Тебе так и не помог {$fmt em|её} талисман! Теперь я свободна!";
    "Ты снова услышала её дьявольский смех. А потом наступила тьма...";
  };
}

room {
  nam = "Тьма";
  before_Cry = function(s, w, wh)
    s.num = s.num + 1
    if s.num < 5 or have(_'скрипка') then
      p("Тебя душат рыдания.")
      if s.num == 1 then
        p("Но у тебя нет глаз, чтобы плакать.")
      elseif s.num == 2 then
        p("Отчаяние захватило тебя.")
      elseif s.num == 3 then
        p("Но можно ли плакать без глаз?")
      else
        p("Ты едва сдерживаешься.")
        if have(_'скрипка') then
          p("Ты чувствуешь в своих руках скрипку.")
        end
      end
    else
      walk(_'cry')
    end
  end;
  before_Play = function(s, w)
    if not w then
      w = _'скрипка'
    end
    if not (w == _'скрипка') then
      return false
    end
    if not fn_tiny() then
      fn_music('mus/violin.ogg', 1)
    end
    walk(_'cry2')
  end;
  num = 0;
  before_Default = "Отчаяние захватило тебя. Всё, что ты можешь делать это думать и плакать.";
  before_Think = "Ты думаешь, что навсегда останешься здесь. Мама! Забери меня отсюда!";
  before_Wait = "Проходит немного времени.";
}:attr '~light'

cutscene {
  nam = "cry2";
  exit = function(s)
    remove(_'сова2')
    move(_'королева2', _'комната')
    _'королева2'.violin = true
    _'зеркало':attr("enterable")
  end;
  next_to = 'комната';
  title = false;
  text = {
    [[Ты берёшь в руки скрипку и извлекаешь первые ноты.^^
		Комната наполнятся звуками.^^
		Отчаяние всё ещё душит тебя. Но постепенно под натиском музыки оно отступает.^^
		Ты чувствуешь как музыка проникает сквозь стены, уносится вверх, спускается глубоко вниз. В самые глубины ледяного замка, в каждый его уголок...^^
		"Дрянь! Дрянь! Дрянь!" -- раздаётся искорёженный ненавистью голос.^^
		"Дрянная девчонка!" -- это {$fmt em|её} голос.]];
    "{$fmt b|{$fmt c|ВСПЫШКА}}";
  };
}

cutscene {
  nam = "cry";
  exit = function(s)
    remove(_'сова2')
    move(_'королева2', _'комната')
    _'зеркало':attr("enterable")
  end;
  next_to = 'комната';
  title = false;
  text = {
    [[Наконец, рыдания прорываются наружу и ты плачешь. Несмотря на то, что у тебя нет глаз, ты чувствуешь как по лицу текут тёплые слёзы.^^
		"Дрянь! Дрянь! Дрянь!" -- раздаётся искорёженный ненавистью голос.^^
		"Дрянная девчонка!" -- это {$fmt em|её} голос.]];
    "{$fmt b|{$fmt c|ВСПЫШКА}}";
  };
}

obj {
  -"Снежная Королева|королева|женщина|другая мама";
  nam = "королева2";
  each_turn = function(s)
    local t = fn_tbl7()
    p(t[fn_rnd(#t)])
  end;
  violin = false;
  before_Default = "Лучше держаться от неё подальше.";
  before_Exam = function(s, w, wh)
    if s.violin then
      p("Она закрывает уши руками. Ты видишь под её ладонями кровь.")
    else
      p("Она закрывает лицо руками. Ты видишь под её ладонями кровь.")
    end
  end;
}:attr 'scenery'

obj {
  -"мама|мать";
  nam = "мама2";
  description = "Это твоя мама. Милая, родная мама!";
  init_dsc = "В комнате находится твоя мама. Немой вопрос застыл на её губах.";
  talk_to = function(s)
    if fn_seen('зеркало2') then
      p("Сначала нужно завершить кое-какое дело.")
    else
      walk(_'happyend')
    end
  end;
  ["before_Touch,Kiss"] = [[Ты бросаешься маме на шею и обнимаешь её.^
-- Мамочка!]];
}:attr 'animate'

obj {
  -"зеркало";
  nam = "зеркало2";
  description = "Ты видишь, что поверхность зеркала имеет фиолетовый оттенок.";
  init_dsc = "На стене висит зеркало.";
  ["before_Attack,Take,Remove"] = function(s, w, wh)
    p("Ты берёшь зеркало в руки и с размаху бросаешь на пол. Сотни мелких осколков разлетаются по всей комнате.^^\n-- Что, черт возьми, ты себе позволяешь? -- слышишь ты, наконец, голос мамы.")
    remove(s)
  end;
  before_Search = "Тебе кажется, что ты видишь за зеркалом Снежную Королеву!";
}

room {
  nam = "комната2";
  dsc = "Ты находишься в своей настоящей комнате. Все вещи находятся там, где и должны быть.";
  enter = function(s)
    pn("Ты бросаешься к зеркалу понимая, что это твой последний шанс на спасение.")
    p("Фиолетовое свечение заполняет всё и ты оказываешься... В своей комнате.")
  end;
  out_to = function(s)
    p("Сначала нужно завершить кое-какое дело.")
  end;
  title = "Комната";
  obj = {
    'зеркало2';
    'мама2';

    Prop {
      -"вещи|кровать|стол|стул|шкаф|стена|осколки";
    };
  };
}

Verb { '#LookIn', "смотреть", "в|во {noun}/вн : Search" }

Verb { '#Sit', "сесть", "на {noun}/вн : Enter" }

if false then
global 'hint_num' (5)
function use_hint()
end
function mp:before_Think()
  if here() ^ 'Тьма' then
    return false
  end
  if here() ^ 'В_машине' then
    if use_hint() then
      return
    end
    p [[Тебе приходит в голову ]];
    if not visited'разговор1' then
      p [[поговорить с матерью.]]
    elseif not _'телефон'.seen then
      p [[смотреть в телефон.]]
    elseif have 'телефон' then
      p [[отдать телефон матери.]]
    elseif blizzard == 0 then
      p [[смотреть в окно.]]
    elseif blizzard == 1 then
      p [[поговорить с матерью.]]
    elseif blizzard < 11 then
      p [[ждать.]]
    else
      p [[выйти из машины.]]
    end
    return
  end
  if here() ^ 'поле' then
    if use_hint() then
      return
    end
    p [[Тебе приходит в голову ]];
    if not have 'телефон' or not have 'браслет' then
      p [[осмотреть машину.]]
      if not _'бардачок':has'open' then
        p [[Затем открыть бардачок.]]
      else
        p [[взять всё из бардачка.]]
      end
    elseif not have 'скрипка' then
      p [[взять скрипку.]]
    elseif not _'телефон'.compass then
      p [[посмотреть в телефон. В нём есть компас.]]
    elseif not _'сова'.talked then
      if not seen 'сова' then
        p [[идти в лес.]]
      else
        if _'сова'.seen then
          p [[поговорить с совой.]]
        else
          p [[осмотреть сову.]]
        end
      end
    elseif not have 'перо' then
      p [[взять перо.]]
    else
      p [[идти в лес.]]
    end
    return
  end
  if here() ^ 'В_лесу' then
    if use_hint() then
      return
    end
    p [[Тебе приходит в голову ]];
    if not _'сова'.talked then
      if where'сова' ^ 'В_лесу' then
        p [[ждать.]];
      else
        p [[идти на восток.]];
      end
    elseif not seen 'олень' or disabled 'олень' then
      p [[идти на запад.]]
    elseif not _'олень'.sit then
      p [[дать оленю перо.]]
    else
      p [[сесть на оленя.]]
    end
    return
  end
  if here() ^ 'Ледяные_горы' then
    if use_hint() then
      return
    end
    p [[Тебе приходит в голову ]]
    if _'#стена'.light == 0 then
      p [[дотронуться стены.]]
    else
      p [[войти в свечение.]]
    end
    return
  end
  if here() ^ 'пещера' then
    if use_hint() then
      return
    end
    p [[Тебе приходит в голову ]]
    if thedark(here) then
      p [[посветить телефоном.]]
    elseif disabled '#кристаллы' then
      p [[осмотреть свечение.]]
    elseif _'#кристаллы'.try < 2 then
      p [[постучать по кристаллам.]]
    elseif not _'#кристаллы'.broken then
      p [[играть на скрипке.]]
    elseif seen 'осколки' then
      p [[взять осколки.]]
    else
      p [[идти на северо-запад.]]
    end
    return
  end
  if here() ^ 'пещера2' then
    if use_hint() then
      return
    end
    p [[Тебе приходит в голову ]]
    if not seen 'осколки' then
      if not have'осколки' then
        p [[идти на юго-восток.]]
      else
        p [[бросить осколки.]]
      end
    elseif thedark(here) then
      p [[включить фонарик.]]
    else
      p [[идти на юго-запад.]]
    end
    return
  end
  if here() ^ 'обрыв' then
    if use_hint() then
      return
    end
    p [[Тебе приходит в голову перепрыгнуть через обрыв.]]
    return
  end
  if here() ^ 'Другая_сторона' then
    if use_hint() then
      return
    end
    p [[Тебе приходит в голову выйти наружу.]]
    return
  end
  if here() ^ 'За_ледяной_стеной' then
    if use_hint() then
      return
    end
    p [[Тебе приходит в голову идти к скале.]]
    return
  end
  if here() ^ 'У_замка' then
    if use_hint() then
      return
    end
    p [[Тебе приходит в голову ]]
    if disabled 'ворота' then
      p [[дать перо статуе.]]
    else
      p [[войти внутрь.]]
    end
    return
  end
  if here() ^ 'Тронный_зал' then
    if use_hint() then
      return
    end
    p [[Тебе приходит в голову ]]
    if visited 'gotmirror' and not _'зеркало'.seen then
      p [[посмотреть в зеркало.]]
    elseif _'браслет':hasnt'worn' then
      p [[надеть браслет.]]
    elseif not _'Тронный_зал'.near then
      p [[подойти к матери.]]
    elseif not _'королева'.queen then
      p [[осмотреть мать.]]
    elseif not visited 'королева_диалог' then
      p [[поговорить с матерью.]]
    elseif disabled 'дверь' then
      p [[идти к голему.]]
    elseif not visited 'gotmirror' then
      p [[идти вниз.]]
    elseif _'дверь':has'open' then
      p [[идти в дверь.]]
    else
      p [[открыть дверь.]]
    end
    return
  end
  if here() ^ 'Зал_с_зеркалами' then
    if use_hint() then
      return
    end
    p [[Тебе приходит в голову ]]
    if not _'Зал_с_зеркалами'.know then
      p [[бросить перо.]]
    elseif not have 'перо' then
      p [[взять перо.]]
    elseif visited 'gotmirror' then
      p [[идти наверх.]]
    else
      p [[идти на запад.]]
    end
    return
  end
  if here() ^ 'ледяное_пламя' then
    if use_hint() then
      return
    end
    p [[Тебе приходит в голову ]]
    if visited 'gotmirror' then
      if not _'зеркало'.seen then
        p [[посмотреть в зеркало.]]
      else
        p [[идти на восток.]]
      end
    elseif _'ледяное_пламя'.warm <= 5 then
      p [[ждать.]]
    else
      p [[войти в пламя.]]
    end
    return
  end
  if here() ^ 'комната' then
    if use_hint() then
      return
    end
    p [[Тебе приходит в голову ]]
    if seen 'королева2' then
      p [[войти в зеркало.]]
      return
    end
    if not seen 'зеркало' and not have 'зеркало' then
      if not visited 'gotmirror' then
        p [[выйти из комнаты.]]
      else
        p [[идти и забрать зеркало оттуда, где ты его оставила.]]
      end
    elseif not _'зеркало'.seen then
      p [[Посмотреть в зеркало.]]
    elseif not _'сова2'.finside and _'сова2'.num < 3 then
      p [[ждать.]]
    elseif _'#окно':hasnt'open' and not _'сова2'.finside then
      p [[открыть окно.]]
    elseif not visited 'сова2_диалог1' and not visited 'сова2_диалог1' then
      p [[поговорить с совой.]]
    elseif not _'зеркало':where() ^ '#стена' then
      p [[повесить зеркало на стену.]]
    else
      p [[поговорить с совой.]]
    end
    return
  end
  if here() ^ 'Тьма' then
    return false
  end
  return false
end
end

function mp:Sing()
  p [[То, что ты учишься в музыкальной школе не означает, что ты хорошо поёшь.]]
end

Verb { '#Ring', "[|по]звон/ить", "Ring" }
mp.Ring = function(s, w, wh)
  if not have(_'телефон') then
    p("У тебя нет телефона.")
    return
  end
  if fn_seen('#мама') then
    p("Тебе сейчас некому звонить.")
    return
  end
  if _'телефон'.compass then
    p("Нет приёма.")
    return
  end
  p("Странно, нет приёма.")
end

Verb { '#SwitchOn2', "завести/,завед/и", "~ {noun}/вн :SwitchOn" }

Verb { '#WalkThrough', "идти,иди", "~ сквозь {noun}/вн,scene :Enter" }

Verb { '#Give', "дать,отда/ть,предло/жить,предла/гать,дам,даю,дадим", "{noun}/вн,held {noun}/дт,scene : Give", "~ {noun}/дт,scene {noun}/вн,held : Give reverse" }
