name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:
  pull_request:

env:
    luajit_ver: 2.0.5
    sdl_ver: 2.24.0
    freetype_ver: 2.12.1

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache libs
        id: cache-libs
        uses: actions/cache@v3
        with:
          path: |
            external
          key: ${{ runner.os }}-${{ env.luajit_ver }}-${{ env.sdl_ver }}-${{ env.freetype_ver }}

      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y gcc-mingw-w64-i686 mingw-w64-i686-dev binutils-mingw-w64-i686 gcc-multilib git
          sudo apt-get install -y build-essential

      - name: build
        run: |
          contrib/build-release.sh

      - name: Create Artifact
        run: |
          mkdir -p artifact/reinstead
          cp -r release/* artifact/reinstead

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: reinstead
          path: artifact
          retention-days: 1
