name: CI

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: CI (${{ matrix.sdl }})
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - sdl: sdl2
          - sdl: sdl3
    steps:
      - uses: actions/checkout@v7

      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libsdl2-dev libsdl3-dev libluajit-5.1-dev libfreetype-dev
          sudo apt-get install -y build-essential

      - name: build-default
        run: SDLVER=${{ matrix.sdl }} ./make-default.sh

      - name: build-make
        run: |
          make clean
          make SDLVER=${{ matrix.sdl }}

      - name: build-freetype
        run: |
          make clean
          make WITH_FREETYPE=1 SDLVER=${{ matrix.sdl }}

      - name: build-schrift
        run: |
          make clean
          make WITH_SCHRIFT=1 SDLVER=${{ matrix.sdl }}
