# instead-cli: Windows build with mingw-w64 (static).
#
#   make -f Makefile.mingw
#
# The client is built with the bundled Lua (../../src/lua) and links statically,
# including GNU libiconv, which is built for mingw by ./libiconv.sh: mingw-w64
# itself ships no iconv.

CC  := i686-w64-mingw32-gcc
EXE := .exe

BUILD := build/mingw

ICONV_DIR   ?= external
ICONV_STAMP := $(ICONV_DIR)/.stamp

CFLAGS  += -mconsole -D_HAVE_ICONV -I$(ICONV_DIR)/include
LDFLAGS += -static -lm -L$(ICONV_DIR)/lib -liconv
EXTRA_DEPS := $(ICONV_STAMP)

include Makefile.common

libiconv: $(ICONV_STAMP)

$(ICONV_STAMP):
	./libiconv.sh
